// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using Honua.Server.Features.Admin.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Honua.Server.Features.Admin;

/// <summary>
/// Admin API endpoints for configuration discovery and management.
/// </summary>
[ApiController]
[Route("admin/configuration")]
[Authorize(Policy = "AdminOnly")]
public sealed class ConfigurationDiscoveryEndpoints : ControllerBase
{
    private readonly ConfigurationDiscoveryService _discoveryService;
    private readonly ILogger<ConfigurationDiscoveryEndpoints> _logger;

    public ConfigurationDiscoveryEndpoints(
        ConfigurationDiscoveryService discoveryService,
        ILogger<ConfigurationDiscoveryEndpoints> logger)
    {
        _discoveryService = discoveryService;
        _logger = logger;
    }

    /// <summary>
    /// Discovers all configuration types and their metadata.
    /// </summary>
    /// <returns>Configuration discovery results</returns>
    [HttpGet("discover")]
    public async Task<ActionResult<ConfigurationDiscoveryResult>> DiscoverConfigurationAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var result = await _discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Ok(result);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to discover configuration");
            return StatusCode(500, new { error = "Configuration discovery failed", details = ex.Message });
        }
    }

    /// <summary>
    /// Gets metadata for all discovered configuration types.
    /// </summary>
    /// <returns>Configuration metadata summary</returns>
    [HttpGet("metadata")]
    public async Task<ActionResult<List<ConfigurationMetadata>>> GetConfigurationMetadataAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var result = await _discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Ok(result.ExtractedMetadata);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get configuration metadata");
            return StatusCode(500, new { error = "Failed to retrieve configuration metadata", details = ex.Message });
        }
    }

    /// <summary>
    /// Gets auto-generated documentation for configuration types.
    /// </summary>
    /// <returns>Auto-generated documentation</returns>
    [HttpGet("auto-documentation")]
    public async Task<ActionResult<List<AutoGeneratedDocumentationSection>>> GetAutoDocumentationAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var result = await _discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Ok(result.AutoGeneratedDocumentation);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to generate auto-documentation");
            return StatusCode(500, new { error = "Auto-documentation generation failed", details = ex.Message });
        }
    }

    /// <summary>
    /// Validates all secret references in the configuration.
    /// </summary>
    /// <returns>Secret validation results</returns>
    [HttpGet("secrets/validate")]
    public async Task<ActionResult<SecretValidationResult>> ValidateSecretsAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var result = await _discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Ok(result.SecretValidation);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to validate secrets");
            return StatusCode(500, new { error = "Secret validation failed", details = ex.Message });
        }
    }

    /// <summary>
    /// Gets configuration audit information.
    /// </summary>
    /// <returns>Configuration audit details</returns>
    [HttpGet("audit")]
    public async Task<ActionResult<ConfigurationAuditInfo>> GetAuditInfoAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var result = await _discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Ok(result.AuditInformation);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get audit information");
            return StatusCode(500, new { error = "Audit information retrieval failed", details = ex.Message });
        }
    }

    /// <summary>
    /// Gets configuration summary with key statistics.
    /// </summary>
    /// <returns>Configuration summary</returns>
    [HttpGet("summary")]
    public async Task<ActionResult<ConfigurationSummary>> GetConfigurationSummaryAsync(CancellationToken cancellationToken = default)
    {
        try
        {
            var result = await _discoveryService.DiscoverConfigurationAsync(cancellationToken);

            var summary = new ConfigurationSummary
            {
                TotalTypes = result.DiscoveredTypes.Count,
                RegisteredTypes = result.DiscoveredTypes.Count(t => t.IsRegisteredInDi),
                TotalProperties = result.DiscoveredTypes.Sum(t => t.Properties.Count),
                SecretProperties = result.DiscoveredTypes.Sum(t => t.Properties.Count(p => p.IsSecret)),
                RequiredProperties = result.DiscoveredTypes.Sum(t => t.Properties.Count(p => p.IsRequired)),
                TypesWithValidation = result.DiscoveredTypes.Count(t => t.Properties.Any(p => p.ValidationRules.Count > 0)),
                TotalSecrets = result.SecretValidation.TotalSecrets,
                ValidSecrets = result.SecretValidation.ValidSecrets,
                InvalidSecrets = result.SecretValidation.InvalidSecrets,
                Environment = result.AuditInformation.Environment,
                DiscoveryDurationMs = result.DiscoveryDurationMs,
                LastDiscovery = result.Timestamp
            };

            return Ok(summary);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to get configuration summary");
            return StatusCode(500, new { error = "Configuration summary failed", details = ex.Message });
        }
    }
}

/// <summary>
/// Configuration summary for dashboard display.
/// </summary>
public sealed class ConfigurationSummary
{
    /// <summary>
    /// Total number of configuration types discovered.
    /// </summary>
    public int TotalTypes { get; set; }

    /// <summary>
    /// Number of types registered in dependency injection.
    /// </summary>
    public int RegisteredTypes { get; set; }

    /// <summary>
    /// Total number of properties across all types.
    /// </summary>
    public int TotalProperties { get; set; }

    /// <summary>
    /// Number of properties containing secret data.
    /// </summary>
    public int SecretProperties { get; set; }

    /// <summary>
    /// Number of required properties.
    /// </summary>
    public int RequiredProperties { get; set; }

    /// <summary>
    /// Number of types with validation rules.
    /// </summary>
    public int TypesWithValidation { get; set; }

    /// <summary>
    /// Total number of secrets found.
    /// </summary>
    public int TotalSecrets { get; set; }

    /// <summary>
    /// Number of valid secrets.
    /// </summary>
    public int ValidSecrets { get; set; }

    /// <summary>
    /// Number of invalid secrets.
    /// </summary>
    public int InvalidSecrets { get; set; }

    /// <summary>
    /// Current environment.
    /// </summary>
    public string Environment { get; set; } = string.Empty;

    /// <summary>
    /// Discovery operation duration in milliseconds.
    /// </summary>
    public long DiscoveryDurationMs { get; set; }

    /// <summary>
    /// When the discovery was last performed.
    /// </summary>
    public DateTimeOffset LastDiscovery { get; set; }
}
