// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using Honua.Server.Features.Admin.Models;
using Honua.Server.Features.Admin.Services;
using Honua.Server.Features.Infrastructure.Authentication;
using Honua.Server.Features.Infrastructure.Models;

namespace Honua.Server.Features.Admin;

/// <summary>
/// Admin endpoints for configuration discovery and management.
/// </summary>
internal static class ConfigurationDiscoveryEndpoints
{
    /// <summary>
    /// Maps configuration discovery endpoints.
    /// </summary>
    /// <param name="endpoints">The endpoint route builder.</param>
    public static void MapConfigurationDiscoveryEndpoints(this IEndpointRouteBuilder endpoints)
    {
<<<<<<< HEAD
        var group = endpoints.MapGroup("/configuration")
            .WithTags("Admin", "Configuration");
=======
        var group = endpoints.MapGroup("/api/v{version:apiVersion}/admin/configuration")
            .WithApiVersionSet()
            .HasApiVersion(1, 0)
            .WithTags("Admin", "Configuration")
            .RequireAdminAuthorization();
>>>>>>> origin/trunk

        _ = group.MapGet("/discover", HandleDiscoverConfigurationAsync)
            .WithName("DiscoverConfiguration")
            .WithSummary("Discover all configuration types and metadata");

        _ = group.MapGet("/metadata", HandleGetConfigurationMetadataAsync)
            .WithName("GetConfigurationMetadata")
            .WithSummary("Get configuration metadata summary");

        _ = group.MapGet("/auto-documentation", HandleGetAutoDocumentationAsync)
            .WithName("GetConfigurationAutoDocumentation")
            .WithSummary("Get auto-generated configuration documentation");

        _ = group.MapGet("/secrets/validate", HandleValidateSecretsAsync)
            .WithName("ValidateConfigurationSecrets")
            .WithSummary("Validate secret references in configuration");

        _ = group.MapGet("/audit", HandleGetAuditInfoAsync)
            .WithName("GetConfigurationAuditInfo")
            .WithSummary("Get configuration audit information");

        _ = group.MapGet("/summary", HandleGetConfigurationSummaryAsync)
            .WithName("GetConfigurationSummary")
            .WithSummary("Get high-level configuration summary");
    }

    private static async Task<IResult> HandleDiscoverConfigurationAsync(
        HttpContext context,
        ConfigurationDiscoveryService discoveryService,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("Admin.ConfigurationDiscovery");

        try
        {
            var result = await discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Results.Json(result, ConfigurationDiscoveryJsonContext.Default.ConfigurationDiscoveryResult);
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.EndpointFailed(logger, "discover", ex.Message, ex);
            return ProblemDetailsHelpers.CreateAdminProblem(
                context,
                StatusCodes.Status500InternalServerError,
                "Configuration discovery failed");
        }
    }

    private static async Task<IResult> HandleGetConfigurationMetadataAsync(
        HttpContext context,
        ConfigurationDiscoveryService discoveryService,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("Admin.ConfigurationDiscovery");

        try
        {
            var result = await discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Results.Json(result.ExtractedMetadata, ConfigurationDiscoveryJsonContext.Default.ListConfigurationMetadata);
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.EndpointFailed(logger, "metadata", ex.Message, ex);
            return ProblemDetailsHelpers.CreateAdminProblem(
                context,
                StatusCodes.Status500InternalServerError,
                "Failed to retrieve configuration metadata");
        }
    }

    private static async Task<IResult> HandleGetAutoDocumentationAsync(
        HttpContext context,
        ConfigurationDiscoveryService discoveryService,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("Admin.ConfigurationDiscovery");

        try
        {
            var result = await discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Results.Json(
                result.AutoGeneratedDocumentation,
                ConfigurationDiscoveryJsonContext.Default.ListAutoGeneratedDocumentationSection);
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.EndpointFailed(logger, "auto-documentation", ex.Message, ex);
            return ProblemDetailsHelpers.CreateAdminProblem(
                context,
                StatusCodes.Status500InternalServerError,
                "Auto-documentation generation failed");
        }
    }

    private static async Task<IResult> HandleValidateSecretsAsync(
        HttpContext context,
        ConfigurationDiscoveryService discoveryService,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("Admin.ConfigurationDiscovery");

        try
        {
            var result = await discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Results.Json(result.SecretValidation, ConfigurationDiscoveryJsonContext.Default.SecretValidationResult);
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.EndpointFailed(logger, "secrets/validate", ex.Message, ex);
            return ProblemDetailsHelpers.CreateAdminProblem(
                context,
                StatusCodes.Status500InternalServerError,
                "Secret validation failed");
        }
    }

    private static async Task<IResult> HandleGetAuditInfoAsync(
        HttpContext context,
        ConfigurationDiscoveryService discoveryService,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("Admin.ConfigurationDiscovery");

        try
        {
            var result = await discoveryService.DiscoverConfigurationAsync(cancellationToken);
            return Results.Json(result.AuditInformation, ConfigurationDiscoveryJsonContext.Default.ConfigurationAuditInfo);
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.EndpointFailed(logger, "audit", ex.Message, ex);
            return ProblemDetailsHelpers.CreateAdminProblem(
                context,
                StatusCodes.Status500InternalServerError,
                "Audit information retrieval failed");
        }
    }

    private static async Task<IResult> HandleGetConfigurationSummaryAsync(
        HttpContext context,
        ConfigurationDiscoveryService discoveryService,
        ILoggerFactory loggerFactory,
        CancellationToken cancellationToken)
    {
        var logger = loggerFactory.CreateLogger("Admin.ConfigurationDiscovery");

        try
        {
            var result = await discoveryService.DiscoverConfigurationAsync(cancellationToken);
            var summary = CreateSummary(result);

            return Results.Json(summary, ConfigurationDiscoveryJsonContext.Default.ConfigurationSummary);
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.EndpointFailed(logger, "summary", ex.Message, ex);
            return ProblemDetailsHelpers.CreateAdminProblem(
                context,
                StatusCodes.Status500InternalServerError,
                "Configuration summary failed");
        }
    }

    private static ConfigurationSummary CreateSummary(ConfigurationDiscoveryResult result)
    {
        return new ConfigurationSummary
        {
            TotalTypes = result.DiscoveredTypes.Count,
            RegisteredTypes = result.DiscoveredTypes.Count(t => t.IsRegisteredInDi),
            TotalProperties = result.DiscoveredTypes.Sum(t => t.Properties.Count),
            SecretProperties = result.DiscoveredTypes.Sum(t => t.Properties.Count(p => p.IsSecret)),
            RequiredProperties = result.DiscoveredTypes.Sum(t => t.Properties.Count(p => p.IsRequired)),
            TypesWithValidation = result.DiscoveredTypes.Count(t => t.Properties.Any(p => p.ValidationRules.Count > 0)),
            TotalSecrets = result.SecretValidation.TotalSecrets,
            ValidSecrets = result.SecretValidation.ValidSecrets,
            InvalidSecrets = result.SecretValidation.InvalidSecrets,
            Environment = result.AuditInformation.Environment,
            DiscoveryDurationMs = result.DiscoveryDurationMs,
            LastDiscovery = result.Timestamp
        };
    }
}

/// <summary>
/// Configuration summary for dashboard display.
/// </summary>
internal sealed class ConfigurationSummary
{
    /// <summary>
    /// Total number of configuration types discovered.
    /// </summary>
    public int TotalTypes { get; set; }

    /// <summary>
    /// Number of types registered in dependency injection.
    /// </summary>
    public int RegisteredTypes { get; set; }

    /// <summary>
    /// Total number of properties across all types.
    /// </summary>
    public int TotalProperties { get; set; }

    /// <summary>
    /// Number of properties containing secret data.
    /// </summary>
    public int SecretProperties { get; set; }

    /// <summary>
    /// Number of required properties.
    /// </summary>
    public int RequiredProperties { get; set; }

    /// <summary>
    /// Number of types with validation rules.
    /// </summary>
    public int TypesWithValidation { get; set; }

    /// <summary>
    /// Total number of secrets found.
    /// </summary>
    public int TotalSecrets { get; set; }

    /// <summary>
    /// Number of valid secrets.
    /// </summary>
    public int ValidSecrets { get; set; }

    /// <summary>
    /// Number of invalid secrets.
    /// </summary>
    public int InvalidSecrets { get; set; }

    /// <summary>
    /// Current environment.
    /// </summary>
    public string Environment { get; set; } = string.Empty;

    /// <summary>
    /// Discovery operation duration in milliseconds.
    /// </summary>
    public long DiscoveryDurationMs { get; set; }

    /// <summary>
    /// When the discovery was last performed.
    /// </summary>
    public DateTimeOffset LastDiscovery { get; set; }
}

internal static partial class ConfigurationDiscoveryLog
{
    [LoggerMessage(
        EventId = 20006,
        Level = LogLevel.Error,
        Message = "Configuration discovery endpoint '{Endpoint}' failed: {Error}")]
    public static partial void EndpointFailed(ILogger logger, string endpoint, string error, Exception exception);
}
