#!/usr/bin/env python3
"""Generate the authoritative GeoParquet PROJJSON CRS catalog.

GeoParquet 1.1 stores per-column CRS as PROJJSON in the file's `geo` metadata.
There is no in-process PROJ library in the .NET server runtime, so we pre-generate
the PROJJSON for a curated set of common output CRS using pyproj (PROJ), commit it
as an embedded resource, and look it up at write time. Regenerate with:

    python scripts/geoparquet/generate-projjson-catalog.py

Requires: pyproj (PROJ). The PROJJSON produced here is byte-for-byte what
geopandas/GDAL write for the same CRS, so files round-trip through GeoParquet
readers (validated: each entry round-trips to its own EPSG code).

Format: top-level object is pretty-printed, but each SRID's PROJJSON value is a
single compact line so the resource diffs one line per CRS.
"""
import json
import sys
from pyproj import CRS

OUTPUT = "src/Honua.Core/Features/Infrastructure/Crs/Resources/geoparquet-crs-projjson.json"

def codes():
    yield 3857  # WGS 84 / Pseudo-Mercator (Web Mercator)
    # Common geographic datums (4326 included though normally emitted as the CRS84 default)
    yield from [4269, 4267, 4258, 4283, 4171, 4173, 4979, 4617, 4759, 4326]
    yield from range(32601, 32661)  # WGS 84 / UTM zone N
    yield from range(32701, 32761)  # WGS 84 / UTM zone S
    yield from range(25828, 25839)  # ETRS89 / UTM zone (Europe)
    yield from [
        27700, 2193, 3035, 3577, 5070, 2154, 31370, 2056,
        28992, 3006, 3067, 2180, 5514, 6933, 3395,
    ]

def main():
    entries = []
    seen = set()
    for code in sorted(set(codes())):
        if code in seen:
            continue
        seen.add(code)
        crs = CRS.from_epsg(code)
        pj = crs.to_json_dict()
        rt = CRS.from_json(json.dumps(pj))
        if rt.to_epsg() != code:
            print(f"FAIL EPSG:{code} round-trips to {rt.to_epsg()}", file=sys.stderr)
            sys.exit(1)
        entries.append((str(code), json.dumps(pj, sort_keys=True, separators=(",", ":"))))

    lines = []
    lines.append("{")
    lines.append('  "_comment": "AUTHORITATIVE GeoParquet PROJJSON CRS catalog. GENERATED by scripts/geoparquet/generate-projjson-catalog.py via pyproj/PROJ. Do not hand-edit; regenerate to add SRIDs. Each value is authoritative full PROJJSON that round-trips to its EPSG code.",')
    lines.append('  "crs": {')
    for i, (code, compact) in enumerate(entries):
        comma = "," if i < len(entries) - 1 else ""
        # code is a stringified int; embed the compact PROJJSON verbatim as the value.
        lines.append(f'    {json.dumps(code)}: {compact}{comma}')
    lines.append("  }")
    lines.append("}")
    with open(OUTPUT, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"Wrote {len(entries)} PROJJSON entries to {OUTPUT}")

if __name__ == "__main__":
    main()
