// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Diagnostics.CodeAnalysis;
using System.Reflection;
using System.Text.Json.Serialization;
using Honua.Core.Configuration;
using Honua.Core.Configuration.Validation;
using Honua.Core.Features.Caching;
using Honua.Core.Features.Infrastructure.Domain;
using Honua.Core.Features.Infrastructure.Monitoring;
using Honua.Core.Features.Security.Abstractions;
using Honua.Core.Features.Tiles;
using Honua.Server.Features.Infrastructure.Authentication;
using Honua.ServiceDefaults;
using Microsoft.Extensions.Options;

namespace Honua.Server.Features.Admin.Services;

/// <summary>
/// Enhanced configuration discovery service that provides automatic documentation
/// generation, metadata extraction, and introspection capabilities.
/// </summary>
internal sealed class ConfigurationDiscoveryService
{
    private readonly IServiceProvider _serviceProvider;
    private readonly IConfiguration _configuration;
    private readonly IWebHostEnvironment _environment;
    private readonly ILogger<ConfigurationDiscoveryService> _logger;
    private readonly ConfigurationDocumentationService _documentationService;

    public ConfigurationDiscoveryService(
        IServiceProvider serviceProvider,
        IConfiguration configuration,
        IWebHostEnvironment environment,
        ILogger<ConfigurationDiscoveryService> logger,
        ConfigurationDocumentationService documentationService)
    {
        _serviceProvider = serviceProvider;
        _configuration = configuration;
        _environment = environment;
        _logger = logger;
        _documentationService = documentationService;
    }

    /// <summary>
    /// Discovers all IOptions configuration classes and their metadata.
    /// </summary>
    public async Task<ConfigurationDiscoveryResult> DiscoverConfigurationAsync(CancellationToken cancellationToken = default)
    {
        var stopwatch = System.Diagnostics.Stopwatch.StartNew();

        try
        {
            // Get existing documentation
            var documentation = _documentationService.BuildDocumentation();

            // Discover all IOptions types
            var optionsTypes = await DiscoverOptionsTypesAsync(cancellationToken);

            // Extract metadata for each type
            var metadata = await ExtractMetadataAsync(optionsTypes, cancellationToken);

            // Generate auto-documentation for undocumented types
            var autoGenerated = GenerateAutoDocumentation(optionsTypes, metadata);

            // Validate secret references
            var secretValidation = await ValidateSecretReferencesAsync(cancellationToken);

            // Get configuration audit information
            var auditInfo = GetConfigurationAuditInfo();

            ConfigurationDiscoveryLog.DiscoveryCompleted(_logger, optionsTypes.Count, metadata.Count, stopwatch.ElapsedMilliseconds);

            return new ConfigurationDiscoveryResult
            {
                ExistingDocumentation = documentation,
                DiscoveredTypes = optionsTypes,
                ExtractedMetadata = metadata,
                AutoGeneratedDocumentation = autoGenerated,
                SecretValidation = secretValidation,
                AuditInformation = auditInfo,
                DiscoveryDurationMs = stopwatch.ElapsedMilliseconds,
                Timestamp = DateTimeOffset.UtcNow
            };
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.DiscoveryFailed(_logger, ex.Message, ex);
            throw;
        }
    }

    /// <summary>
    /// Discovers all registered IOptions types in the service provider.
    /// </summary>
    private async Task<List<ConfigurationTypeInfo>> DiscoverOptionsTypesAsync(CancellationToken cancellationToken)
    {
        var types = new List<ConfigurationTypeInfo>();

        // Well-known IOptions types
        var knownTypes = new[]
        {
            typeof(CacheOptions),
            typeof(StandardTtlOptions),
            typeof(LimitsOptions),
            typeof(TileOptions),
            typeof(CloudStorageOptions),
            typeof(TracingOptions),
            typeof(AdaptiveSamplingOptions),
            typeof(PerformanceMonitoringOptions),
            typeof(ApiKeyAuthenticationOptions),
            typeof(OidcAuthenticationOptions),
            typeof(SecretProviderOptions)
        };

        foreach (var type in knownTypes)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var info = await ExtractTypeInfoAsync(type);
            if (info != null)
            {
                types.Add(info);
            }
        }

        // Discover additional types through reflection
        var additionalTypes = await DiscoverAdditionalOptionsTypesAsync(cancellationToken);
        types.AddRange(additionalTypes);

        return types;
    }

    /// <summary>
    /// Discovers additional IOptions types through assembly reflection.
    /// </summary>
    private async Task<List<ConfigurationTypeInfo>> DiscoverAdditionalOptionsTypesAsync(CancellationToken cancellationToken)
    {
        var types = new List<ConfigurationTypeInfo>();

        // Get all assemblies in the current domain that belong to the Honua project
        var assemblies = AppDomain.CurrentDomain.GetAssemblies()
            .Where(a => a.FullName?.StartsWith("Honua.", StringComparison.OrdinalIgnoreCase) == true)
            .ToArray();

        foreach (var assembly in assemblies)
        {
            cancellationToken.ThrowIfCancellationRequested();

            try
            {
                var assemblyTypes = assembly.GetTypes()
                    .Where(t => t.IsClass && !t.IsAbstract && HasSectionNameProperty(t))
                    .ToArray();

                foreach (var type in assemblyTypes)
                {
                    var info = await ExtractTypeInfoAsync(type);
                    if (info != null && !types.Any(t => t.Type == type))
                    {
                        types.Add(info);
                    }
                }
            }
            catch (ReflectionTypeLoadException ex)
            {
                ConfigurationDiscoveryLog.AssemblyLoadWarning(_logger, assembly.FullName ?? "Unknown", ex.Message);
            }
        }

        return types;
    }

    /// <summary>
    /// Checks if a type has a SectionName constant property.
    /// </summary>
    private static bool HasSectionNameProperty(Type type)
    {
        return type.GetField("SectionName", BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy) != null
            || type.GetProperty("SectionName", BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy) != null;
    }

    /// <summary>
    /// Extracts type information for a configuration class.
    /// </summary>
    private async Task<ConfigurationTypeInfo?> ExtractTypeInfoAsync(Type type)
    {
        try
        {
            // Get section name
            var sectionName = GetSectionName(type);
            if (sectionName == null)
            {
                return null;
            }

            // Extract properties
            var properties = ExtractPropertyMetadata(type);

            // Check if registered in DI
            var isRegistered = IsRegisteredInServiceProvider(type);

            // Get current values if available
            var currentValues = await GetCurrentConfigurationValuesAsync(type, sectionName);

            return new ConfigurationTypeInfo
            {
                Type = type,
                SectionName = sectionName,
                TypeName = type.Name,
                FullTypeName = type.FullName ?? type.Name,
                Assembly = type.Assembly.GetName().Name ?? "Unknown",
                Properties = properties,
                IsRegisteredInDi = isRegistered,
                CurrentValues = currentValues
            };
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.TypeExtractionError(_logger, type.FullName ?? type.Name, ex.Message);
            return null;
        }
    }

    /// <summary>
    /// Gets the section name for a configuration type.
    /// </summary>
    private static string? GetSectionName(Type type)
    {
        // Try static field first
        var field = type.GetField("SectionName", BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy);
        if (field?.GetValue(null) is string fieldValue)
        {
            return fieldValue;
        }

        // Try static property
        var property = type.GetProperty("SectionName", BindingFlags.Public | BindingFlags.Static | BindingFlags.FlattenHierarchy);
        if (property?.GetValue(null) is string propertyValue)
        {
            return propertyValue;
        }

        return null;
    }

    /// <summary>
    /// Extracts property metadata from a type.
    /// </summary>
    private static List<PropertyMetadata> ExtractPropertyMetadata(Type type)
    {
        var properties = new List<PropertyMetadata>();

        foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
        {
            if (prop.CanRead && prop.GetIndexParameters().Length == 0)
            {
                var metadata = new PropertyMetadata
                {
                    Name = prop.Name,
                    Type = prop.PropertyType.Name,
                    FullType = prop.PropertyType.FullName ?? prop.PropertyType.Name,
                    IsRequired = IsPropertyRequired(prop),
                    DefaultValue = GetDefaultValue(prop),
                    Description = GetPropertyDescription(prop),
                    ValidationRules = ExtractValidationRules(prop),
                    IsSecret = IsSecretProperty(prop)
                };

                properties.Add(metadata);
            }
        }

        return properties;
    }

    /// <summary>
    /// Determines if a property is required.
    /// </summary>
    private static bool IsPropertyRequired(PropertyInfo property)
    {
        return property.GetCustomAttribute<RequiredAttribute>() != null
            || property.GetCustomAttribute<RequiredConfigurationAttribute>() != null;
    }

    /// <summary>
    /// Gets the default value for a property.
    /// </summary>
    private static object? GetDefaultValue(PropertyInfo property)
    {
        try
        {
            var instance = Activator.CreateInstance(property.DeclaringType!);
            return property.GetValue(instance);
        }
        catch
        {
            return null;
        }
    }

    /// <summary>
    /// Gets the description for a property.
    /// </summary>
    private static string? GetPropertyDescription(PropertyInfo property)
    {
        var descriptionAttr = property.GetCustomAttribute<DescriptionAttribute>();
        if (descriptionAttr?.Description != null)
        {
            return descriptionAttr.Description;
        }

        // Try to extract from XML doc comments if available
        return ExtractXmlDocComment(property);
    }

    /// <summary>
    /// Attempts to extract XML documentation comments.
    /// </summary>
    private static string? ExtractXmlDocComment(PropertyInfo property)
    {
        // This is a simplified implementation
        // In a full implementation, you'd parse the XML documentation file
        return null;
    }

    /// <summary>
    /// Extracts validation rules from property attributes.
    /// </summary>
    private static List<ValidationRuleInfo> ExtractValidationRules(PropertyInfo property)
    {
        var rules = new List<ValidationRuleInfo>();

        foreach (var attr in property.GetCustomAttributes<ValidationAttribute>())
        {
            var rule = new ValidationRuleInfo
            {
                AttributeType = attr.GetType().Name,
                ErrorMessage = attr.ErrorMessage,
                IsConfigurationValidation = attr is ConfigurationValidationAttribute
            };

            // Extract specific validation details
            switch (attr)
            {
                case RangeAttribute range:
                    rule.MinValue = range.Minimum;
                    rule.MaxValue = range.Maximum;
                    break;
                case StringLengthAttribute stringLength:
                    rule.MinLength = stringLength.MinimumLength;
                    rule.MaxLength = stringLength.MaximumLength;
                    break;
                case ValidTtlAttribute ttlAttr:
                    rule.MinimumTtl = ttlAttr.MinimumTtl;
                    rule.MaximumTtl = ttlAttr.MaximumTtl;
                    rule.RecommendedMinimumInProduction = ttlAttr.RecommendedMinimumInProduction;
                    break;
            }

            rules.Add(rule);
        }

        return rules;
    }

    /// <summary>
    /// Determines if a property contains secret data.
    /// </summary>
    private static bool IsSecretProperty(PropertyInfo property)
    {
        var name = property.Name.ToLowerInvariant();
        return name.Contains("password") || name.Contains("secret") || name.Contains("key") || name.Contains("token")
            || property.GetCustomAttribute<SecretReferenceAttribute>() != null;
    }

    /// <summary>
    /// Checks if a type is registered in the service provider.
    /// </summary>
    private bool IsRegisteredInServiceProvider(Type type)
    {
        try
        {
            var optionsType = typeof(IOptions<>).MakeGenericType(type);
            return _serviceProvider.GetService(optionsType) != null;
        }
        catch
        {
            return false;
        }
    }

    /// <summary>
    /// Gets current configuration values for a type.
    /// </summary>
    private async Task<Dictionary<string, object?>> GetCurrentConfigurationValuesAsync(Type type, string sectionName)
    {
        var values = new Dictionary<string, object?>();

        try
        {
            // Try to get from IOptions if registered
            var optionsType = typeof(IOptions<>).MakeGenericType(type);
            var options = _serviceProvider.GetService(optionsType);

            if (options != null)
            {
                var valueProperty = optionsType.GetProperty("Value");
                var instance = valueProperty?.GetValue(options);

                if (instance != null)
                {
                    foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
                    {
                        if (prop.CanRead && prop.GetIndexParameters().Length == 0)
                        {
                            try
                            {
                                var value = prop.GetValue(instance);
                                values[prop.Name] = IsSecretProperty(prop) ? "***" : value;
                            }
                            catch
                            {
                                values[prop.Name] = null;
                            }
                        }
                    }
                }
            }
            else
            {
                // Fallback to reading from IConfiguration
                var section = _configuration.GetSection(sectionName);
                foreach (var prop in type.GetProperties(BindingFlags.Public | BindingFlags.Instance))
                {
                    if (prop.CanRead && prop.GetIndexParameters().Length == 0)
                    {
                        var configValue = section[prop.Name];
                        values[prop.Name] = IsSecretProperty(prop) && configValue != null ? "***" : configValue;
                    }
                }
            }
        }
        catch (Exception ex)
        {
            ConfigurationDiscoveryLog.ValueExtractionError(_logger, type.FullName ?? type.Name, ex.Message);
        }

        return values;
    }

    /// <summary>
    /// Extracts metadata for all discovered types.
    /// </summary>
    private async Task<List<ConfigurationMetadata>> ExtractMetadataAsync(List<ConfigurationTypeInfo> types, CancellationToken cancellationToken)
    {
        var metadata = new List<ConfigurationMetadata>();

        foreach (var typeInfo in types)
        {
            cancellationToken.ThrowIfCancellationRequested();

            var meta = new ConfigurationMetadata
            {
                SectionName = typeInfo.SectionName,
                TypeName = typeInfo.TypeName,
                PropertyCount = typeInfo.Properties.Count,
                SecretPropertyCount = typeInfo.Properties.Count(p => p.IsSecret),
                RequiredPropertyCount = typeInfo.Properties.Count(p => p.IsRequired),
                HasValidation = typeInfo.Properties.Any(p => p.ValidationRules.Count > 0),
                IsRegistered = typeInfo.IsRegisteredInDi,
                LastModified = GetLastModifiedTime(typeInfo.Type)
            };

            metadata.Add(meta);
        }

        return metadata;
    }

    /// <summary>
    /// Gets the last modified time for a type's assembly.
    /// </summary>
    private static DateTimeOffset GetLastModifiedTime(Type type)
    {
        try
        {
            var assembly = type.Assembly;
            var location = assembly.Location;

            if (!string.IsNullOrEmpty(location) && File.Exists(location))
            {
                return File.GetLastWriteTimeUtc(location);
            }

            return DateTimeOffset.UtcNow;
        }
        catch
        {
            return DateTimeOffset.UtcNow;
        }
    }

    /// <summary>
    /// Generates automatic documentation for undocumented configuration types.
    /// </summary>
    private List<AutoGeneratedDocumentationSection> GenerateAutoDocumentation(List<ConfigurationTypeInfo> types, List<ConfigurationMetadata> metadata)
    {
        var sections = new List<AutoGeneratedDocumentationSection>();

        foreach (var typeInfo in types)
        {
            var section = new AutoGeneratedDocumentationSection
            {
                SectionName = typeInfo.SectionName,
                TypeName = typeInfo.TypeName,
                Description = $"Auto-generated documentation for {typeInfo.TypeName}",
                Properties = typeInfo.Properties.Select(p => new AutoGeneratedPropertyDoc
                {
                    Name = p.Name,
                    Type = p.Type,
                    Description = p.Description ?? GeneratePropertyDescription(p),
                    DefaultValue = p.DefaultValue,
                    IsRequired = p.IsRequired,
                    IsSecret = p.IsSecret,
                    EnvironmentVariable = GetEnvironmentVariableName(typeInfo.SectionName, p.Name),
                    ValidationSummary = GetValidationSummary(p.ValidationRules)
                }).ToList()
            };

            sections.Add(section);
        }

        return sections;
    }

    /// <summary>
    /// Generates a description for a property based on its name and type.
    /// </summary>
    private static string GeneratePropertyDescription(PropertyMetadata property)
    {
        var name = property.Name;

        // Generate description based on common patterns
        if (name.EndsWith("Enabled"))
            return $"Enables or disables {name.Replace("Enabled", "").ToLowerInvariant()}";

        if (name.EndsWith("Timeout"))
            return $"Timeout duration for {name.Replace("Timeout", "").ToLowerInvariant()} operations";

        if (name.EndsWith("MaxSize") || name.EndsWith("MaxLength"))
            return $"Maximum size limit for {name.Replace("Max", "").Replace("Size", "").Replace("Length", "").ToLowerInvariant()}";

        if (name.Contains("Ttl"))
            return $"Time-to-live duration for {name.Replace("Ttl", "").ToLowerInvariant()}";

        return $"Configuration setting for {name}";
    }

    /// <summary>
    /// Gets the environment variable name for a configuration property.
    /// </summary>
    private static string GetEnvironmentVariableName(string sectionName, string propertyName)
    {
        return $"{sectionName}__{propertyName}".Replace(":", "__");
    }

    /// <summary>
    /// Gets a summary of validation rules for a property.
    /// </summary>
    private static string GetValidationSummary(List<ValidationRuleInfo> rules)
    {
        if (rules.Count == 0)
            return "No validation rules";

        var summaries = new List<string>();

        foreach (var rule in rules)
        {
            switch (rule.AttributeType)
            {
                case "RequiredAttribute":
                    summaries.Add("Required");
                    break;
                case "RangeAttribute" when rule.MinValue != null && rule.MaxValue != null:
                    summaries.Add($"Range: {rule.MinValue} - {rule.MaxValue}");
                    break;
                case "StringLengthAttribute" when rule.MaxLength.HasValue:
                    summaries.Add($"Max length: {rule.MaxLength}");
                    break;
                case "ValidTtlAttribute":
                    summaries.Add($"TTL: {rule.MinimumTtl} - {rule.MaximumTtl}");
                    break;
            }
        }

        return summaries.Count > 0 ? string.Join(", ", summaries) : "Custom validation";
    }

    /// <summary>
    /// Validates all secret references in the configuration.
    /// </summary>
    private async Task<SecretValidationResult> ValidateSecretReferencesAsync(CancellationToken cancellationToken)
    {
        var result = new SecretValidationResult
        {
            TotalSecrets = 0,
            ValidSecrets = 0,
            InvalidSecrets = 0,
            Issues = new List<SecretValidationIssue>()
        };

        try
        {
            var secretProvider = _serviceProvider.GetService<ISecretProvider>();
            if (secretProvider == null)
            {
                result.Issues.Add(new SecretValidationIssue
                {
                    SecretReference = "N/A",
                    Issue = "ISecretProvider not registered",
                    Severity = "Error"
                });
                return result;
            }

            // Scan configuration for potential secret references
            var secretReferences = ScanForSecretReferences();
            result.TotalSecrets = secretReferences.Count;

            foreach (var secretRef in secretReferences)
            {
                cancellationToken.ThrowIfCancellationRequested();

                try
                {
                    var canResolve = await secretProvider.CanResolveSecretAsync(secretRef, cancellationToken);
                    if (canResolve)
                    {
                        result.ValidSecrets++;
                    }
                    else
                    {
                        result.InvalidSecrets++;
                        result.Issues.Add(new SecretValidationIssue
                        {
                            SecretReference = secretRef,
                            Issue = "Secret reference cannot be resolved",
                            Severity = "Warning"
                        });
                    }
                }
                catch (Exception ex)
                {
                    result.InvalidSecrets++;
                    result.Issues.Add(new SecretValidationIssue
                    {
                        SecretReference = secretRef,
                        Issue = ex.Message,
                        Severity = "Error"
                    });
                }
            }
        }
        catch (Exception ex)
        {
            result.Issues.Add(new SecretValidationIssue
            {
                SecretReference = "N/A",
                Issue = $"Secret validation failed: {ex.Message}",
                Severity = "Error"
            });
        }

        return result;
    }

    /// <summary>
    /// Scans configuration for potential secret references.
    /// </summary>
    private List<string> ScanForSecretReferences()
    {
        var secretRefs = new List<string>();

        // Scan all configuration sections
        foreach (var section in _configuration.AsEnumerable())
        {
            var value = section.Value;
            if (!string.IsNullOrEmpty(value) && IsLikelySecretReference(value))
            {
                secretRefs.Add(value);
            }
        }

        return secretRefs.Distinct().ToList();
    }

    /// <summary>
    /// Determines if a value looks like a secret reference.
    /// </summary>
    private static bool IsLikelySecretReference(string value)
    {
        if (string.IsNullOrWhiteSpace(value))
            return false;

        var colonIndex = value.IndexOf(':', StringComparison.Ordinal);
        if (colonIndex <= 0)
            return false;

        var provider = value[..colonIndex];
        var knownProviders = new[] { "env", "azure", "aws", "vault", "config" };

        return knownProviders.Contains(provider, StringComparer.OrdinalIgnoreCase);
    }

    /// <summary>
    /// Gets configuration audit information.
    /// </summary>
    private ConfigurationAuditInfo GetConfigurationAuditInfo()
    {
        return new ConfigurationAuditInfo
        {
            Environment = _environment.EnvironmentName,
            MachineName = Environment.MachineName,
            ApplicationName = _environment.ApplicationName,
            ContentRoot = _environment.ContentRootPath,
            ConfigurationSources = _configuration.AsEnumerable()
                .Where(kvp => kvp.Value != null)
                .GroupBy(kvp => GetConfigurationSourceType(kvp.Key))
                .ToDictionary(g => g.Key, g => g.Count()),
            TotalConfigurationKeys = _configuration.AsEnumerable().Count(kvp => kvp.Value != null)
        };
    }

    /// <summary>
    /// Determines the source type for a configuration key.
    /// </summary>
    private static string GetConfigurationSourceType(string key)
    {
        if (key.Contains("__"))
            return "Environment Variables";

        if (key.Contains(":"))
            return "Configuration File";

        return "Other";
    }
}

// Additional model classes for the discovery service...

/// <summary>
/// Result of configuration discovery operation.
/// </summary>
public sealed class ConfigurationDiscoveryResult
{
    /// <summary>
    /// Existing configuration documentation.
    /// </summary>
    public ConfigurationDocumentation ExistingDocumentation { get; set; } = null!;

    /// <summary>
    /// Discovered configuration types.
    /// </summary>
    public List<ConfigurationTypeInfo> DiscoveredTypes { get; set; } = new();

    /// <summary>
    /// Extracted metadata for all types.
    /// </summary>
    public List<ConfigurationMetadata> ExtractedMetadata { get; set; } = new();

    /// <summary>
    /// Auto-generated documentation.
    /// </summary>
    public List<AutoGeneratedDocumentationSection> AutoGeneratedDocumentation { get; set; } = new();

    /// <summary>
    /// Secret reference validation results.
    /// </summary>
    public SecretValidationResult SecretValidation { get; set; } = new();

    /// <summary>
    /// Configuration audit information.
    /// </summary>
    public ConfigurationAuditInfo AuditInformation { get; set; } = new();

    /// <summary>
    /// Duration of the discovery operation in milliseconds.
    /// </summary>
    public long DiscoveryDurationMs { get; set; }

    /// <summary>
    /// Timestamp when discovery was performed.
    /// </summary>
    public DateTimeOffset Timestamp { get; set; }
}

/// <summary>
/// Information about a discovered configuration type.
/// </summary>
public sealed class ConfigurationTypeInfo
{
    /// <summary>
    /// The .NET type.
    /// </summary>
    [JsonIgnore]
    public Type Type { get; set; } = null!;

    /// <summary>
    /// Configuration section name.
    /// </summary>
    public string SectionName { get; set; } = string.Empty;

    /// <summary>
    /// Simple type name.
    /// </summary>
    public string TypeName { get; set; } = string.Empty;

    /// <summary>
    /// Full type name including namespace.
    /// </summary>
    public string FullTypeName { get; set; } = string.Empty;

    /// <summary>
    /// Assembly name where the type is defined.
    /// </summary>
    public string Assembly { get; set; } = string.Empty;

    /// <summary>
    /// Properties of the configuration type.
    /// </summary>
    public List<PropertyMetadata> Properties { get; set; } = new();

    /// <summary>
    /// Whether the type is registered in dependency injection.
    /// </summary>
    public bool IsRegisteredInDi { get; set; }

    /// <summary>
    /// Current configuration values.
    /// </summary>
    public Dictionary<string, object?> CurrentValues { get; set; } = new();
}

/// <summary>
/// Metadata about a configuration property.
/// </summary>
public sealed class PropertyMetadata
{
    /// <summary>
    /// Property name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Property type name.
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Full property type name.
    /// </summary>
    public string FullType { get; set; } = string.Empty;

    /// <summary>
    /// Whether the property is required.
    /// </summary>
    public bool IsRequired { get; set; }

    /// <summary>
    /// Default value of the property.
    /// </summary>
    public object? DefaultValue { get; set; }

    /// <summary>
    /// Property description.
    /// </summary>
    public string? Description { get; set; }

    /// <summary>
    /// Validation rules applied to the property.
    /// </summary>
    public List<ValidationRuleInfo> ValidationRules { get; set; } = new();

    /// <summary>
    /// Whether the property contains secret data.
    /// </summary>
    public bool IsSecret { get; set; }
}

/// <summary>
/// Information about a validation rule.
/// </summary>
public sealed class ValidationRuleInfo
{
    /// <summary>
    /// Type of validation attribute.
    /// </summary>
    public string AttributeType { get; set; } = string.Empty;

    /// <summary>
    /// Error message for the validation rule.
    /// </summary>
    public string? ErrorMessage { get; set; }

    /// <summary>
    /// Whether it's a configuration-specific validation attribute.
    /// </summary>
    public bool IsConfigurationValidation { get; set; }

    /// <summary>
    /// Minimum value for range validation.
    /// </summary>
    public object? MinValue { get; set; }

    /// <summary>
    /// Maximum value for range validation.
    /// </summary>
    public object? MaxValue { get; set; }

    /// <summary>
    /// Minimum length for string validation.
    /// </summary>
    public int? MinLength { get; set; }

    /// <summary>
    /// Maximum length for string validation.
    /// </summary>
    public int? MaxLength { get; set; }

    /// <summary>
    /// Minimum TTL for TTL validation.
    /// </summary>
    public string? MinimumTtl { get; set; }

    /// <summary>
    /// Maximum TTL for TTL validation.
    /// </summary>
    public string? MaximumTtl { get; set; }

    /// <summary>
    /// Recommended minimum TTL for production.
    /// </summary>
    public string? RecommendedMinimumInProduction { get; set; }
}

/// <summary>
/// Configuration metadata summary.
/// </summary>
public sealed class ConfigurationMetadata
{
    /// <summary>
    /// Configuration section name.
    /// </summary>
    public string SectionName { get; set; } = string.Empty;

    /// <summary>
    /// Type name.
    /// </summary>
    public string TypeName { get; set; } = string.Empty;

    /// <summary>
    /// Number of properties.
    /// </summary>
    public int PropertyCount { get; set; }

    /// <summary>
    /// Number of secret properties.
    /// </summary>
    public int SecretPropertyCount { get; set; }

    /// <summary>
    /// Number of required properties.
    /// </summary>
    public int RequiredPropertyCount { get; set; }

    /// <summary>
    /// Whether the type has validation rules.
    /// </summary>
    public bool HasValidation { get; set; }

    /// <summary>
    /// Whether the type is registered in DI.
    /// </summary>
    public bool IsRegistered { get; set; }

    /// <summary>
    /// Last modified time of the type.
    /// </summary>
    public DateTimeOffset LastModified { get; set; }
}

/// <summary>
/// Auto-generated documentation section.
/// </summary>
public sealed class AutoGeneratedDocumentationSection
{
    /// <summary>
    /// Configuration section name.
    /// </summary>
    public string SectionName { get; set; } = string.Empty;

    /// <summary>
    /// Type name.
    /// </summary>
    public string TypeName { get; set; } = string.Empty;

    /// <summary>
    /// Section description.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Properties in the section.
    /// </summary>
    public List<AutoGeneratedPropertyDoc> Properties { get; set; } = new();
}

/// <summary>
/// Auto-generated property documentation.
/// </summary>
public sealed class AutoGeneratedPropertyDoc
{
    /// <summary>
    /// Property name.
    /// </summary>
    public string Name { get; set; } = string.Empty;

    /// <summary>
    /// Property type.
    /// </summary>
    public string Type { get; set; } = string.Empty;

    /// <summary>
    /// Property description.
    /// </summary>
    public string Description { get; set; } = string.Empty;

    /// <summary>
    /// Default value.
    /// </summary>
    public object? DefaultValue { get; set; }

    /// <summary>
    /// Whether the property is required.
    /// </summary>
    public bool IsRequired { get; set; }

    /// <summary>
    /// Whether the property is secret.
    /// </summary>
    public bool IsSecret { get; set; }

    /// <summary>
    /// Environment variable name.
    /// </summary>
    public string EnvironmentVariable { get; set; } = string.Empty;

    /// <summary>
    /// Validation summary.
    /// </summary>
    public string ValidationSummary { get; set; } = string.Empty;
}

/// <summary>
/// Secret validation results.
/// </summary>
public sealed class SecretValidationResult
{
    /// <summary>
    /// Total number of secrets found.
    /// </summary>
    public int TotalSecrets { get; set; }

    /// <summary>
    /// Number of valid secrets.
    /// </summary>
    public int ValidSecrets { get; set; }

    /// <summary>
    /// Number of invalid secrets.
    /// </summary>
    public int InvalidSecrets { get; set; }

    /// <summary>
    /// Validation issues found.
    /// </summary>
    public List<SecretValidationIssue> Issues { get; set; } = new();
}

/// <summary>
/// A secret validation issue.
/// </summary>
public sealed class SecretValidationIssue
{
    /// <summary>
    /// Secret reference that has an issue.
    /// </summary>
    public string SecretReference { get; set; } = string.Empty;

    /// <summary>
    /// Description of the issue.
    /// </summary>
    public string Issue { get; set; } = string.Empty;

    /// <summary>
    /// Severity of the issue.
    /// </summary>
    public string Severity { get; set; } = string.Empty;
}

/// <summary>
/// Configuration audit information.
/// </summary>
public sealed class ConfigurationAuditInfo
{
    /// <summary>
    /// Current environment name.
    /// </summary>
    public string Environment { get; set; } = string.Empty;

    /// <summary>
    /// Machine name where the application is running.
    /// </summary>
    public string MachineName { get; set; } = string.Empty;

    /// <summary>
    /// Application name.
    /// </summary>
    public string ApplicationName { get; set; } = string.Empty;

    /// <summary>
    /// Content root path.
    /// </summary>
    public string ContentRoot { get; set; } = string.Empty;

    /// <summary>
    /// Configuration sources and their key counts.
    /// </summary>
    public Dictionary<string, int> ConfigurationSources { get; set; } = new();

    /// <summary>
    /// Total number of configuration keys.
    /// </summary>
    public int TotalConfigurationKeys { get; set; }
}

/// <summary>
/// Logging extensions for configuration discovery.
/// </summary>
internal static partial class ConfigurationDiscoveryLog
{
    [LoggerMessage(
        EventId = 20001,
        Level = LogLevel.Information,
        Message = "Configuration discovery completed: {TypeCount} types, {MetadataCount} metadata entries, {DurationMs}ms")]
    public static partial void DiscoveryCompleted(ILogger logger, int typeCount, int metadataCount, long durationMs);

    [LoggerMessage(
        EventId = 20002,
        Level = LogLevel.Error,
        Message = "Configuration discovery failed: {Error}")]
    public static partial void DiscoveryFailed(ILogger logger, string error, Exception exception);

    [LoggerMessage(
        EventId = 20003,
        Level = LogLevel.Warning,
        Message = "Assembly load warning for {AssemblyName}: {Error}")]
    public static partial void AssemblyLoadWarning(ILogger logger, string assemblyName, string error);

    [LoggerMessage(
        EventId = 20004,
        Level = LogLevel.Warning,
        Message = "Type extraction error for {TypeName}: {Error}")]
    public static partial void TypeExtractionError(ILogger logger, string typeName, string error);

    [LoggerMessage(
        EventId = 20005,
        Level = LogLevel.Warning,
        Message = "Value extraction error for {TypeName}: {Error}")]
    public static partial void ValueExtractionError(ILogger logger, string typeName, string error);
}