// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Collections.Immutable;
using System.Text.Json;
using System.Text.Json.Serialization;
using Honua.Infrastructure.Models;

namespace Honua.Protocols.GeoServices.FeatureServer.Models;

/// <summary>
/// JSON serialization context for FeatureServer API models with source generation for AOT compatibility.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(FeatureServerResponse))]
[JsonSerializable(typeof(LayerResponse))]
[JsonSerializable(typeof(LayerRelationshipInfo))]
[JsonSerializable(typeof(LayerRelationshipInfo[]))]
[JsonSerializable(typeof(LayerInfo))]
[JsonSerializable(typeof(FeatureServerTimeInfo))]
[JsonSerializable(typeof(FeatureServerExtrusionInfo))]
[JsonSerializable(typeof(SpatialReferenceInfo))]
[JsonSerializable(typeof(GeoServicesSpatialReference))]
[JsonSerializable(typeof(ExtentInfo))]
[JsonSerializable(typeof(GeoServicesFieldInfo))]
[JsonSerializable(typeof(GeoServicesFieldInfo[]), TypeInfoPropertyName = "GeoServicesFieldInfoArray")]
[JsonSerializable(typeof(GeoServicesFieldDomainInfo))]
[JsonSerializable(typeof(GeoServicesFieldDomainCodedValueInfo))]
[JsonSerializable(typeof(GeoServicesFieldDomainCodedValueInfo[]))]
[JsonSerializable(typeof(QueryResponse))]
[JsonSerializable(typeof(ServiceQueryResponse))]
[JsonSerializable(typeof(ServiceQueryLayerResponse))]
[JsonSerializable(typeof(ServiceQueryLayerResponse[]))]
[JsonSerializable(typeof(GeoServicesFeature))]
[JsonSerializable(typeof(GeoServicesFeature[]), TypeInfoPropertyName = "GeoServicesFeatureArray")]
[JsonSerializable(typeof(GeoServicesGeometry))]
[JsonSerializable(typeof(QueryParameters))]
[JsonSerializable(typeof(GeoJsonFeatureSet))]
[JsonSerializable(typeof(GeoJsonFeature), TypeInfoPropertyName = "FeatureServerGeoJsonFeature")]
[JsonSerializable(typeof(GeoJsonFeature[]), TypeInfoPropertyName = "FeatureServerGeoJsonFeatureArray")]
[JsonSerializable(typeof(GeoJsonGeometry))]
[JsonSerializable(typeof(ApplyEditsRequest))]
[JsonSerializable(typeof(ApplyEditsResponse))]
[JsonSerializable(typeof(EditResult))]
[JsonSerializable(typeof(EditError))]
[JsonSerializable(typeof(QueryRelatedRecordsParameters))]
[JsonSerializable(typeof(QueryRelatedRecordsResponse))]
[JsonSerializable(typeof(RelatedRecordGroup))]
[JsonSerializable(typeof(RelatedRecords))]
[JsonSerializable(typeof(double[]))]
[JsonSerializable(typeof(double[][]))]
[JsonSerializable(typeof(double[][][]))]
[JsonSerializable(typeof(int[]))]
[JsonSerializable(typeof(ApiErrorResponse))]
[JsonSerializable(typeof(GeoServicesError))]
[JsonSerializable(typeof(Dictionary<string, object>))]
[JsonSerializable(typeof(Dictionary<string, object>[]))]
[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(Dictionary<string, object?>[]))]
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(AttachmentInfo))]
[JsonSerializable(typeof(AttachmentInfosResponse))]
[JsonSerializable(typeof(AttachmentGroup))]
[JsonSerializable(typeof(AttachmentQueryResponse))]
[JsonSerializable(typeof(AddAttachmentResult))]
[JsonSerializable(typeof(AddAttachmentResponse))]
[JsonSerializable(typeof(UpdateAttachmentResult))]
[JsonSerializable(typeof(UpdateAttachmentResponse))]
[JsonSerializable(typeof(DeleteAttachmentResult))]
[JsonSerializable(typeof(DeleteAttachmentsResponse))]
[JsonSerializable(typeof(UniqueIdFieldInfo))]
[JsonSerializable(typeof(EditFieldsInfo))]
[JsonSerializable(typeof(EditingInfo))]
[JsonSerializable(typeof(FeatureTemplate))]
[JsonSerializable(typeof(FeatureTemplate[]))]
[JsonSerializable(typeof(ServiceLayerEdits))]
[JsonSerializable(typeof(ServiceLayerEdits[]))]
[JsonSerializable(typeof(ServiceApplyEditsResponse))]
[JsonSerializable(typeof(ServiceLayerEditResult))]
[JsonSerializable(typeof(ServiceLayerEditResult[]))]
[JsonSerializable(typeof(IReadOnlyList<object>))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(object[]))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(DateTimeOffset))]
// ASP.NET Core types
[JsonSerializable(typeof(Microsoft.AspNetCore.Mvc.ProblemDetails))]
[JsonSerializable(typeof(ImmutableArray<string>))]
[JsonSerializable(typeof(ImmutableArray<ImmutableArray<double>>))]
[JsonSerializable(typeof(ImmutableArray<ImmutableArray<string?>>))]
[JsonSerializable(typeof(ImmutableArray<string>?))]
// Replication models
[JsonSerializable(typeof(CreateReplicaRequest))]
[JsonSerializable(typeof(CreateReplicaResponse))]
[JsonSerializable(typeof(ReplicaSummary))]
[JsonSerializable(typeof(ReplicaSummary[]), TypeInfoPropertyName = "ReplicaSummaryArray")]
[JsonSerializable(typeof(ReplicaInfoResponse))]
[JsonSerializable(typeof(ReplicaInfoLayer))]
[JsonSerializable(typeof(ReplicaInfoLayer[]))]
[JsonSerializable(typeof(ReplicaInfoLayerServerGeneration))]
[JsonSerializable(typeof(ReplicaInfoLayerServerGeneration[]), TypeInfoPropertyName = "ReplicaInfoLayerServerGenerationArray")]
[JsonSerializable(typeof(ReplicaLayerInfo))]
[JsonSerializable(typeof(ReplicaLayerInfo[]))]
[JsonSerializable(typeof(ExtractChangesRequest))]
[JsonSerializable(typeof(ExtractChangesResponse))]
[JsonSerializable(typeof(LayerChanges))]
[JsonSerializable(typeof(LayerChanges[]))]
[JsonSerializable(typeof(long[]), TypeInfoPropertyName = "Int64Array")]
[JsonSerializable(typeof(ReplicaState))]
[JsonSerializable(typeof(DistributedReplicaStore.ReplicaStateEnvelope))]
[JsonSerializable(typeof(SynchronizeReplicaRequest))]
[JsonSerializable(typeof(SynchronizeReplicaResponse))]
[JsonSerializable(typeof(UnRegisterReplicaRequest))]
[JsonSerializable(typeof(SuccessResponse))]
// Maintenance models
[JsonSerializable(typeof(AppendRequest))]
[JsonSerializable(typeof(AppendResponse))]
[JsonSerializable(typeof(CalculateRequest))]
[JsonSerializable(typeof(CalculateResponse))]
[JsonSerializable(typeof(QueryDomainsResponse))]
[JsonSerializable(typeof(QueryRelationshipsResponse))]
[JsonSerializable(typeof(ServiceRelationshipInfo))]
[JsonSerializable(typeof(ServiceRelationshipInfo[]))]
[JsonSerializable(typeof(DomainInfo))]
[JsonSerializable(typeof(DomainInfo[]))]
[JsonSerializable(typeof(DomainCodedValueInfo))]
[JsonSerializable(typeof(DomainCodedValueInfo[]))]
[JsonSerializable(typeof(ValidateSqlRequest))]
[JsonSerializable(typeof(ValidateSqlResponse))]
// Not-implemented operation surfaces (spec-shaped honest responses)
[JsonSerializable(typeof(QueryContingentValuesResponse))]
[JsonSerializable(typeof(SharedTemplatesResponse))]
[JsonSerializable(typeof(HtmlPopupResponse))]
[JsonSerializable(typeof(HasAssetsResponse))]
[JsonSerializable(typeof(QueryAssetsResponse))]
[JsonSerializable(typeof(CleanupAssetsResponse))]
[JsonSerializable(typeof(UpdateMetadataResponse))]
// Advanced query models
[JsonSerializable(typeof(GetEstimatesResponse))]
[JsonSerializable(typeof(ServiceGetEstimatesResponse))]
[JsonSerializable(typeof(ServiceLayerEstimateInfo))]
[JsonSerializable(typeof(ServiceLayerEstimateInfo[]))]
// Temporal extent endpoint (#379)
[JsonSerializable(typeof(TemporalExtentResponse))]
[JsonSerializable(typeof(SpatialAggregationResultResponse))]
[JsonSerializable(typeof(SpatialAggregationIndexStateResponse))]
[JsonSerializable(typeof(SpatialAggregationIndexModelResponse))]
[JsonSerializable(typeof(SpatialAggregationMetadataResponse))]
[JsonSerializable(typeof(SpatialAggregationSummaryMetadataResponse))]
[JsonSerializable(typeof(SpatialAggregationSummaryMetadataResponse[]))]
[JsonSerializable(typeof(SpatialAggregationRangeBucketMetadataResponse))]
[JsonSerializable(typeof(SpatialAggregationRangeBucketMetadataResponse[]))]
[JsonSerializable(typeof(SpatialAggregationHistogramMetadataResponse))]
[JsonSerializable(typeof(SpatialAggregationGroupByMetadataResponse))]
[JsonSerializable(typeof(SpatialAggregationGroupByMetadataResponse[]))]
[JsonSerializable(typeof(SpatialAggregationWidgetMetadataResponse))]
[JsonSerializable(typeof(SpatialAggregationWidgetMetadataResponse[]))]
[JsonSerializable(typeof(SpatialAggregationWidgetProgressiveResponse))]
[JsonSerializable(typeof(SpatialAggregationProgressiveStateResponse))]
[JsonSerializable(typeof(SpatialAggregationCacheMetadataResponse))]
[JsonSerializable(typeof(SpatialAggregationCellResponse))]
[JsonSerializable(typeof(SpatialAggregationCellResponse[]))]
[JsonSerializable(typeof(SpatialAggregationGroupedSummaryResponse))]
[JsonSerializable(typeof(SpatialAggregationGroupedSummaryResponse[]))]
[JsonSerializable(typeof(SpatialAggregationSummaryValueResponse))]
[JsonSerializable(typeof(Dictionary<string, SpatialAggregationSummaryValueResponse>))]
[JsonSerializable(typeof(SpatialAggregationBucketValueResponse))]
[JsonSerializable(typeof(SpatialAggregationBucketValueResponse[]))]
[JsonSerializable(typeof(SpatialAggregationPageInfoResponse))]
[JsonSerializable(typeof(SpatialAggregationDegradedReasonResponse))]
[JsonSerializable(typeof(SpatialAggregationDegradedReasonResponse[]))]
internal sealed partial class FeatureServerJsonContext : JsonSerializerContext;
