#!/usr/bin/env bash
# Called on a trunk checkout after scripts/ci/regenerate-generated-files.sh has
# refreshed the working tree. This script NEVER writes trunk directly: it
# commits any drift on a fixed automation branch and opens (or refreshes) a
# PR from that branch into trunk, so the regenerated bytes land through the
# same PR Gate + Review Gate + per-PR lander path as every other change.
#
# That is a deliberate change from the first attempt at this workflow (#4540),
# which pushed straight to `refs/heads/trunk` with a ruleset-bypass
# credential. scripts/ci/validate-single-merge-authority.sh exists to prove
# trunk has exactly one writer, and it rejected that push (#4653): a second
# script with authority to move trunk without review is exactly the
# multi-writer condition the guard is written to catch, and weakening the
# guard to admit it would defeat its purpose. Landing through an ordinary PR
# keeps the guard's proof intact for free — there is no second trunk writer to
# reason about, only a bot-authored PR subject to the same gates as any other.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/../.."
source scripts/ci/generated-files.sh

branch='automation/regenerate-generated-files'
title='ci: regenerate generated files'

if git diff --quiet HEAD -- "${GENERATED_FILES[@]}"; then
  echo 'Generated files are up to date; nothing to publish.'
  exit 0
fi
# Validation stays bound to the triggering source even on an old rerun.
# Capture the branch lease BEFORE observing trunk: a newer publisher racing
# that observation must never have its automation head overwritten.
remote_branch="$(git ls-remote origin "refs/heads/${branch}")"
remote_branch="${remote_branch%%[[:space:]]*}"
source_sha="$(git rev-parse HEAD)"
remote_trunk="$(git ls-remote --exit-code origin refs/heads/trunk)"
remote_trunk="${remote_trunk%%[[:space:]]*}"
if [[ "$source_sha" != "$remote_trunk" ]]; then
  echo "Validated source $source_sha; trunk is now $remote_trunk. No stale projections published."
  exit 0
fi
: "${GH_TOKEN:?MERGE_TRAIN_TOKEN is required to publish a PR and trigger its admission checks}"
git diff --stat HEAD -- "${GENERATED_FILES[@]}"

git add -- "${GENERATED_FILES[@]}"
git -c user.name='Mike McDougall' \
    -c user.email='mike@honua.io' \
    commit -m "${title}" \
    -m "Generated-From: ${source_sha}" \
    -m 'Refs #3213 (perpetual generated-file sync; never closes the epic)'

# One automation-owned branch: a failed `gh pr create` never leaves a new
# orphan branch behind, and pushing again simply updates whatever PR is
# already open on it. force-with-lease is confined to this bot-owned branch
# and can never target trunk.
#
# The destination below is a literal, not `HEAD:refs/heads/${branch}`:
# scripts/ci/validate-single-merge-authority.sh cannot statically prove a
# variable push destination is not trunk, so (correctly) it rejects any
# `git push` whose ref is a shell variable everywhere outside its own
# allowlist -- that is exactly how a disguised trunk push would read. Keep
# this literal in sync with `branch` above by hand.
# Use the lease captured before the freshness observation. This is a CAS of
# the automation branch, not a lock on trunk. A later trunk push schedules its
# own refresh through the same reviewed maintenance path as #4695.
# Credentials are resolved only for this push and never stored by checkout.
git -c credential.helper= -c 'credential.helper=!gh auth git-credential' \
  push --force-with-lease="refs/heads/automation/regenerate-generated-files:${remote_branch}" \
  origin HEAD:refs/heads/automation/regenerate-generated-files

existing="$(gh pr list --state open --head "${branch}" --base trunk --json number --jq '.[0].number // empty')"
if [[ -n "${existing}" ]]; then
  echo "Updated existing generated-files PR #${existing}."
  exit 0
fi
gh pr create --base trunk --head "${branch}" \
  --title "${title}" \
  --body 'Automated regeneration of the tracked projections listed in scripts/ci/generated-files.sh (see docs/internal/ci/generated-files-on-trunk.md). Lands through the normal PR Gate + Review Gate + per-PR lander path; this workflow never writes trunk directly. Refs #3213.'
