// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

namespace Honua.Server.Features.Infrastructure.Security;

/// <summary>
/// Result of security analysis for an audit event.
/// </summary>
public class SecurityAnalysisResult
{
    public string EventId { get; set; } = string.Empty;
    public DateTime AnalysisTimestamp { get; set; }
    public List<ThreatDetection> Threats { get; set; } = new();
    public List<AnomalyDetection> Anomalies { get; set; } = new();
    public List<ComplianceViolation> ComplianceViolations { get; set; } = new();
    public List<string> AnalysisErrors { get; set; } = new();
    public int RiskScore { get; set; }
    public string? RecommendedAction { get; set; }
}

/// <summary>
/// Security threat detection result.
/// </summary>
public class ThreatDetection
{
    public ThreatType ThreatType { get; set; }
    public ThreatSeverity Severity { get; set; }
    public string Description { get; set; } = string.Empty;
    public string? Evidence { get; set; }
    public double Confidence { get; set; }
    public DateTime DetectedAt { get; set; } = DateTime.UtcNow;
    public Dictionary<string, object> Metadata { get; set; } = new();
}

/// <summary>
/// Types of security threats that can be detected.
/// </summary>
public enum ThreatType
{
    SqlInjection,
    XssAttempt,
    BruteForceAttack,
    PrivilegeEscalation,
    DataExfiltration,
    MaliciousIp,
    CommandInjection,
    SessionHijacking,
    UnauthorizedAccess,
    SuspiciousFileAccess,
    AccountEnumeration,
    DenialOfService
}

/// <summary>
/// Severity levels for security threats.
/// </summary>
public enum ThreatSeverity
{
    Critical,
    High,
    Medium,
    Low,
    Info
}

/// <summary>
/// Behavioral anomaly detection result.
/// </summary>
public class AnomalyDetection
{
    public AnomalyType AnomalyType { get; set; }
    public AnomalySeverity Severity { get; set; }
    public string Description { get; set; } = string.Empty;
    public double DeviationScore { get; set; }
    public double Confidence { get; set; }
    public DateTime DetectedAt { get; set; } = DateTime.UtcNow;
    public Dictionary<string, object> BaselineData { get; set; } = new();
    public Dictionary<string, object> CurrentData { get; set; } = new();
}

/// <summary>
/// Types of behavioral anomalies.
/// </summary>
public enum AnomalyType
{
    UnusualTimeAccess,
    UnusualLocation,
    UnusualActivityVolume,
    UnusualActionPattern,
    UnusualResourceAccess,
    UnusualDataVolume,
    UnusualSessionDuration,
    UnusualAuthenticationPattern
}

/// <summary>
/// Severity levels for anomalies.
/// </summary>
public enum AnomalySeverity
{
    High,
    Medium,
    Low
}

/// <summary>
/// Security alert generated by monitoring system.
/// </summary>
public class SecurityAlert
{
    public string AlertId { get; set; } = string.Empty;
    public string? EventId { get; set; }
    public string? CorrelationId { get; set; }
    public AlertType AlertType { get; set; }
    public AlertSeverity Severity { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public string? SourceIp { get; set; }
    public string? UserId { get; set; }
    public string? Resource { get; set; }
    public DateTime Timestamp { get; set; }
    public int RiskScore { get; set; }
    public List<ThreatDetection> Threats { get; set; } = new();
    public List<AnomalyDetection> Anomalies { get; set; } = new();
    public List<string> RecommendedActions { get; set; } = new();
    public AlertStatus Status { get; set; }
    public string? AssignedTo { get; set; }
    public DateTime? ResolvedAt { get; set; }
    public string? Resolution { get; set; }
    public Dictionary<string, object> Metadata { get; set; } = new();
}

/// <summary>
/// Types of security alerts.
/// </summary>
public enum AlertType
{
    SecurityIncident,
    ComplianceViolation,
    BehavioralAnomaly,
    ThreatDetection,
    BruteForceAttack,
    SqlInjectionAttempt,
    PrivilegeEscalation,
    SuspiciousDataAccess,
    UnauthorizedAccess,
    DataIntegrityViolation,
    ConfigurationChange,
    SystemCompromise
}

/// <summary>
/// Severity levels for alerts.
/// </summary>
public enum AlertSeverity
{
    Critical,
    High,
    Medium,
    Low,
    Info
}

/// <summary>
/// Status of security alerts.
/// </summary>
public enum AlertStatus
{
    Open,
    InProgress,
    Resolved,
    False_Positive,
    Suppressed
}

/// <summary>
/// User behavioral profile for anomaly detection.
/// </summary>
public class UserBehaviorProfile
{
    public string UserId { get; set; } = string.Empty;
    public DateTime FirstSeen { get; set; }
    public DateTime LastSeen { get; set; }
    public List<UserActivity> ActionHistory { get; set; } = new();
    public Dictionary<string, int> ResourceAccessCounts { get; set; } = new();
    public Dictionary<int, int> HourlyActivityCounts { get; set; } = new();
    public Dictionary<DayOfWeek, int> DailyActivityCounts { get; set; } = new();
    public HashSet<string> IpAddresses { get; set; } = new();
    public HashSet<string> UserAgents { get; set; } = new();
    public double AverageSessionDuration { get; set; }
    public int TotalActions { get; set; }

    public void UpdateActivity(AuditEvent auditEvent)
    {
        LastSeen = auditEvent.Timestamp;
        TotalActions++;

        ActionHistory.Add(new UserActivity
        {
            Timestamp = auditEvent.Timestamp,
            EventType = auditEvent.EventType,
            Resource = auditEvent.Resource,
            Action = auditEvent.Action,
            IpAddress = auditEvent.ClientIp,
            UserAgent = auditEvent.UserAgent
        });

        // Maintain sliding window of recent activities
        var cutoff = DateTime.UtcNow.AddDays(-30);
        ActionHistory.RemoveAll(a => a.Timestamp < cutoff);

        // Update resource access counts
        if (!string.IsNullOrEmpty(auditEvent.Resource))
        {
            ResourceAccessCounts[auditEvent.Resource] = ResourceAccessCounts.GetValueOrDefault(auditEvent.Resource, 0) + 1;
        }

        // Update hourly activity
        var hour = auditEvent.Timestamp.Hour;
        HourlyActivityCounts[hour] = HourlyActivityCounts.GetValueOrDefault(hour, 0) + 1;

        // Update daily activity
        var dayOfWeek = auditEvent.Timestamp.DayOfWeek;
        DailyActivityCounts[dayOfWeek] = DailyActivityCounts.GetValueOrDefault(dayOfWeek, 0) + 1;

        // Track IP addresses
        if (!string.IsNullOrEmpty(auditEvent.ClientIp))
        {
            IpAddresses.Add(auditEvent.ClientIp);
        }

        // Track user agents
        if (!string.IsNullOrEmpty(auditEvent.UserAgent))
        {
            UserAgents.Add(auditEvent.UserAgent);
        }
    }

    public HashSet<int> GetTypicalActivityHours()
    {
        var totalActivity = HourlyActivityCounts.Values.Sum();
        var threshold = totalActivity * 0.1; // Hours with at least 10% of activity

        return HourlyActivityCounts
            .Where(kvp => kvp.Value >= threshold)
            .Select(kvp => kvp.Key)
            .ToHashSet();
    }

    public HashSet<string> GetRecentIpAddresses(int days = 7)
    {
        var cutoff = DateTime.UtcNow.AddDays(-days);
        return ActionHistory
            .Where(a => a.Timestamp > cutoff && !string.IsNullOrEmpty(a.IpAddress))
            .Select(a => a.IpAddress!)
            .ToHashSet();
    }

    public int GetRecentActivityCount(TimeSpan timeWindow)
    {
        var cutoff = DateTime.UtcNow.Subtract(timeWindow);
        return ActionHistory.Count(a => a.Timestamp > cutoff);
    }

    public double GetAverageActivityCount()
    {
        if (ActionHistory.Count == 0)
            return 0;

        var days = (DateTime.UtcNow - FirstSeen).TotalDays;
        return days > 0 ? ActionHistory.Count / days : 0;
    }

    public List<UserActivity> GetRecentActions(int count)
    {
        return ActionHistory
            .OrderByDescending(a => a.Timestamp)
            .Take(count)
            .ToList();
    }

    public void CleanupOldData(DateTime cutoff)
    {
        ActionHistory.RemoveAll(a => a.Timestamp < cutoff);

        // Clean up counts for very old data
        if (FirstSeen < cutoff.AddMonths(-6))
        {
            HourlyActivityCounts.Clear();
            DailyActivityCounts.Clear();
            ResourceAccessCounts.Clear();
            IpAddresses.Clear();
            UserAgents.Clear();
        }
    }
}

/// <summary>
/// Individual user activity record.
/// </summary>
public class UserActivity
{
    public DateTime Timestamp { get; set; }
    public AuditEventType EventType { get; set; }
    public string Resource { get; set; } = string.Empty;
    public string Action { get; set; } = string.Empty;
    public string? IpAddress { get; set; }
    public string? UserAgent { get; set; }
}

/// <summary>
/// IP address behavioral profile for threat detection.
/// </summary>
public class IpBehaviorProfile
{
    public string IpAddress { get; set; } = string.Empty;
    public DateTime FirstSeen { get; set; }
    public DateTime LastSeen { get; set; }
    public List<IpActivity> ActivityHistory { get; set; } = new();
    public Dictionary<AuditEventType, int> EventTypeCounts { get; set; } = new();
    public Dictionary<string, int> UserCounts { get; set; } = new();
    public Dictionary<string, int> ResourceCounts { get; set; } = new();
    public int FailedAuthenticationCount { get; set; }
    public int SuccessfulAuthenticationCount { get; set; }
    public bool IsSuspicious { get; set; }
    public List<string> SuspiciousFlags { get; set; } = new();

    public void UpdateActivity(AuditEvent auditEvent)
    {
        LastSeen = auditEvent.Timestamp;

        ActivityHistory.Add(new IpActivity
        {
            Timestamp = auditEvent.Timestamp,
            EventType = auditEvent.EventType,
            UserId = auditEvent.UserId,
            Resource = auditEvent.Resource,
            Action = auditEvent.Action,
            UserAgent = auditEvent.UserAgent
        });

        // Maintain sliding window
        var cutoff = DateTime.UtcNow.AddDays(-7);
        ActivityHistory.RemoveAll(a => a.Timestamp < cutoff);

        // Update counts
        EventTypeCounts[auditEvent.EventType] = EventTypeCounts.GetValueOrDefault(auditEvent.EventType, 0) + 1;

        if (!string.IsNullOrEmpty(auditEvent.UserId))
        {
            UserCounts[auditEvent.UserId] = UserCounts.GetValueOrDefault(auditEvent.UserId, 0) + 1;
        }

        if (!string.IsNullOrEmpty(auditEvent.Resource))
        {
            ResourceCounts[auditEvent.Resource] = ResourceCounts.GetValueOrDefault(auditEvent.Resource, 0) + 1;
        }

        // Track authentication attempts
        if (auditEvent.EventType == AuditEventType.AuthenticationFailure)
        {
            FailedAuthenticationCount++;
        }
        else if (auditEvent.EventType == AuditEventType.AuthenticationSuccess)
        {
            SuccessfulAuthenticationCount++;
        }

        // Update suspicious flags
        UpdateSuspiciousFlags();
    }

    private void UpdateSuspiciousFlags()
    {
        SuspiciousFlags.Clear();

        // High failure rate
        var totalAuth = FailedAuthenticationCount + SuccessfulAuthenticationCount;
        if (totalAuth > 10 && (double)FailedAuthenticationCount / totalAuth > 0.8)
        {
            SuspiciousFlags.Add("HIGH_FAILURE_RATE");
        }

        // Multiple users from same IP
        if (UserCounts.Count > 5)
        {
            SuspiciousFlags.Add("MULTIPLE_USERS");
        }

        // High activity volume
        var recentActivity = ActivityHistory.Count(a => a.Timestamp > DateTime.UtcNow.AddHours(-1));
        if (recentActivity > 100)
        {
            SuspiciousFlags.Add("HIGH_ACTIVITY_VOLUME");
        }

        // Diverse resource access
        if (ResourceCounts.Count > 20)
        {
            SuspiciousFlags.Add("DIVERSE_RESOURCE_ACCESS");
        }

        IsSuspicious = SuspiciousFlags.Count > 0;
    }

    public void CleanupOldData(DateTime cutoff)
    {
        ActivityHistory.RemoveAll(a => a.Timestamp < cutoff);

        if (FirstSeen < cutoff.AddMonths(-3))
        {
            EventTypeCounts.Clear();
            UserCounts.Clear();
            ResourceCounts.Clear();
            FailedAuthenticationCount = 0;
            SuccessfulAuthenticationCount = 0;
            SuspiciousFlags.Clear();
            IsSuspicious = false;
        }
    }
}

/// <summary>
/// Individual IP activity record.
/// </summary>
public class IpActivity
{
    public DateTime Timestamp { get; set; }
    public AuditEventType EventType { get; set; }
    public string? UserId { get; set; }
    public string Resource { get; set; } = string.Empty;
    public string Action { get; set; } = string.Empty;
    public string? UserAgent { get; set; }
}

/// <summary>
/// Configuration options for security monitoring.
/// </summary>
public class SecurityMonitoringOptions
{
    public TimeSpan MonitoringInterval { get; set; } = TimeSpan.FromMinutes(1);
    public TimeSpan DataRetentionPeriod { get; set; } = TimeSpan.FromDays(90);
    public int AlertThreshold { get; set; } = 70;
    public int BruteForceThreshold { get; set; } = 5;
    public TimeSpan BruteForceTimeWindow { get; set; } = TimeSpan.FromMinutes(15);
    public int LargeDataAccessThreshold { get; set; } = 1000;
    public long LargeResultSizeThreshold { get; set; } = 10 * 1024 * 1024; // 10MB
    public TimeSpan VolumeAnomalyTimeWindow { get; set; } = TimeSpan.FromHours(1);
    public double VolumeAnomalyMultiplier { get; set; } = 3.0;
    public int MaxAlertsPerCycle { get; set; } = 100;
    public bool EnableRealTimeAlerts { get; set; } = true;
    public bool EnableAutomatedResponse { get; set; }
    public int BusinessHoursStart { get; set; } = 8;
    public int BusinessHoursEnd { get; set; } = 18;
    public DayOfWeek[] BusinessDays { get; set; } =
    {
        DayOfWeek.Monday, DayOfWeek.Tuesday, DayOfWeek.Wednesday,
        DayOfWeek.Thursday, DayOfWeek.Friday
    };
    public HashSet<string> KnownMaliciousIps { get; set; } = new();
    public HashSet<string> TrustedIpRanges { get; set; } = new();
    public Dictionary<string, object> ThreatIntelligenceConfig { get; set; } = new();
}
