import { describe, expect, it } from "vitest";

import { HonuaClient, HonuaHttpError } from "../src/honua.js";
import {
  AttributionCompat,
  BasemapCompat,
  BasemapToggleCompat,
  BasemapGalleryCompat,
  BasemapLayerListCompat,
  BookmarksCompat,
  CompassCompat,
  CompatEventBus,
  CoordinateConversionCompat,
  createArcGisTokenInterceptor,
  createEsriRequestInterceptors,
  DirectionsCompat,
  EsriRequestInterceptorRegistry,
  EditorCompat,
  FeatureCompat,
  FeatureFormCompat,
  FeatureTemplatesCompat,
  ExpandCompat,
  FeatureLayerCompat,
  FeatureTableCompat,
  FeatureTableHighlightIdsCompat,
  GraphicCompat,
  GraphicsLayerCompat,
  GroupLayerCompat,
  HomeCompat,
  IdentifyCompat,
  LayerListCompat,
  LegendCompat,
  LocateCompat,
  FullscreenCompat,
  AreaMeasurement2DCompat,
  DistanceMeasurement2DCompat,
  MeasurementCompat,
  MapCompat,
  MapImageLayerCompat,
  MapViewCompat,
  MapViewUiCompat,
  PrintCompat,
  PopupCompat,
  PopupTemplateCompat,
  QueryCompat,
  RouteLayerCompat,
  RouteTaskCompat,
  reactiveUtils,
  SearchCompat,
  SketchCompat,
  ScaleBarCompat,
  SwipeCompat,
  TableListCompat,
  TrackCompat,
  TimeSliderCompat,
  TileLayerCompat,
  ZoomCompat,
  watch,
  when,
  whenOnce,
  parseMapServiceUrl,
  SceneViewCompat,
  WebMapCompat,
} from "../src/esri-compat-entry.js";
import {
  buildJsMigrationReport,
  evaluateMigrationGates,
  getJsParityMatrix,
  runLayerReconciliation,
  runEsriCompatCodemod,
  scanArcGisUsage,
  summarizeJsParityMatrix,
} from "../src/migration-entry.js";

describe("entrypoint modules", () => {
  it("exposes honua-first core entrypoint", () => {
    expect(HonuaClient).toBeTypeOf("function");
    expect(HonuaHttpError).toBeTypeOf("function");
  });

  it("exposes esri-compat entrypoint", () => {
    expect(FeatureLayerCompat).toBeTypeOf("function");
    expect(HomeCompat).toBeTypeOf("function");
    expect(BasemapCompat).toBeTypeOf("function");
    expect(BasemapToggleCompat).toBeTypeOf("function");
    expect(BasemapGalleryCompat).toBeTypeOf("function");
    expect(BasemapLayerListCompat).toBeTypeOf("function");
    expect(BookmarksCompat).toBeTypeOf("function");
    expect(CompassCompat).toBeTypeOf("function");
    expect(ExpandCompat).toBeTypeOf("function");
    expect(AttributionCompat).toBeTypeOf("function");
    expect(FullscreenCompat).toBeTypeOf("function");
    expect(ZoomCompat).toBeTypeOf("function");
    expect(GraphicCompat).toBeTypeOf("function");
    expect(LocateCompat).toBeTypeOf("function");
    expect(ScaleBarCompat).toBeTypeOf("function");
    expect(CoordinateConversionCompat).toBeTypeOf("function");
    expect(CompatEventBus).toBeTypeOf("function");
    expect(createEsriRequestInterceptors).toBeTypeOf("function");
    expect(createArcGisTokenInterceptor).toBeTypeOf("function");
    expect(EsriRequestInterceptorRegistry).toBeTypeOf("function");
    expect(DirectionsCompat).toBeTypeOf("function");
    expect(EditorCompat).toBeTypeOf("function");
    expect(FeatureCompat).toBeTypeOf("function");
    expect(FeatureFormCompat).toBeTypeOf("function");
    expect(FeatureTemplatesCompat).toBeTypeOf("function");
    expect(GraphicsLayerCompat).toBeTypeOf("function");
    expect(FeatureTableCompat).toBeTypeOf("function");
    expect(FeatureTableHighlightIdsCompat).toBeTypeOf("function");
    expect(GroupLayerCompat).toBeTypeOf("function");
    expect(IdentifyCompat).toBeTypeOf("function");
    expect(LayerListCompat).toBeTypeOf("function");
    expect(LegendCompat).toBeTypeOf("function");
    expect(MapCompat).toBeTypeOf("function");
    expect(MapImageLayerCompat).toBeTypeOf("function");
    expect(MapViewCompat).toBeTypeOf("function");
    expect(MapViewUiCompat).toBeTypeOf("function");
    expect(PrintCompat).toBeTypeOf("function");
    expect(MeasurementCompat).toBeTypeOf("function");
    expect(AreaMeasurement2DCompat).toBeTypeOf("function");
    expect(DistanceMeasurement2DCompat).toBeTypeOf("function");
    expect(PopupCompat).toBeTypeOf("function");
    expect(PopupTemplateCompat).toBeTypeOf("function");
    expect(QueryCompat).toBeTypeOf("function");
    expect(RouteLayerCompat).toBeTypeOf("function");
    expect(RouteTaskCompat).toBeTypeOf("function");
    expect(reactiveUtils.watch).toBeTypeOf("function");
    expect(SwipeCompat).toBeTypeOf("function");
    expect(TableListCompat).toBeTypeOf("function");
    expect(SketchCompat).toBeTypeOf("function");
    expect(TrackCompat).toBeTypeOf("function");
    expect(TimeSliderCompat).toBeTypeOf("function");
    expect(TileLayerCompat).toBeTypeOf("function");
    expect(parseMapServiceUrl).toBeTypeOf("function");
    expect(SceneViewCompat).toBeTypeOf("function");
    expect(SearchCompat).toBeTypeOf("function");
    expect(WebMapCompat).toBeTypeOf("function");
    expect(watch).toBeTypeOf("function");
    expect(when).toBeTypeOf("function");
    expect(whenOnce).toBeTypeOf("function");
  });

  it("exposes migration tooling entrypoint", () => {
    expect(scanArcGisUsage).toBeTypeOf("function");
    expect(runEsriCompatCodemod).toBeTypeOf("function");
    expect(buildJsMigrationReport).toBeTypeOf("function");
    expect(evaluateMigrationGates).toBeTypeOf("function");
    expect(getJsParityMatrix).toBeTypeOf("function");
    expect(runLayerReconciliation).toBeTypeOf("function");
    expect(summarizeJsParityMatrix).toBeTypeOf("function");
  });
});
