import { describe, expect, it } from "vitest";

import {
  createHonuaService,
  HonuaClient,
  HonuaFeatureLayer,
  HonuaHttpError,
  HonuaMapService,
  HonuaService,
} from "../src/honua.js";
import {
  AttributionCompat,
  BasemapCompat,
  BasemapToggleCompat,
  BasemapGalleryCompat,
  BasemapLayerListCompat,
  BookmarksCompat,
  CompassCompat,
  CompatEventBus,
  CoordinateConversionCompat,
  ColorCompat,
  createArcGisTokenInterceptor,
  createEsriRequestInterceptors,
  DirectionsCompat,
  esriConfig,
  esriRequest,
  EsriRequestInterceptorRegistry,
  EditorCompat,
  FeatureCompat,
  FeatureFormCompat,
  FeatureSetCompat,
  FeatureTemplatesCompat,
  ExpandCompat,
  FeatureLayerCompat,
  FeatureTableCompat,
  FeatureTableHighlightIdsCompat,
  GraphicCompat,
  getEsriConfigHonuaInterceptors,
  GraphicsLayerCompat,
  GroupLayerCompat,
  HomeCompat,
  IdentifyCompat,
  identityManager,
  LayerListCompat,
  LegendCompat,
  LocateCompat,
  FullscreenCompat,
  AreaMeasurement2DCompat,
  DistanceMeasurement2DCompat,
  MeasurementCompat,
  MapCompat,
  MapImageLayerCompat,
  MapViewCompat,
  MapViewUiCompat,
  PrintCompat,
  PopupCompat,
  PopupTemplateCompat,
  OAuthInfoCompat,
  PointCompat,
  PolylineCompat,
  PolygonCompat,
  ExtentCompat,
  SpatialReferenceCompat,
  QueryCompat,
  RouteLayerCompat,
  RouteTaskCompat,
  reactiveUtils,
  resetEsriConfig,
  SearchCompat,
  SketchCompat,
  SimpleLineSymbolCompat,
  SimpleFillSymbolCompat,
  SimpleMarkerSymbolCompat,
  PictureMarkerSymbolCompat,
  TextSymbolCompat,
  LabelClassCompat,
  ClassBreaksRendererCompat,
  SimpleRendererCompat,
  ScaleBarCompat,
  SwipeCompat,
  TableListCompat,
  TrackCompat,
  TimeSliderCompat,
  TileLayerCompat,
  UniqueValueRendererCompat,
  ZoomCompat,
  watch,
  when,
  whenOnce,
  parseMapServiceUrl,
  SceneViewCompat,
  WebMapCompat,
} from "../src/esri-compat-entry.js";
import {
  buildJsMigrationReport,
  evaluateMigrationGates,
  getJsParityMatrix,
  runLayerReconciliation,
  runEsriCompatCodemod,
  scanArcGisUsage,
  summarizeJsParityMatrix,
} from "../src/migration-entry.js";

describe("entrypoint modules", () => {
  it("exposes honua-first core entrypoint", () => {
    expect(HonuaClient).toBeTypeOf("function");
    expect(HonuaHttpError).toBeTypeOf("function");
    expect(HonuaService).toBeTypeOf("function");
    expect(HonuaFeatureLayer).toBeTypeOf("function");
    expect(HonuaMapService).toBeTypeOf("function");
    expect(createHonuaService).toBeTypeOf("function");
  });

  it("exposes esri-compat entrypoint", () => {
    expect(FeatureLayerCompat).toBeTypeOf("function");
    expect(HomeCompat).toBeTypeOf("function");
    expect(BasemapCompat).toBeTypeOf("function");
    expect(BasemapToggleCompat).toBeTypeOf("function");
    expect(BasemapGalleryCompat).toBeTypeOf("function");
    expect(BasemapLayerListCompat).toBeTypeOf("function");
    expect(BookmarksCompat).toBeTypeOf("function");
    expect(CompassCompat).toBeTypeOf("function");
    expect(ExpandCompat).toBeTypeOf("function");
    expect(AttributionCompat).toBeTypeOf("function");
    expect(FullscreenCompat).toBeTypeOf("function");
    expect(ZoomCompat).toBeTypeOf("function");
    expect(GraphicCompat).toBeTypeOf("function");
    expect(PointCompat).toBeTypeOf("function");
    expect(PolylineCompat).toBeTypeOf("function");
    expect(PolygonCompat).toBeTypeOf("function");
    expect(ExtentCompat).toBeTypeOf("function");
    expect(SpatialReferenceCompat).toBeTypeOf("function");
    expect(ColorCompat).toBeTypeOf("function");
    expect(LocateCompat).toBeTypeOf("function");
    expect(ScaleBarCompat).toBeTypeOf("function");
    expect(CoordinateConversionCompat).toBeTypeOf("function");
    expect(CompatEventBus).toBeTypeOf("function");
    expect(createEsriRequestInterceptors).toBeTypeOf("function");
    expect(createArcGisTokenInterceptor).toBeTypeOf("function");
    expect(EsriRequestInterceptorRegistry).toBeTypeOf("function");
    expect(esriConfig).toBeTypeOf("object");
    expect(esriRequest).toBeTypeOf("function");
    expect(getEsriConfigHonuaInterceptors).toBeTypeOf("function");
    expect(resetEsriConfig).toBeTypeOf("function");
    expect(identityManager).toBeTypeOf("object");
    expect(DirectionsCompat).toBeTypeOf("function");
    expect(EditorCompat).toBeTypeOf("function");
    expect(FeatureCompat).toBeTypeOf("function");
    expect(FeatureFormCompat).toBeTypeOf("function");
    expect(FeatureSetCompat).toBeTypeOf("function");
    expect(FeatureTemplatesCompat).toBeTypeOf("function");
    expect(GraphicsLayerCompat).toBeTypeOf("function");
    expect(FeatureTableCompat).toBeTypeOf("function");
    expect(FeatureTableHighlightIdsCompat).toBeTypeOf("function");
    expect(GroupLayerCompat).toBeTypeOf("function");
    expect(IdentifyCompat).toBeTypeOf("function");
    expect(LayerListCompat).toBeTypeOf("function");
    expect(LegendCompat).toBeTypeOf("function");
    expect(MapCompat).toBeTypeOf("function");
    expect(MapImageLayerCompat).toBeTypeOf("function");
    expect(MapViewCompat).toBeTypeOf("function");
    expect(MapViewUiCompat).toBeTypeOf("function");
    expect(PrintCompat).toBeTypeOf("function");
    expect(MeasurementCompat).toBeTypeOf("function");
    expect(AreaMeasurement2DCompat).toBeTypeOf("function");
    expect(DistanceMeasurement2DCompat).toBeTypeOf("function");
    expect(PopupCompat).toBeTypeOf("function");
    expect(PopupTemplateCompat).toBeTypeOf("function");
    expect(OAuthInfoCompat).toBeTypeOf("function");
    expect(QueryCompat).toBeTypeOf("function");
    expect(RouteLayerCompat).toBeTypeOf("function");
    expect(RouteTaskCompat).toBeTypeOf("function");
    expect(reactiveUtils.watch).toBeTypeOf("function");
    expect(SwipeCompat).toBeTypeOf("function");
    expect(TableListCompat).toBeTypeOf("function");
    expect(SketchCompat).toBeTypeOf("function");
    expect(TrackCompat).toBeTypeOf("function");
    expect(TimeSliderCompat).toBeTypeOf("function");
    expect(TileLayerCompat).toBeTypeOf("function");
    expect(parseMapServiceUrl).toBeTypeOf("function");
    expect(SceneViewCompat).toBeTypeOf("function");
    expect(SearchCompat).toBeTypeOf("function");
    expect(SimpleLineSymbolCompat).toBeTypeOf("function");
    expect(SimpleFillSymbolCompat).toBeTypeOf("function");
    expect(SimpleMarkerSymbolCompat).toBeTypeOf("function");
    expect(PictureMarkerSymbolCompat).toBeTypeOf("function");
    expect(TextSymbolCompat).toBeTypeOf("function");
    expect(LabelClassCompat).toBeTypeOf("function");
    expect(ClassBreaksRendererCompat).toBeTypeOf("function");
    expect(SimpleRendererCompat).toBeTypeOf("function");
    expect(UniqueValueRendererCompat).toBeTypeOf("function");
    expect(WebMapCompat).toBeTypeOf("function");
    expect(watch).toBeTypeOf("function");
    expect(when).toBeTypeOf("function");
    expect(whenOnce).toBeTypeOf("function");
  });

  it("exposes migration tooling entrypoint", () => {
    expect(scanArcGisUsage).toBeTypeOf("function");
    expect(runEsriCompatCodemod).toBeTypeOf("function");
    expect(buildJsMigrationReport).toBeTypeOf("function");
    expect(evaluateMigrationGates).toBeTypeOf("function");
    expect(getJsParityMatrix).toBeTypeOf("function");
    expect(runLayerReconciliation).toBeTypeOf("function");
    expect(summarizeJsParityMatrix).toBeTypeOf("function");
  });
});
