apiVersion: v2
name: honua
description: Honua Server Helm chart
type: application
version: 0.1.0
appVersion: "0.0.0"
dependencies:
  - name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: ">=12.0.0 <16.0.0"
    condition: postgresql.enabled
  - name: redis
    repository: https://charts.bitnami.com/bitnami
    version: ">=18.0.0 <21.0.0"
    condition: redis.enabled
