// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Text.Json;
using System.Text.Json.Serialization;

namespace Honua.Core.Features.Forms.Packages;

/// <summary>
/// Stable lifecycle states for server-owned form packages.
/// </summary>
public static class FormPackageStatus
{
    /// <summary>Editable package draft.</summary>
    public const string Draft = "draft";

    /// <summary>Immutable package version available for runtime submission.</summary>
    public const string Published = "published";

    /// <summary>Retained package version that should not be selected as current.</summary>
    public const string Archived = "archived";
}

/// <summary>
/// Feature edit operations that a published form package may permit.
/// </summary>
public static class FormSubmissionOperations
{
    /// <summary>Create a new feature.</summary>
    public const string Create = "create";

    /// <summary>Update an existing feature.</summary>
    public const string Update = "update";

    /// <summary>Delete an existing feature.</summary>
    public const string Delete = "delete";
}

/// <summary>
/// Survey-style form package document governed by Honua Server.
/// </summary>
public sealed class FormPackageDocument
{
    /// <summary>Wire schema version for this package document.</summary>
    [JsonPropertyName("schemaVersion")]
    public string SchemaVersion { get; init; } = "honua.form-package.v1";

    /// <summary>Stable package identifier. Generated by the server when omitted on create.</summary>
    [JsonPropertyName("formId")]
    public string? FormId { get; init; }

    /// <summary>Human-readable title shown in builder and field clients.</summary>
    [JsonPropertyName("title")]
    public string? Title { get; init; }

    /// <summary>Optional package description.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>Target feature service and layer for submissions.</summary>
    [JsonPropertyName("target")]
    public FormTargetDefinition? Target { get; init; }

    /// <summary>Ordered sections or groups in the form.</summary>
    [JsonPropertyName("sections")]
    public FormSectionDefinition[] Sections { get; init; } = [];

    /// <summary>Field definitions, including target-field bindings.</summary>
    [JsonPropertyName("fields")]
    public FormFieldDefinition[] Fields { get; init; } = [];

    /// <summary>Runtime edit policy for accepted submissions.</summary>
    [JsonPropertyName("submitPolicy")]
    public FormSubmitPolicy SubmitPolicy { get; init; } = new();

    /// <summary>Package-level and per-field attachment policy.</summary>
    [JsonPropertyName("attachmentPolicy")]
    public FormAttachmentPolicy AttachmentPolicy { get; init; } = new();

    /// <summary>Privacy policy applied while validating, storing, and auditing submissions.</summary>
    [JsonPropertyName("privacyPolicy")]
    public FormPrivacyPolicy PrivacyPolicy { get; init; } = new();

    /// <summary>Offline and sync policy advertised to field clients.</summary>
    [JsonPropertyName("offlinePolicy")]
    public FormOfflinePolicy OfflinePolicy { get; init; } = new();

    /// <summary>Optional provenance describing how the package was authored.</summary>
    [JsonPropertyName("provenance")]
    public FormProvenanceRef? Provenance { get; init; }

    /// <summary>Opaque package metadata. Values must be policy-safe and non-secret.</summary>
    [JsonPropertyName("metadata")]
    public Dictionary<string, string>? Metadata { get; init; }
}

/// <summary>
/// Feature service and layer binding for a form package.
/// </summary>
public sealed class FormTargetDefinition
{
    /// <summary>Target feature service identifier.</summary>
    [JsonPropertyName("serviceId")]
    public string? ServiceId { get; init; }

    /// <summary>Target feature layer identifier.</summary>
    [JsonPropertyName("layerId")]
    public int LayerId { get; init; }
}

/// <summary>
/// Section or group used to organize form fields.
/// </summary>
public sealed class FormSectionDefinition
{
    /// <summary>Stable section identifier.</summary>
    [JsonPropertyName("sectionId")]
    public string? SectionId { get; init; }

    /// <summary>Localized or fallback section label.</summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }

    /// <summary>Optional section description.</summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>Field ids included in this section.</summary>
    [JsonPropertyName("fieldIds")]
    public string[] FieldIds { get; init; } = [];
}

/// <summary>
/// Single field or attachment control definition in a package.
/// </summary>
public sealed class FormFieldDefinition
{
    /// <summary>Stable field identifier used by clients and submissions.</summary>
    [JsonPropertyName("fieldId")]
    public string? FieldId { get; init; }

    /// <summary>Human-readable field label.</summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }

    /// <summary>Optional help text.</summary>
    [JsonPropertyName("hint")]
    public string? Hint { get; init; }

    /// <summary>Form field type such as text, number, date, choice, geometry, or attachment.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>Target layer attribute field. Attachment fields do not require a target field.</summary>
    [JsonPropertyName("targetField")]
    public string? TargetField { get; init; }

    /// <summary>Optional section id containing this field.</summary>
    [JsonPropertyName("sectionId")]
    public string? SectionId { get; init; }

    /// <summary>Whether a submission must provide a value for this field.</summary>
    [JsonPropertyName("required")]
    public bool Required { get; init; }

    /// <summary>Whether clients should render the control read-only.</summary>
    [JsonPropertyName("readOnly")]
    public bool ReadOnly { get; init; }

    /// <summary>Whether the field carries sensitive values that should be minimized in records.</summary>
    [JsonPropertyName("private")]
    public bool Private { get; init; }

    /// <summary>Optional default value encoded as JSON.</summary>
    [JsonPropertyName("defaultValue")]
    public JsonElement? DefaultValue { get; init; }

    /// <summary>Domain or coded-value choice policy for this field.</summary>
    [JsonPropertyName("domain")]
    public FormFieldDomainDefinition? Domain { get; init; }

    /// <summary>Declarative validation rules applied by the server.</summary>
    [JsonPropertyName("validation")]
    public FormValidationRule[] Validation { get; init; } = [];

    /// <summary>Conditional visibility policy for this field.</summary>
    [JsonPropertyName("visibility")]
    public FormConditionalRule? Visibility { get; init; }
}

/// <summary>
/// Form-level domain definition for a field.
/// </summary>
public sealed class FormFieldDomainDefinition
{
    /// <summary>Domain type, usually codedValue or range.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>Allowed coded-value choices.</summary>
    [JsonPropertyName("choices")]
    public FormDomainChoice[] Choices { get; init; } = [];

    /// <summary>Inclusive minimum for range domains.</summary>
    [JsonPropertyName("min")]
    public JsonElement? Min { get; init; }

    /// <summary>Inclusive maximum for range domains.</summary>
    [JsonPropertyName("max")]
    public JsonElement? Max { get; init; }
}

/// <summary>
/// Coded-value choice exposed by a form field domain.
/// </summary>
public sealed class FormDomainChoice
{
    /// <summary>Stored domain code.</summary>
    [JsonPropertyName("code")]
    public JsonElement Code { get; init; }

    /// <summary>Display label for the code.</summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }
}

/// <summary>
/// Server-validated rule applied to a submitted form value.
/// </summary>
public sealed class FormValidationRule
{
    /// <summary>Stable rule identifier.</summary>
    [JsonPropertyName("ruleId")]
    public string? RuleId { get; init; }

    /// <summary>Rule type such as minLength, maxLength, min, max, or regex.</summary>
    [JsonPropertyName("type")]
    public string? Type { get; init; }

    /// <summary>Client-facing validation message.</summary>
    [JsonPropertyName("message")]
    public string? Message { get; init; }

    /// <summary>Rule parameters encoded as JSON.</summary>
    [JsonPropertyName("parameters")]
    public JsonElement? Parameters { get; init; }
}

/// <summary>
/// Conditional rule used for form visibility decisions.
/// </summary>
public sealed class FormConditionalRule
{
    /// <summary>Field id that controls this rule.</summary>
    [JsonPropertyName("dependsOnFieldId")]
    public string? DependsOnFieldId { get; init; }

    /// <summary>Operator such as equals, notEquals, in, isEmpty, or isNotEmpty.</summary>
    [JsonPropertyName("operator")]
    public string? Operator { get; init; }

    /// <summary>Comparison value encoded as JSON.</summary>
    [JsonPropertyName("value")]
    public JsonElement? Value { get; init; }
}

/// <summary>
/// Submission policy for a package.
/// </summary>
public sealed class FormSubmitPolicy
{
    /// <summary>Allowed edit operations. Defaults to create-only.</summary>
    [JsonPropertyName("allowedOperations")]
    public string[] AllowedOperations { get; init; } = [FormSubmissionOperations.Create];

    /// <summary>Whether create/update submissions must include geometry when the target layer has geometry.</summary>
    [JsonPropertyName("requiresGeometry")]
    public bool RequiresGeometry { get; init; } = true;

    /// <summary>Whether published submissions may include attachments.</summary>
    [JsonPropertyName("allowAttachments")]
    public bool AllowAttachments { get; init; } = true;

    /// <summary>Maximum accepted offline age in seconds.</summary>
    [JsonPropertyName("maxOfflineAgeSeconds")]
    public int? MaxOfflineAgeSeconds { get; init; }
}

/// <summary>
/// Package attachment policy.
/// </summary>
public sealed class FormAttachmentPolicy
{
    /// <summary>Whether submissions may include attachments.</summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

    /// <summary>Maximum attachments accepted in one submission.</summary>
    [JsonPropertyName("maxAttachmentsPerSubmission")]
    public int? MaxAttachmentsPerSubmission { get; init; }

    /// <summary>Maximum bytes for one attachment.</summary>
    [JsonPropertyName("maxAttachmentBytes")]
    public long? MaxAttachmentBytes { get; init; }

    /// <summary>Maximum total attachment bytes per submission.</summary>
    [JsonPropertyName("maxTotalBytes")]
    public long? MaxTotalBytes { get; init; }

    /// <summary>Allowed MIME types. Wildcards such as image/* are supported.</summary>
    [JsonPropertyName("allowedContentTypes")]
    public string[] AllowedContentTypes { get; init; } = [];

    /// <summary>Per-field attachment policy overrides.</summary>
    [JsonPropertyName("fields")]
    public FormFieldAttachmentPolicy[] Fields { get; init; } = [];

    /// <summary>Whether EXIF stripping is required before persistence.</summary>
    [JsonPropertyName("requireExifStripping")]
    public bool RequireExifStripping { get; init; }

    /// <summary>Whether face blur is required before persistence.</summary>
    [JsonPropertyName("requireFaceBlur")]
    public bool RequireFaceBlur { get; init; }

    /// <summary>Whether arbitrary redaction is required before persistence.</summary>
    [JsonPropertyName("requireRedaction")]
    public bool RequireRedaction { get; init; }
}

/// <summary>
/// Attachment policy scoped to one form field.
/// </summary>
public sealed class FormFieldAttachmentPolicy
{
    /// <summary>Form field id for this policy.</summary>
    [JsonPropertyName("fieldId")]
    public string? FieldId { get; init; }

    /// <summary>Maximum attachments accepted for this field.</summary>
    [JsonPropertyName("maxCount")]
    public int? MaxCount { get; init; }

    /// <summary>Allowed MIME types for this field.</summary>
    [JsonPropertyName("allowedContentTypes")]
    public string[] AllowedContentTypes { get; init; } = [];

    /// <summary>Whether this attachment field is required.</summary>
    [JsonPropertyName("required")]
    public bool Required { get; init; }
}

/// <summary>
/// Privacy policy attached to a form package.
/// </summary>
public sealed class FormPrivacyPolicy
{
    /// <summary>Field ids whose values should not be copied into audit details.</summary>
    [JsonPropertyName("privateFieldIds")]
    public string[] PrivateFieldIds { get; init; } = [];

    /// <summary>Required transforms such as none or auditOnly.</summary>
    [JsonPropertyName("requiredTransformations")]
    public string[] RequiredTransformations { get; init; } = [];

    /// <summary>Whether server records should capture the actor identifier.</summary>
    [JsonPropertyName("captureActor")]
    public bool CaptureActor { get; init; } = true;

    /// <summary>Whether server records should capture the client/device id.</summary>
    [JsonPropertyName("captureDeviceId")]
    public bool CaptureDeviceId { get; init; } = true;

    /// <summary>Optional retention hint in days.</summary>
    [JsonPropertyName("retentionDays")]
    public int? RetentionDays { get; init; }
}

/// <summary>
/// Offline sync policy for a package.
/// </summary>
public sealed class FormOfflinePolicy
{
    /// <summary>Whether field clients may cache this package for offline work.</summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

    /// <summary>Preferred transport identifiers in priority order.</summary>
    [JsonPropertyName("preferredTransports")]
    public string[] PreferredTransports { get; init; } = ["feature-server-replica", "fieldcollection"];

    /// <summary>Whether existing GeoServices FeatureServer replica endpoints should be advertised.</summary>
    [JsonPropertyName("replicaTransportEnabled")]
    public bool ReplicaTransportEnabled { get; init; } = true;

    /// <summary>Whether FieldCollection mobile sync endpoints should be advertised.</summary>
    [JsonPropertyName("fieldCollectionTransportEnabled")]
    public bool FieldCollectionTransportEnabled { get; init; } = true;

    /// <summary>Conflict review mode. Full conflict review is outside this ticket.</summary>
    [JsonPropertyName("conflictReviewMode")]
    public string? ConflictReviewMode { get; init; } = "defer";
}

/// <summary>
/// Package authoring provenance.
/// </summary>
public sealed class FormProvenanceRef
{
    /// <summary>Tool or subsystem that produced the package.</summary>
    [JsonPropertyName("source")]
    public string? Source { get; init; }

    /// <summary>Source package version or revision.</summary>
    [JsonPropertyName("sourceVersion")]
    public string? SourceVersion { get; init; }
}

/// <summary>
/// Persisted form package version.
/// </summary>
public sealed class FormPackageVersion
{
    /// <summary>Stable package id.</summary>
    [JsonPropertyName("formId")]
    public string FormId { get; init; } = string.Empty;

    /// <summary>Monotonic integer version.</summary>
    [JsonPropertyName("version")]
    public int Version { get; init; }

    /// <summary>Package lifecycle status.</summary>
    [JsonPropertyName("status")]
    public string Status { get; init; } = FormPackageStatus.Draft;

    /// <summary>Package document.</summary>
    [JsonPropertyName("package")]
    public FormPackageDocument Package { get; init; } = new();

    /// <summary>Last stored validation result, when available.</summary>
    [JsonPropertyName("validation")]
    public FormPackageValidationResult? Validation { get; init; }

    /// <summary>Stable content hash for the package document.</summary>
    [JsonPropertyName("contentHash")]
    public string ContentHash { get; init; } = string.Empty;

    /// <summary>Policy hash covering submit, attachment, privacy, and offline policy.</summary>
    [JsonPropertyName("policyHash")]
    public string PolicyHash { get; init; } = string.Empty;

    /// <summary>HTTP ETag for draft concurrency and immutable readback.</summary>
    [JsonPropertyName("etag")]
    public string ETag { get; init; } = string.Empty;

    /// <summary>UTC creation timestamp.</summary>
    [JsonPropertyName("createdAt")]
    public DateTimeOffset CreatedAt { get; init; }

    /// <summary>Actor that created this version.</summary>
    [JsonPropertyName("createdBy")]
    public string? CreatedBy { get; init; }

    /// <summary>UTC publish timestamp for published versions.</summary>
    [JsonPropertyName("publishedAt")]
    public DateTimeOffset? PublishedAt { get; init; }

    /// <summary>Actor that published this version.</summary>
    [JsonPropertyName("publishedBy")]
    public string? PublishedBy { get; init; }

    /// <summary>Published version that was reopened into this draft.</summary>
    [JsonPropertyName("reopenedFromVersion")]
    public int? ReopenedFromVersion { get; init; }
}

/// <summary>
/// Summary row for listing package families.
/// </summary>
public sealed class FormPackageSummary
{
    /// <summary>Stable package id.</summary>
    [JsonPropertyName("formId")]
    public string FormId { get; init; } = string.Empty;

    /// <summary>Current package title.</summary>
    [JsonPropertyName("title")]
    public string Title { get; init; } = string.Empty;

    /// <summary>Target service id.</summary>
    [JsonPropertyName("serviceId")]
    public string ServiceId { get; init; } = string.Empty;

    /// <summary>Target layer id.</summary>
    [JsonPropertyName("layerId")]
    public int LayerId { get; init; }

    /// <summary>Current draft version, when present.</summary>
    [JsonPropertyName("currentDraftVersion")]
    public int? CurrentDraftVersion { get; init; }

    /// <summary>Current published version, when present.</summary>
    [JsonPropertyName("currentPublishedVersion")]
    public int? CurrentPublishedVersion { get; init; }

    /// <summary>UTC update timestamp.</summary>
    [JsonPropertyName("updatedAt")]
    public DateTimeOffset UpdatedAt { get; init; }
}

/// <summary>
/// Validation result for a package or submission.
/// </summary>
public sealed class FormPackageValidationResult
{
    /// <summary>Whether the validated subject has no error-severity issues.</summary>
    [JsonPropertyName("isValid")]
    public bool IsValid { get; init; }

    /// <summary>Validation issues.</summary>
    [JsonPropertyName("issues")]
    public FormValidationIssue[] Issues { get; init; } = [];
}

/// <summary>
/// Single validation issue.
/// </summary>
public sealed class FormValidationIssue
{
    /// <summary>Stable machine-readable issue code.</summary>
    [JsonPropertyName("code")]
    public string Code { get; init; } = string.Empty;

    /// <summary>Issue severity, usually error or warning.</summary>
    [JsonPropertyName("severity")]
    public string Severity { get; init; } = "error";

    /// <summary>Optional field id associated with the issue.</summary>
    [JsonPropertyName("fieldId")]
    public string? FieldId { get; init; }

    /// <summary>Optional JSON pointer or property path.</summary>
    [JsonPropertyName("path")]
    public string? Path { get; init; }

    /// <summary>Human-readable issue message.</summary>
    [JsonPropertyName("message")]
    public string Message { get; init; } = string.Empty;
}

/// <summary>
/// Runtime form submission request.
/// </summary>
public sealed class FormSubmissionRequest
{
    /// <summary>Optional idempotency key scoped to actor, package, and version.</summary>
    [JsonPropertyName("idempotencyKey")]
    public string? IdempotencyKey { get; init; }

    /// <summary>Explicit package version. Current published version is used when omitted.</summary>
    [JsonPropertyName("formVersion")]
    public int? FormVersion { get; init; }

    /// <summary>Requested operation, defaulting to create.</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; init; } = FormSubmissionOperations.Create;

    /// <summary>Existing target feature id for update/delete operations.</summary>
    [JsonPropertyName("targetFeatureId")]
    public long? TargetFeatureId { get; init; }

    /// <summary>Client or device identifier for sync records.</summary>
    [JsonPropertyName("clientId")]
    public string? ClientId { get; init; }

    /// <summary>Client submission timestamp.</summary>
    [JsonPropertyName("submittedAt")]
    public DateTimeOffset? SubmittedAt { get; init; }

    /// <summary>Submitted field values keyed by form field id.</summary>
    [JsonPropertyName("values")]
    public Dictionary<string, JsonElement> Values { get; init; } = new(StringComparer.Ordinal);

    /// <summary>Submitted geometry encoded as GeoServices-style JSON.</summary>
    [JsonPropertyName("geometry")]
    public JsonElement? Geometry { get; init; }

    /// <summary>Attachment descriptors. Multipart submissions provide file content by part name.</summary>
    [JsonPropertyName("attachments")]
    public FormSubmissionAttachmentDescriptor[] Attachments { get; init; } = [];
}

/// <summary>
/// Attachment metadata supplied with a form submission.
/// </summary>
public sealed class FormSubmissionAttachmentDescriptor
{
    /// <summary>Client-side attachment identifier.</summary>
    [JsonPropertyName("clientAttachmentId")]
    public string? ClientAttachmentId { get; init; }

    /// <summary>Attachment field id in the package.</summary>
    [JsonPropertyName("fieldId")]
    public string? FieldId { get; init; }

    /// <summary>Multipart part name containing file bytes.</summary>
    [JsonPropertyName("partName")]
    public string? PartName { get; init; }

    /// <summary>Original filename.</summary>
    [JsonPropertyName("filename")]
    public string? Filename { get; init; }

    /// <summary>Submitted MIME content type.</summary>
    [JsonPropertyName("contentType")]
    public string? ContentType { get; init; }

    /// <summary>Submitted size in bytes.</summary>
    [JsonPropertyName("sizeBytes")]
    public long? SizeBytes { get; init; }

    /// <summary>Optional SHA-256 checksum supplied by the client.</summary>
    [JsonPropertyName("sha256")]
    public string? Sha256 { get; init; }
}

/// <summary>
/// Runtime submission response.
/// </summary>
public sealed class FormSubmissionResponse
{
    /// <summary>Server submission identifier.</summary>
    [JsonPropertyName("submissionId")]
    public Guid SubmissionId { get; init; }

    /// <summary>Response status such as accepted, rejected, or failed.</summary>
    [JsonPropertyName("status")]
    public string Status { get; init; } = "accepted";

    /// <summary>Package id.</summary>
    [JsonPropertyName("formId")]
    public string FormId { get; init; } = string.Empty;

    /// <summary>Package version.</summary>
    [JsonPropertyName("formVersion")]
    public int FormVersion { get; init; }

    /// <summary>Applied operation.</summary>
    [JsonPropertyName("operation")]
    public string Operation { get; init; } = FormSubmissionOperations.Create;

    /// <summary>Target feature id when known.</summary>
    [JsonPropertyName("targetFeatureId")]
    public long? TargetFeatureId { get; init; }

    /// <summary>Feature edit outcome.</summary>
    [JsonPropertyName("editOutcome")]
    public FormEditOutcome? EditOutcome { get; init; }

    /// <summary>Attachment persistence outcomes.</summary>
    [JsonPropertyName("attachmentOutcomes")]
    public FormSubmissionAttachmentOutcome[] AttachmentOutcomes { get; init; } = [];

    /// <summary>Validation issues when rejected.</summary>
    [JsonPropertyName("validationIssues")]
    public FormValidationIssue[] ValidationIssues { get; init; } = [];

    /// <summary>Retry guidance for offline clients.</summary>
    [JsonPropertyName("retry")]
    public FormSubmissionRetryGuidance? Retry { get; init; }

    /// <summary>Whether this response was returned from an idempotency replay record.</summary>
    [JsonPropertyName("idempotentReplay")]
    public bool IdempotentReplay { get; init; }
}

/// <summary>
/// Canonical feature edit outcome for a submission.
/// </summary>
public sealed class FormEditOutcome
{
    /// <summary>Whether the edit succeeded.</summary>
    [JsonPropertyName("succeeded")]
    public bool Succeeded { get; init; }

    /// <summary>Created feature count.</summary>
    [JsonPropertyName("created")]
    public int Created { get; init; }

    /// <summary>Updated feature count.</summary>
    [JsonPropertyName("updated")]
    public int Updated { get; init; }

    /// <summary>Deleted feature count.</summary>
    [JsonPropertyName("deleted")]
    public int Deleted { get; init; }

    /// <summary>Sanitized edit error, if any.</summary>
    [JsonPropertyName("error")]
    public string? Error { get; init; }
}

/// <summary>
/// Attachment policy and persistence outcome for one submitted attachment.
/// </summary>
public sealed class FormSubmissionAttachmentOutcome
{
    /// <summary>Client-side attachment identifier.</summary>
    [JsonPropertyName("clientAttachmentId")]
    public string? ClientAttachmentId { get; init; }

    /// <summary>Package field id.</summary>
    [JsonPropertyName("fieldId")]
    public string? FieldId { get; init; }

    /// <summary>Outcome status.</summary>
    [JsonPropertyName("status")]
    public string Status { get; init; } = "accepted";

    /// <summary>Persisted attachment id when upload succeeded.</summary>
    [JsonPropertyName("attachmentId")]
    public long? AttachmentId { get; init; }

    /// <summary>Sanitized rejection or failure reason.</summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; init; }

    /// <summary>Whether privacy policy transforms or minimization were applied.</summary>
    [JsonPropertyName("privacyApplied")]
    public bool PrivacyApplied { get; init; }
}

/// <summary>
/// Retry guidance for offline/mobile clients.
/// </summary>
public sealed class FormSubmissionRetryGuidance
{
    /// <summary>Whether retry is safe.</summary>
    [JsonPropertyName("retryable")]
    public bool Retryable { get; init; }

    /// <summary>Optional retry-after delay in seconds.</summary>
    [JsonPropertyName("retryAfterSeconds")]
    public int? RetryAfterSeconds { get; init; }

    /// <summary>Human-readable retry reason.</summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; init; }
}

/// <summary>
/// Discoverable offline policy for a published package.
/// </summary>
public sealed class FormOfflinePolicyResponse
{
    /// <summary>Package id.</summary>
    [JsonPropertyName("formId")]
    public string FormId { get; init; } = string.Empty;

    /// <summary>Package version.</summary>
    [JsonPropertyName("formVersion")]
    public int FormVersion { get; init; }

    /// <summary>Whether offline use is enabled.</summary>
    [JsonPropertyName("enabled")]
    public bool Enabled { get; init; }

    /// <summary>Target feature service id.</summary>
    [JsonPropertyName("serviceId")]
    public string ServiceId { get; init; } = string.Empty;

    /// <summary>Target layer id.</summary>
    [JsonPropertyName("layerId")]
    public int LayerId { get; init; }

    /// <summary>Available sync transports.</summary>
    [JsonPropertyName("availableTransports")]
    public string[] AvailableTransports { get; init; } = [];

    /// <summary>Links to existing sync endpoints.</summary>
    [JsonPropertyName("links")]
    public FormLink[] Links { get; init; } = [];

    /// <summary>Required request headers for sync clients.</summary>
    [JsonPropertyName("requiredHeaders")]
    public Dictionary<string, string> RequiredHeaders { get; init; } = new(StringComparer.Ordinal);
}

/// <summary>
/// Link relation in offline policy responses.
/// </summary>
public sealed class FormLink
{
    /// <summary>Link relation.</summary>
    [JsonPropertyName("rel")]
    public string Rel { get; init; } = string.Empty;

    /// <summary>Absolute link target.</summary>
    [JsonPropertyName("href")]
    public string Href { get; init; } = string.Empty;

    /// <summary>HTTP method.</summary>
    [JsonPropertyName("method")]
    public string Method { get; init; } = "GET";
}

/// <summary>
/// Durable submission record for idempotency lookup.
/// </summary>
public sealed class FormSubmissionRecord
{
    /// <summary>Submission identifier.</summary>
    public Guid SubmissionId { get; init; }

    /// <summary>Hash of the original request body.</summary>
    public string RequestHash { get; init; } = string.Empty;

    /// <summary>Stored response, when the submission reached a terminal state.</summary>
    public FormSubmissionResponse? Response { get; init; }

    /// <summary>Record status such as pending, accepted, rejected, or failed.</summary>
    public string Status { get; init; } = string.Empty;
}
