// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

namespace Honua.Server;

/// <summary>
/// Registry of all public HTTP endpoints exposed by Honua.Server.
/// Keep this list in sync with endpoint mappings to enforce API surface coverage.
/// </summary>
public static class EndpointRegistry
{
    /// <summary>
    /// All endpoints that require integration test coverage.
    /// </summary>
    public static IReadOnlyList<EndpointDefinition> All { get; } =
    [
        new("GET", "/healthz/live"),
        new("GET", "/healthz/ready"),
        new("GET", "/healthz/metrics"),
        new("GET", "/metrics"),

        // Interactive API explorer (Scalar)
        new("GET", "/docs"),

        new("GET", "/api/v1/admin/config"),
        new("GET", "/api/v1/admin/auth/config"),
        new("POST", "/api/v1/admin/auth/providers/{providerKey}/authorize-url"),
        new("POST", "/api/v1/admin/auth/providers/{providerKey}/token"),
        new("GET", "/api/v1/admin/auth/providers/{providerKey}/logout-url"),
        new("GET", "/api/v1/admin/openapi.json"),
        new("GET", "/api/v1/admin/connections/{id}/tables"),
        new("GET", "/api/v1/admin/connections/tables"),
        new("GET", "/api/v1/admin/connections/{*path}"),
        new("GET", "/api/v1/admin/connections/{id}/layers"),
        new("POST", "/api/v1/admin/connections/{id}/layers"),
        new("PUT", "/api/v1/admin/connections/{id}/layers/{layerId}/enabled"),
        new("PUT", "/api/v1/admin/connections/{id}/layers/enabled"),
        new("GET", "/api/v1/admin/version"),
        new("GET", "/api/v1/admin/capabilities"),
        new("GET", "/api/v1/admin/manifest"),
        new("POST", "/api/v1/admin/manifest/apply"),
        new("GET", "/api/v1/admin/manifest/pending"),
        new("GET", "/api/v1/admin/manifest/pending/{id}"),
        new("POST", "/api/v1/admin/manifest/pending/{id}/approve"),
        new("POST", "/api/v1/admin/manifest/pending/{id}/reject"),
        new("GET", "/api/v1/admin/manifest/pending/history"),
        new("GET", "/api/v1/admin/manifest/drift"),
        new("GET", "/api/v1/admin/manifest/versions"),
        new("GET", "/api/v1/admin/manifest/versions/{versionId}"),
        new("GET", "/api/v1/admin/deploy/preflight"),
        new("POST", "/api/v1/admin/deploy/plan"),
        new("POST", "/api/v1/admin/deploy/operations"),
        new("GET", "/api/v1/admin/deploy/operations/{operationId}"),
        new("POST", "/api/v1/admin/deploy/operations/{operationId}/submit"),
        new("POST", "/api/v1/admin/deploy/operations/{operationId}/rollback"),
        new("GET", "/api/v1/admin/services"),
        new("GET", "/api/v1/admin/services/{serviceName}/settings"),
        new("PUT", "/api/v1/admin/services/{serviceName}/protocols"),
        new("PUT", "/api/v1/admin/services/{serviceName}/mapserver"),
        new("PUT", "/api/v1/admin/services/{serviceName}/access-policy"),
        new("PUT", "/api/v1/admin/services/{serviceName}/timeinfo"),
        new("PUT", "/api/v1/admin/services/{serviceName}/layers/{layerId}/metadata"),

        // v1 admin secure connection endpoints
        new("GET", "/api/v1/admin/connections"),
        new("GET", "/api/v1/admin/connections/{id}"),
        new("POST", "/api/v1/admin/connections"),
        new("POST", "/api/v1/admin/connections/test"),
        new("PUT", "/api/v1/admin/connections/{id}"),
        new("DELETE", "/api/v1/admin/connections/{id}"),
        new("POST", "/api/v1/admin/connections/{id}/test"),
        new("POST", "/api/v1/admin/connections/encryption/validate"),
        new("POST", "/api/v1/admin/connections/encryption/rotate-key"),

        // v1 admin license management endpoints (#511)
        new("GET", "/api/v1/admin/license"),
        new("POST", "/api/v1/admin/license"),
        new("GET", "/api/v1/admin/license/entitlements"),

        // v1 platform admin endpoints (#513)
        new("GET", "/api/v1/admin/license/status"),
        new("GET", "/api/v1/admin/license/features"),
        new("POST", "/api/v1/admin/license/upload"),
        new("GET", "/api/v1/admin/identity/providers"),
        new("GET", "/api/v1/admin/identity/providers/{providerType}/test"),
        new("GET", "/api/v1/admin/cache/status"),
        new("POST", "/api/v1/admin/cache/invalidate"),
        new("GET", "/api/v1/admin/geocoding/providers"),
        new("GET", "/api/v1/admin/features"),

        // v1 admin OIDC provider endpoints (#511)
        new("GET", "/api/v1/admin/oidc/providers"),
        new("POST", "/api/v1/admin/oidc/providers"),
        new("GET", "/api/v1/admin/oidc/providers/{id}"),
        new("PUT", "/api/v1/admin/oidc/providers/{id}"),
        new("DELETE", "/api/v1/admin/oidc/providers/{id}"),
        new("POST", "/api/v1/admin/oidc/providers/{id}/test"),

        // v1 admin user management endpoints (#511)
        new("GET", "/api/v1/admin/users"),
        new("GET", "/api/v1/admin/users/{id}"),
        new("PUT", "/api/v1/admin/users/{id}/roles"),
        new("DELETE", "/api/v1/admin/users/{id}"),
        new("GET", "/api/v1/admin/users/{id}/effective-permissions"),

        // v1 admin role management endpoints (#511)
        new("GET", "/api/v1/admin/roles"),
        new("POST", "/api/v1/admin/roles"),
        new("GET", "/api/v1/admin/roles/{id}"),
        new("PUT", "/api/v1/admin/roles/{id}"),
        new("DELETE", "/api/v1/admin/roles/{id}"),
        new("GET", "/api/v1/admin/roles/{id}/permissions"),
        new("PUT", "/api/v1/admin/roles/{id}/permissions"),

        // v1 admin rate limit policy endpoints (#511)
        new("GET", "/api/v1/admin/rate-limits"),
        new("POST", "/api/v1/admin/rate-limits"),
        new("GET", "/api/v1/admin/rate-limits/{id}"),
        new("PUT", "/api/v1/admin/rate-limits/{id}"),
        new("DELETE", "/api/v1/admin/rate-limits/{id}"),
        new("GET", "/api/v1/admin/rate-limits/status"),

        // v1 admin metadata resource endpoints
        new("GET", "/api/v1/admin/metadata/resources"),
        new("GET", "/api/v1/admin/metadata/resources/{kind}/{namespace}/{name}"),
        new("POST", "/api/v1/admin/metadata/resources"),
        new("PUT", "/api/v1/admin/metadata/resources/{kind}/{namespace}/{name}"),
        new("DELETE", "/api/v1/admin/metadata/resources/{kind}/{namespace}/{name}"),
        new("GET", "/api/v1/admin/metadata/layers/{layerId}/style"),
        new("PUT", "/api/v1/admin/metadata/layers/{layerId}/style"),
        new("POST", "/api/v1/admin/metadata/layers/{layerId}/suggest-style"),
        new("POST", "/api/v1/admin/gitops/watch"),
        new("PUT", "/api/v1/admin/gitops/watch"),
        new("GET", "/api/v1/admin/gitops/watch"),
        new("DELETE", "/api/v1/admin/gitops/watch"),
        new("GET", "/api/v1/admin/gitops/changes"),
        new("GET", "/api/v1/admin/gitops/changes/{id}"),
        new("GET", "/api/v1/admin/gitops/changes/{id}/diff"),
        new("GET", "/api/v1/admin/alerts/zones"),
        new("POST", "/api/v1/admin/alerts/zones"),
        new("PUT", "/api/v1/admin/alerts/zones/{zoneId}"),
        new("DELETE", "/api/v1/admin/alerts/zones/{zoneId}"),
        new("GET", "/api/v1/admin/alerts/rules"),
        new("POST", "/api/v1/admin/alerts/rules"),
        new("PUT", "/api/v1/admin/alerts/rules/{ruleId}"),
        new("DELETE", "/api/v1/admin/alerts/rules/{ruleId}"),

        // v1 admin import endpoints (primary)
        new("GET", "/api/v1/admin/import/formats"),
        new("POST", "/api/v1/admin/import/preview"),
        new("POST", "/api/v1/admin/import/preview-url"),
        new("POST", "/api/v1/admin/import/upload"),
        new("POST", "/api/v1/admin/import/upload-url"),
        new("GET", "/api/v1/admin/import/uploads/{uploadId}/progress"),
        new("POST", "/api/v1/admin/import/uploads/{uploadId}/cancel"),
        new("GET", "/api/v1/admin/import/uploads"),
        new("GET", "/api/v1/admin/import/jobs/{jobId}"),
        new("POST", "/api/v1/admin/import/jobs/{jobId}/cancel"),
        new("GET", "/api/v1/admin/import/jobs"),
        new("GET", "/api/v1/admin/import/limits"),

        // v1 admin import endpoints (Geoservices)
        new("POST", "/api/v1/admin/import/geoservices/discover"),
        new("POST", "/api/v1/admin/import/geoservices/start"),
        new("GET", "/api/v1/admin/import/geoservices/jobs/{jobId}"),
        new("POST", "/api/v1/admin/import/geoservices/jobs/{jobId}/cancel"),
        new("GET", "/api/v1/admin/import/geoservices/jobs"),

        // v1 admin import endpoints (Raster)
        new("POST", "/api/v1/admin/import/raster"),
        new("GET", "/api/v1/admin/import/raster/formats"),

        // v1 admin import endpoints (GeoServer)
        new("POST", "/api/v1/admin/import/geoserver/discover"),
        new("POST", "/api/v1/admin/import/geoserver/start"),
        new("GET", "/api/v1/admin/import/geoserver/jobs/{jobId}"),
        new("POST", "/api/v1/admin/import/geoserver/jobs/{jobId}/cancel"),
        new("GET", "/api/v1/admin/import/geoserver/jobs"),

        // v1 admin operational monitoring endpoints (#512)
        new("GET", "/api/v1/admin/operations/cache/health"),
        new("POST", "/api/v1/admin/operations/cache/invalidate"),
        new("GET", "/api/v1/admin/operations/streaming/subscribers"),
        new("GET", "/api/v1/admin/operations/streaming/alerts"),
        new("DELETE", "/api/v1/admin/operations/streaming/subscribers/{subscriberId}"),

        // v1 feature-change streaming endpoints (#501)
        new("GET", "/api/v1/streaming/features"),
        new("GET", "/api/v1/admin/streaming/features/sessions"),
        new("DELETE", "/api/v1/admin/streaming/features/sessions/{sessionId}"),

        new("GET", "/api/v1/admin/operations/geocoding/providers"),
        new("GET", "/api/v1/admin/operations/geocoding/configuration"),

        // v1 admin operations progress endpoints
        new("GET", "/api/v1/admin/operations/{operationId}"),
        new("POST", "/api/v1/admin/operations/{operationId}/cancel"),
        new("GET", "/api/v1/admin/operations/active"),
        new("GET", "/api/v1/admin/operations/type/{operationType}"),
        new("GET", "/api/v1/admin/feature-events/replay"),
        new("POST", "/api/v1/admin/tile-operations/jobs"),
        new("GET", "/api/v1/admin/tile-operations/jobs/{jobId}"),
        new("GET", "/api/v1/admin/tile-operations/jobs"),
        new("POST", "/api/v1/admin/tile-operations/jobs/{jobId}/cancel"),
        new("POST", "/api/v1/admin/tile-operations/jobs/{jobId}/retry"),

        new("GET", "/api/v1/admin/observability/errors"),
        new("GET", "/api/v1/admin/observability/telemetry"),
        new("GET", "/api/v1/admin/observability/migrations"),

        new("GET", "/api/v1/admin/performance/database/query-cache/statistics"),

        new("GET", "/api/v1/metrics/health"),
        new("GET", "/api/v1/metrics/performance"),
        new("GET", "/api/v1/metrics/database"),
        new("GET", "/api/v1/metrics/cache"),
        new("GET", "/api/v1/metrics/memory"),
        new("GET", "/api/v1/metrics/streaming"),

        new("POST", "/csp-violation-report"),

        new("GET", "/rest/services"),
        new("GET", "/rest/info"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer/findAddressCandidates"),
        new("POST", "/rest/services/{locatorName}/GeocodeServer/findAddressCandidates"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer/reverseGeocode"),
        new("POST", "/rest/services/{locatorName}/GeocodeServer/reverseGeocode"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer/suggest"),
        new("POST", "/rest/services/{locatorName}/GeocodeServer/suggest"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer/geocodeAddresses"),
        new("POST", "/rest/services/{locatorName}/GeocodeServer/geocodeAddresses"),
        new("GET", "/rest/services/GeocodeServer"),
        new("GET", "/rest/services/GeocodeServer/findAddressCandidates"),
        new("GET", "/rest/services/GeocodeServer/reverseGeocode"),
        new("GET", "/rest/services/GeocodeServer/suggest"),
        new("GET", "/rest/services/GeocodeServer/geocodeAddresses"),

        new("GET", "/rest/services/{serviceId}/FeatureServer"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/query"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/query"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/query"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/query"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/applyEdits"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/applyEdits"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/addFeatures"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/updateFeatures"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/deleteFeatures"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryRelatedRecords"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryRelatedRecords"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/generateRenderer"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/createReplica"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/extractChanges"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/synchronizeReplica"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/unRegisterReplica"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/append"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/append"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/calculate"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/queryDomains"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/relationships"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/validateSQL"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/getEstimates"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/getEstimates"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryTopFeatures"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryTopFeatures"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryDateBins"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryDateBins"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryBins"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryBins"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryH3"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryH3"),
        new("GET", "/tiles/{layerId}/{z}/{x}/{y}.mvt"),
        new("GET", "/tiles/{layerId}/h3/{z}/{x}/{y}.mvt"),
        new("GET", "/tiles/{layerId}/tile.json"),
        new("GET", "/api/styles/{layerId}.json"),

        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryAttachments"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryAttachments"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/addAttachment"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/addAttachment"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/updateAttachment"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/updateAttachment"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/deleteAttachments"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/deleteAttachments"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/attachments/{attachmentId}"),

        new("GET", "/rest/services/{serviceId}/MapServer"),
        new("GET", "/rest/services/{serviceId}/MapServer/{layerId}"),
        new("GET", "/rest/services/{serviceId}/MapServer/export"),
        new("POST", "/rest/services/{serviceId}/MapServer/export"),
        new("GET", "/rest/services/{serviceId}/MapServer/generateKml"),
        new("POST", "/rest/services/{serviceId}/MapServer/generateKml"),
        new("GET", "/rest/services/{serviceId}/MapServer/identify"),
        new("POST", "/rest/services/{serviceId}/MapServer/identify"),
        new("GET", "/rest/services/{serviceId}/MapServer/legend"),
        new("GET", "/rest/services/{serviceId}/MapServer/find"),
        new("POST", "/rest/services/{serviceId}/MapServer/find"),
        new("GET", "/rest/services/{serviceId}/MapServer/{layerId}/query"),
        new("POST", "/rest/services/{serviceId}/MapServer/{layerId}/query"),
        new("GET", "/rest/services/{serviceId}/MapServer/query"),
        new("POST", "/rest/services/{serviceId}/MapServer/query"),
        new("GET", "/rest/services/{serviceId}/MapServer/tile/{z}/{y}/{x}"),
        new("GET", "/rest/services/{serviceId}/MapServer/WMTS"),
        new("GET", "/rest/services/{serviceId}/MapServer/WMTS/{**restPath}"),
        new("GET", "/rest/services/{serviceId}/MapServer/WMS"),
        new("GET", "/ogc/services/{serviceId}/wmts"),
        new("GET", "/ogc/services/{serviceId}/wms"),

        new("GET", "/rest/services/{id}/ImageServer"),
        new("GET", "/rest/services/{id}/ImageServer/exportImage"),
        new("GET", "/rest/services/{id}/ImageServer/identify"),
        new("GET", "/rest/services/{id}/ImageServer/tile/{level}/{row}/{col}"),

        new("GET", "/odata"),
        new("GET", "/odata/$metadata"),
        new("GET", "/odata/Layers"),
        new("GET", "/odata/Layers({layerId})"),
        new("GET", "/odata/Layers/$count"),
        new("GET", "/odata/Layers({layerId})/Features"),
        new("GET", "/odata/Layers({layerId})/Features/$count"),
        new("POST", "/odata/Layers({layerId})/Features"),
        new("GET", "/odata/Layers({layerId})/Features({objectId})"),
        new("PATCH", "/odata/Layers({layerId})/Features({objectId})"),
        new("DELETE", "/odata/Layers({layerId})/Features({objectId})"),
        new("GET", "/odata/Features"),
        new("GET", "/odata/Features/$count"),
        new("POST", "/odata/Features"),
        new("GET", "/odata/Features(LayerId={layerId},ObjectId={objectId})"),
        new("GET", "/odata/Features(LayerId={layerId},ObjectId={objectId})/$ref"),
        new("GET", "/odata/Features(LayerId={layerId},ObjectId={objectId})/$value"),
        new("PATCH", "/odata/Features(LayerId={layerId},ObjectId={objectId})"),
        new("DELETE", "/odata/Features(LayerId={layerId},ObjectId={objectId})"),
        new("GET", "/odata/Features({layerId})"),
        new("GET", "/odata/Features({layerId})/$count"),
        new("GET", "/odata/Features({layerId},{objectId})"),
        new("PATCH", "/odata/Features({layerId},{objectId})"),
        new("DELETE", "/odata/Features({layerId},{objectId})"),
        new("POST", "/odata/$batch"),
        new("GET", "/odata/Features({layerId})/$apply"),
        new("GET", "/odata/Features({layerId})/$search"),

        new("GET", "/ogc/features"),
        new("GET", "/ogc/features/conformance"),
        new("GET", "/openapi.json"),
        new("GET", "/ogc/features/collections"),
        new("GET", "/ogc/features/collections/{collectionId}"),
        new("GET", "/ogc/features/collections/{collectionId}/queryables"),
        new("GET", "/ogc/features/collections/{collectionId}/items"),
        new("GET", "/ogc/features/api"),
        new("GET", "/ogc/features/collections/{collectionId}/items/{featureId}"),
        new("POST", "/ogc/features/collections/{collectionId}/items"),
        new("POST", "/ogc/features/collections/{collectionId}/items/batch"),
        new("PUT", "/ogc/features/collections/{collectionId}/items/{featureId}"),
        new("PATCH", "/ogc/features/collections/{collectionId}/items/{featureId}"),
        new("DELETE", "/ogc/features/collections/{collectionId}/items/{featureId}"),
        new("GET", "/ogc/features/collections/{collectionId}/h3"),

        new("GET", "/ogc/tiles"),
        new("GET", "/ogc/tiles/conformance"),
        new("GET", "/ogc/tiles/openapi.json"),
        new("GET", "/ogc/tiles/collections"),
        new("GET", "/ogc/tiles/collections/{collectionId}"),
        new("GET", "/ogc/tiles/collections/{collectionId}/tiles"),
        new("GET", "/ogc/tiles/collections/{collectionId}/tiles/{tileMatrixSetId}"),
        new("GET", "/ogc/tiles/collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}"),
        new("GET", "/ogc/tiles/tiles"),
        new("GET", "/ogc/tiles/tiles/{tileMatrixSetId}"),
        new("GET", "/ogc/tiles/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}"),
        new("GET", "/ogc/tiles/tileMatrixSets"),
        new("GET", "/ogc/tiles/tileMatrixSets/{tileMatrixSetId}"),

        new("GET", "/rest/services/geometry/buffer"),
        new("POST", "/rest/services/geometry/buffer"),
        new("GET", "/rest/services/geometry/simplify"),
        new("POST", "/rest/services/geometry/simplify"),
        new("GET", "/rest/services/geometry/project"),
        new("POST", "/rest/services/geometry/project"),
        new("GET", "/rest/services/geometry/intersect"),
        new("POST", "/rest/services/geometry/intersect"),
        new("GET", "/rest/services/geometry/union"),
        new("POST", "/rest/services/geometry/union"),
        new("GET", "/rest/services/geometry/clip"),
        new("POST", "/rest/services/geometry/clip"),
        new("GET", "/rest/services/geometry/difference"),
        new("POST", "/rest/services/geometry/difference"),
        new("GET", "/rest/services/geometry/area"),
        new("POST", "/rest/services/geometry/area"),
        new("GET", "/rest/services/geometry/length"),
        new("POST", "/rest/services/geometry/length"),

        new("GET", "/ogc/maps"),
        new("GET", "/ogc/maps/conformance"),
        new("GET", "/ogc/maps/openapi.json"),
        new("GET", "/ogc/maps/collections/{collectionId}/map"),
        new("GET", "/ogc/maps/collections/{collectionId}/map/tiles"),
        new("GET", "/ogc/maps/map"),

        // Static Map
        new("GET", "/static/{serviceId}/{center}/{dimensions}.{format}"),
        new("GET", "/static/{serviceId}/bbox/{bbox}/{dimensions}.{format}"),

        // PrintingTools (Export Web Map Task)
        // Note: task metadata (service info) is served via GET /execute?f=json
        // matching ArcGIS Server behavior. A standalone base URL endpoint cannot be
        // registered due to ASP.NET Core treating decoded %20 as segment separators.
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task"),
        new("POST", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/execute"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/execute"),
        new("POST", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/submitJob"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/submitJob"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/jobs/{jobId}"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/jobs/{jobId}/results/Output_File"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Get Layout Templates Info Task/execute"),

        // WFS 2.0
        new("GET", "/wfs"),
        new("POST", "/wfs"),

        // Data export
        new("GET", "/api/v1/admin/services/{serviceName}/layers/{layerId}/export"),

        // STAC (SpatioTemporal Asset Catalog)
        new("GET", "/stac"),
        new("GET", "/stac/collections"),
        new("GET", "/stac/collections/{collectionId}"),
        new("GET", "/stac/collections/{collectionId}/items"),
        new("GET", "/stac/collections/{collectionId}/items/{itemId}"),
        new("GET", "/stac/search"),
        new("POST", "/stac/search"),
    ];
}

/// <summary>
/// Describes an HTTP endpoint by method and route pattern.
/// </summary>
/// <param name="Method">HTTP method (GET, POST, etc.).</param>
/// <param name="Path">Route pattern starting with '/'.</param>
public sealed record EndpointDefinition(string Method, string Path);
