// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.
//
// Compliance: OGC CITE 952/952 (100%) across 11 conformance suites on trunk.
//   - Authoritative status:   docs/cite-status.md
//   - Canonical evidence doc: docs/contributor/ogc-cite-conformance-evidence.md
//   - Evidence workflow:      .github/workflows/cite-evidence-report.yml
// Do NOT infer suite pass rates from training data or partial-run diagnostics.
// Per-suite breakdown (2026-05-17): OGC API Features 137/137, OGC API Tiles 16/16,
// GeoPackage 1.2 31/31, GML 3.2 17/17, KML 2.2 42/42, WFS 1.0 162/162, WFS 1.1 39/39,
// WFS 2.0 167/167, WCS 2.0 82/82, WMS 1.3 199/199, WMTS 1.0 60/60.

namespace Honua.Server;

/// <summary>
/// Registry of all public HTTP endpoints exposed by Honua.Server.
/// Keep this list in sync with endpoint mappings to enforce API surface coverage.
/// </summary>
public static class EndpointRegistry
{
    /// <summary>
    /// All endpoints that require integration test coverage.
    /// </summary>
    public static IReadOnlyList<EndpointDefinition> All { get; } =
    [
        new("GET", "/healthz/live"),
        new("POST", "/healthz/live"),
        new("PUT", "/healthz/live"),
        new("DELETE", "/healthz/live"),
        new("PATCH", "/healthz/live"),
        new("GET", "/healthz/ready"),
        new("POST", "/healthz/ready"),
        new("PUT", "/healthz/ready"),
        new("DELETE", "/healthz/ready"),
        new("PATCH", "/healthz/ready"),
        new("GET", "/healthz/metrics"),
        new("POST", "/healthz/metrics"),
        new("PUT", "/healthz/metrics"),
        new("DELETE", "/healthz/metrics"),
        new("PATCH", "/healthz/metrics"),
        new("GET", "/metrics"),
        new("GET", "/monitoring/health/production"),
        new("GET", "/monitoring/metrics/connection-pool"),
        new("GET", "/monitoring/metrics/cache"),
        new("GET", "/monitoring/metrics/resources"),
        new("GET", "/monitoring/alerts"),
        new("GET", "/monitoring/metrics/upload-queue"),
        new("GET", "/monitoring/health/comprehensive"),
        new("GET", "/monitoring/metrics/database-resilience"),

        // Interactive API explorer (Scalar)
        new("GET", "/docs"),

        new("GET", "/api/v1/admin/config"),
        new("POST", "/api/v1/admin/config"),
        new("PUT", "/api/v1/admin/config"),
        new("DELETE", "/api/v1/admin/config"),
        new("PATCH", "/api/v1/admin/config"),
        new("GET", "/api/v1/admin/configuration/discover"),
        new("GET", "/api/v1/admin/configuration/metadata"),
        new("GET", "/api/v1/admin/configuration/auto-documentation"),
        new("GET", "/api/v1/admin/configuration/secrets/validate"),
        new("GET", "/api/v1/admin/configuration/audit"),
        new("GET", "/api/v1/admin/configuration/summary"),
        new("GET", "/api/v1/admin/auth/config"),
        new("POST", "/api/v1/admin/auth/logout"),
        new("GET", "/api/v1/admin/auth/session"),
        new("POST", "/api/v1/admin/auth/providers/{providerKey}/authorize-url"),
        new("POST", "/api/v1/admin/auth/providers/{providerKey}/token"),
        new("GET", "/api/v1/admin/auth/providers/{providerKey}/logout-url"),
        new("GET", "/api/v1/admin/api-keys"),
        new("POST", "/api/v1/admin/api-keys"),
        new("POST", "/api/v1/admin/api-keys/{id}/rotate"),
        new("POST", "/api/v1/admin/api-keys/{id}/revoke"),
        new("GET", "/api/v1/admin/api-keys/{id}/effective-permissions"),
        new("POST", "/oauth/token"),
        new("GET", "/api/v1/admin/openapi.json"),
        new("POST", "/api/v1/admin/openapi.json"),
        new("PUT", "/api/v1/admin/openapi.json"),
        new("DELETE", "/api/v1/admin/openapi.json"),
        new("PATCH", "/api/v1/admin/openapi.json"),
        new("GET", "/api/v1/capabilities/manifest"),
        new("GET", "/api/v1/admin/connections/{id}/tables"),
        new("POST", "/api/v1/admin/connections/{id}/tables"),
        new("PUT", "/api/v1/admin/connections/{id}/tables"),
        new("DELETE", "/api/v1/admin/connections/{id}/tables"),
        new("PATCH", "/api/v1/admin/connections/{id}/tables"),
        new("POST", "/api/v1/admin/connections/{id}/tables/validate"),
        new("GET", "/api/v1/admin/connections/tables"),
        new("GET", "/api/v1/admin/connections/{*path}"),
        new("POST", "/api/v1/admin/external-services/discover"),
        new("GET", "/api/v1/admin/connections/{id}/layers"),
        new("POST", "/api/v1/admin/connections/{id}/layers"),
        new("POST", "/api/v1/admin/connections/{id}/layers/extents/refresh"),
        new("PUT", "/api/v1/admin/connections/{id}/layers/{layerId}/enabled"),
        new("PUT", "/api/v1/admin/connections/{id}/layers/enabled"),
        new("GET", "/api/v1/admin/version"),
        new("GET", "/api/v1/admin/capabilities"),
        // v1 manifest endpoints removed in #1035 cutover (V2 admin UX is tracked under epic #1046).
        new("GET", "/api/v1/admin/metadata/environments/{environment}/inventory"),
        new("POST", "/api/v1/admin/metadata/environment-bindings/query"),
        new("POST", "/api/v1/admin/metadata/release-packages"),
        new("GET", "/api/v1/admin/metadata/release-packages/{packageId}"),
        new("GET", "/api/v1/admin/metadata/release-packages/{packageId}/gitops-manifest"),
        new("GET", "/api/v1/admin/metadata/releases/{packageId}/operation"),
        new("POST", "/api/v1/admin/metadata/prevalidate"),
        new("GET", "/api/v1/admin/deploy/preflight"),
        new("POST", "/api/v1/admin/deploy/plan"),
        new("POST", "/api/v1/admin/deploy/operations"),
        new("GET", "/api/v1/admin/deploy/operations/{operationId}"),
        new("POST", "/api/v1/admin/deploy/operations/{operationId}/submit"),
        new("POST", "/api/v1/admin/deploy/operations/{operationId}/rollback"),
        new("GET", "/api/v1/admin/services"),
        new("GET", "/api/v1/admin/services/{serviceName}/settings"),
        new("PUT", "/api/v1/admin/services/{serviceName}/protocols"),
        new("PUT", "/api/v1/admin/services/{serviceName}/mapserver"),
        new("PUT", "/api/v1/admin/services/{serviceName}/access-policy"),
        new("PUT", "/api/v1/admin/services/{serviceName}/timeinfo"),
        new("PUT", "/api/v1/admin/services/{serviceName}/layers/{layerId}/metadata"),

        // v1 admin secure connection endpoints
        new("GET", "/api/v1/admin/connections"),
        new("GET", "/api/v1/admin/connections/{id}"),
        new("POST", "/api/v1/admin/connections"),
        new("POST", "/api/v1/admin/connections/test"),
        new("PUT", "/api/v1/admin/connections/{id}"),
        new("DELETE", "/api/v1/admin/connections/{id}"),
        new("POST", "/api/v1/admin/connections/{id}/test"),
        new("POST", "/api/v1/admin/connections/encryption/validate"),
        new("POST", "/api/v1/admin/connections/encryption/rotate-key"),

        // v1 admin client-certificate trust profile endpoints (#1171)
        new("GET", "/api/v1/admin/security/client-certificates/profiles"),
        new("POST", "/api/v1/admin/security/client-certificates/profiles"),
        new("GET", "/api/v1/admin/security/client-certificates/profiles/{profileId}"),
        new("PUT", "/api/v1/admin/security/client-certificates/profiles/{profileId}"),
        new("DELETE", "/api/v1/admin/security/client-certificates/profiles/{profileId}"),
        new("GET", "/api/v1/admin/security/client-certificates/profiles/{profileId}/mappings"),
        new("POST", "/api/v1/admin/security/client-certificates/profiles/{profileId}/mappings"),
        new("PUT", "/api/v1/admin/security/client-certificates/profiles/{profileId}/mappings/{mappingId}"),
        new("DELETE", "/api/v1/admin/security/client-certificates/profiles/{profileId}/mappings/{mappingId}"),
        new("GET", "/api/v1/admin/security/client-certificates/profiles/{profileId}/revocations"),
        new("POST", "/api/v1/admin/security/client-certificates/profiles/{profileId}/revocations"),
        new("DELETE", "/api/v1/admin/security/client-certificates/profiles/{profileId}/revocations/{revocationId}"),
        new("POST", "/api/v1/admin/security/client-certificates/validate"),

        // v1 admin license management endpoints (#511)
        new("GET", "/api/v1/admin/license"),
        new("POST", "/api/v1/admin/license"),
        new("GET", "/api/v1/admin/license/entitlements"),

        // v1 platform admin endpoints (#513)
        new("GET", "/api/v1/admin/license/status"),
        new("GET", "/api/v1/admin/license/features"),
        new("POST", "/api/v1/admin/license/upload"),
        new("GET", "/api/v1/admin/identity/providers"),
        new("GET", "/api/v1/admin/identity/providers/{providerType}/test"),
        new("GET", "/api/v1/admin/cache/status"),
        new("POST", "/api/v1/admin/cache/invalidate"),
        new("GET", "/api/v1/admin/geocoding/providers"),
        new("GET", "/api/v1/admin/features"),

        // v1 admin compliance endpoints (#352)
        new("GET", "/api/v1/admin/compliance/dashboard"),
        new("GET", "/api/v1/admin/compliance/report"),
        new("POST", "/api/v1/admin/compliance/residency/evaluate"),
        new("POST", "/api/v1/admin/compliance/encryption/rotate-key"),

        // v1 admin OIDC provider endpoints (#511)
        new("GET", "/api/v1/admin/oidc/providers"),
        new("POST", "/api/v1/admin/oidc/providers"),
        new("GET", "/api/v1/admin/oidc/providers/{id}"),
        new("PUT", "/api/v1/admin/oidc/providers/{id}"),
        new("DELETE", "/api/v1/admin/oidc/providers/{id}"),
        new("POST", "/api/v1/admin/oidc/providers/{id}/test"),

        // v1 admin user management endpoints (#511)
        new("GET", "/api/v1/admin/users"),
        new("GET", "/api/v1/admin/users/{id}"),
        new("PUT", "/api/v1/admin/users/{id}/roles"),
        new("DELETE", "/api/v1/admin/users/{id}"),
        new("GET", "/api/v1/admin/users/{id}/effective-permissions"),

        // v1 admin role management endpoints (#511)
        new("GET", "/api/v1/admin/roles"),
        new("POST", "/api/v1/admin/roles"),
        new("GET", "/api/v1/admin/roles/{id}"),
        new("PUT", "/api/v1/admin/roles/{id}"),
        new("DELETE", "/api/v1/admin/roles/{id}"),
        new("GET", "/api/v1/admin/roles/{id}/permissions"),
        new("PUT", "/api/v1/admin/roles/{id}/permissions"),

        // v1 console metadata v2 content + RBAC baseline (#1162)
        new("GET", "/api/v1/console/session"),
        new("GET", "/api/v1/console/content"),
        new("POST", "/api/v1/console/content"),
        new("GET", "/api/v1/console/content/search"),
        new("GET", "/api/v1/console/content/{id}"),
        new("PUT", "/api/v1/console/content/{id}"),
        new("PATCH", "/api/v1/console/content/{id}"),
        new("DELETE", "/api/v1/console/content/{id}"),
        new("GET", "/api/v1/console/content/{id}/provenance"),
        new("POST", "/api/v1/console/actions/check"),
        // v1 Console Share access public-link + embed API (#1215)
        new("GET", "/api/v1/console/content/{id}/share"),
        new("PUT", "/api/v1/console/content/{id}/share/access"),
        new("GET", "/api/v1/console/content/{id}/share/dependencies"),
        new("GET", "/api/v1/console/content/{id}/share/link"),
        new("POST", "/api/v1/console/content/{id}/share/link"),
        new("DELETE", "/api/v1/console/content/{id}/share/link/{tokenId}"),
        new("PUT", "/api/v1/console/content/{id}/share/embed"),
        new("POST", "/api/v1/console/content/{id}/share/embed"),
        new("GET", "/api/v1/console/share/content/{id}"),
        new("GET", "/api/v1/console/share/link/{token}"),
        new("POST", "/api/v1/console/share/embed/{token}/redeem"),
        new("POST", "/api/v1/admin/packages/validate"),
        new("POST", "/api/v1/admin/packages/preview"),
        new("GET", "/api/v1/console/workflow-node-registry"),
        new("GET", "/api/v1/console/workflow-node-registry/{nodeTypeId}"),
        new("GET", "/api/v1/console/workflow-packages"),
        new("POST", "/api/v1/console/workflow-packages"),
        new("GET", "/api/v1/console/workflow-packages/{packageId}"),
        new("PUT", "/api/v1/console/workflow-packages/{packageId}"),
        new("GET", "/api/v1/console/workflow-packages/{packageId}/versions"),
        new("POST", "/api/v1/console/workflow-packages/{packageId}/versions"),
        new("GET", "/api/v1/console/workflow-packages/{packageId}/versions/{packageVersion}"),
        new("POST", "/api/v1/console/workflow-packages/{packageId}/versions/{packageVersion}/validate"),
        new("POST", "/api/v1/console/workflow-packages/{packageId}/versions/{packageVersion}/dry-run"),
        new("POST", "/api/v1/console/workflow-packages/{packageId}/versions/{packageVersion}/publish"),
        new("GET", "/api/v1/console/workflow-publications"),
        new("POST", "/api/v1/console/workflow-publications/{publicationId}/runs"),

        // v1 Studio package lifecycle endpoints (#1180)
        new("GET", "/api/v1/studio/package-families"),
        new("POST", "/api/v1/studio/package-drafts"),
        new("GET", "/api/v1/studio/package-drafts/{draftId}"),
        new("PUT", "/api/v1/studio/package-drafts/{draftId}"),
        new("DELETE", "/api/v1/studio/package-drafts/{draftId}"),
        new("POST", "/api/v1/studio/package-drafts/{draftId}/validate"),
        new("POST", "/api/v1/studio/package-drafts/{draftId}/preview-plan"),
        new("POST", "/api/v1/studio/package-drafts/{draftId}/content-versions"),
        new("GET", "/api/v1/studio/content-items/{itemId}/versions"),
        new("GET", "/api/v1/studio/content-items/{itemId}/versions/{versionId}"),
        new("POST", "/api/v1/studio/content-items/{itemId}/version-comparisons"),
        new("POST", "/api/v1/studio/content-items/{itemId}/versions/{versionId}/publish-requests"),
        new("POST", "/api/v1/studio/content-items/{itemId}/versions/{versionId}/reopen"),
        new("POST", "/api/v1/studio/content-items/{itemId}/rollback-requests"),

        // v1 content publication registry for Studio-generated artifacts (#1183)
        new("POST", "/api/v1/console/publications"),
        new("GET", "/api/v1/console/publications/{publicationId}"),
        new("GET", "/api/v1/console/publications/{publicationId}/versions/{versionSelector}"),
        new("POST", "/api/v1/console/publications/{publicationId}/republish"),
        new("POST", "/api/v1/console/publications/{publicationId}/rollback"),
        new("PATCH", "/api/v1/console/publications/{publicationId}/policy"),
        new("GET", "/api/v1/published/{*routeSlug}"),

        // v1 admin metadata resource CRUD endpoints removed in #1035 cutover.
        // (Layer-style/fields/filter/validation endpoints below still serve v1 layer ids.)
        new("GET", "/api/v1/admin/metadata/layers/{layerId}/style"),
        new("PUT", "/api/v1/admin/metadata/layers/{layerId}/style"),
        new("GET", "/api/v1/admin/metadata/layers/{layerId}/fields"),
        new("PUT", "/api/v1/admin/metadata/layers/{layerId}/fields"),
        new("GET", "/api/v1/admin/metadata/layers/{layerId}/filter"),
        new("PUT", "/api/v1/admin/metadata/layers/{layerId}/filter"),
        new("GET", "/api/v1/admin/metadata/layers/{layerId}/validation"),
        new("POST", "/api/v1/admin/metadata/layers/{layerId}/style/import-sld"),
        new("GET", "/api/v1/admin/metadata/layers/{layerId}/style/export-sld"),
        new("POST", "/api/v1/admin/metadata/layers/{layerId}/suggest-style"),
        // v1 gitops watch endpoints removed in #1035 cutover.
        new("GET", "/api/v1/admin/alerts/zones"),
        new("GET", "/api/v1/admin/alerts/zones/{zoneId}"),
        new("POST", "/api/v1/admin/alerts/zones"),
        new("PUT", "/api/v1/admin/alerts/zones/{zoneId}"),
        new("DELETE", "/api/v1/admin/alerts/zones/{zoneId}"),
        new("GET", "/api/v1/admin/alerts/rules"),
        new("GET", "/api/v1/admin/alerts/rules/{ruleId}"),
        new("POST", "/api/v1/admin/alerts/rules"),
        new("POST", "/api/v1/admin/alerts/rules/test"),
        new("PUT", "/api/v1/admin/alerts/rules/{ruleId}"),
        new("PUT", "/api/v1/admin/alerts/rules/{ruleId}/enabled"),
        new("GET", "/api/v1/admin/alerts/rules/{ruleId}/health"),
        new("DELETE", "/api/v1/admin/alerts/rules/{ruleId}"),

        // v1 admin import endpoints (primary)
        new("GET", "/api/v1/admin/import/formats"),
        new("POST", "/api/v1/admin/import/formats"),
        new("PUT", "/api/v1/admin/import/formats"),
        new("DELETE", "/api/v1/admin/import/formats"),
        new("PATCH", "/api/v1/admin/import/formats"),
        new("POST", "/api/v1/admin/import/preview"),
        new("GET", "/api/v1/admin/import/preview"),
        new("PUT", "/api/v1/admin/import/preview"),
        new("DELETE", "/api/v1/admin/import/preview"),
        new("PATCH", "/api/v1/admin/import/preview"),
        new("POST", "/api/v1/admin/import/preview-url"),
        new("GET", "/api/v1/admin/import/preview-url"),
        new("PUT", "/api/v1/admin/import/preview-url"),
        new("DELETE", "/api/v1/admin/import/preview-url"),
        new("PATCH", "/api/v1/admin/import/preview-url"),
        new("POST", "/api/v1/admin/import/upload"),
        new("GET", "/api/v1/admin/import/upload"),
        new("PUT", "/api/v1/admin/import/upload"),
        new("DELETE", "/api/v1/admin/import/upload"),
        new("PATCH", "/api/v1/admin/import/upload"),
        new("POST", "/api/v1/admin/import/upload-url"),
        new("GET", "/api/v1/admin/import/upload-url"),
        new("PUT", "/api/v1/admin/import/upload-url"),
        new("DELETE", "/api/v1/admin/import/upload-url"),
        new("PATCH", "/api/v1/admin/import/upload-url"),
        new("GET", "/api/v1/admin/import/uploads/{uploadId}/progress"),
        new("POST", "/api/v1/admin/import/uploads/{uploadId}/progress"),
        new("PUT", "/api/v1/admin/import/uploads/{uploadId}/progress"),
        new("DELETE", "/api/v1/admin/import/uploads/{uploadId}/progress"),
        new("PATCH", "/api/v1/admin/import/uploads/{uploadId}/progress"),
        new("POST", "/api/v1/admin/import/uploads/{uploadId}/cancel"),
        new("GET", "/api/v1/admin/import/uploads/{uploadId}/cancel"),
        new("PUT", "/api/v1/admin/import/uploads/{uploadId}/cancel"),
        new("DELETE", "/api/v1/admin/import/uploads/{uploadId}/cancel"),
        new("PATCH", "/api/v1/admin/import/uploads/{uploadId}/cancel"),
        new("GET", "/api/v1/admin/import/uploads"),
        new("POST", "/api/v1/admin/import/uploads"),
        new("PUT", "/api/v1/admin/import/uploads"),
        new("DELETE", "/api/v1/admin/import/uploads"),
        new("PATCH", "/api/v1/admin/import/uploads"),
        new("GET", "/api/v1/admin/import/jobs/{jobId}"),
        new("POST", "/api/v1/admin/import/jobs/{jobId}"),
        new("PUT", "/api/v1/admin/import/jobs/{jobId}"),
        new("DELETE", "/api/v1/admin/import/jobs/{jobId}"),
        new("PATCH", "/api/v1/admin/import/jobs/{jobId}"),
        new("POST", "/api/v1/admin/import/jobs/{jobId}/cancel"),
        new("GET", "/api/v1/admin/import/jobs/{jobId}/cancel"),
        new("PUT", "/api/v1/admin/import/jobs/{jobId}/cancel"),
        new("DELETE", "/api/v1/admin/import/jobs/{jobId}/cancel"),
        new("PATCH", "/api/v1/admin/import/jobs/{jobId}/cancel"),
        new("GET", "/api/v1/admin/import/jobs"),
        new("POST", "/api/v1/admin/import/jobs"),
        new("PUT", "/api/v1/admin/import/jobs"),
        new("DELETE", "/api/v1/admin/import/jobs"),
        new("PATCH", "/api/v1/admin/import/jobs"),
        new("GET", "/api/v1/admin/import/limits"),
        new("POST", "/api/v1/admin/import/limits"),
        new("PUT", "/api/v1/admin/import/limits"),
        new("DELETE", "/api/v1/admin/import/limits"),
        new("PATCH", "/api/v1/admin/import/limits"),
        new("POST", "/api/v1/admin/import/scan"),

        // v1 admin ArcGIS migration evidence endpoints (#1025 slice 6)
        new("GET", "/api/v1/admin/import/arcgis/migrations"),
        new("GET", "/api/v1/admin/import/arcgis/migrations/{runId}/manifest"),
        new("GET", "/api/v1/admin/import/arcgis/migrations/{runId}/parity"),

        // v1 admin import endpoints (Geoservices)
        new("POST", "/api/v1/admin/import/geoservices/discover"),
        new("POST", "/api/v1/admin/import/geoservices/start"),
        new("GET", "/api/v1/admin/import/geoservices/jobs/{jobId}"),
        new("POST", "/api/v1/admin/import/geoservices/jobs/{jobId}/cancel"),
        new("GET", "/api/v1/admin/import/geoservices/jobs"),

        // v1 admin import endpoints (Raster)
        new("POST", "/api/v1/admin/import/raster"),
        new("GET", "/api/v1/admin/import/raster/formats"),

        // v1 admin migration performance evidence endpoints (#1033 slice 5)
        new("GET", "/api/v1/admin/migration/performance-evidence/latest"),
        new("GET", "/api/v1/admin/migration/performance-evidence/history"),
        new("GET", "/api/v1/admin/migration/performance-evidence/{evidenceId}"),

        // v1 admin import endpoints (GeoServer)
        new("POST", "/api/v1/admin/import/geoserver/discover"),
        new("POST", "/api/v1/admin/import/geoserver/start"),
        new("GET", "/api/v1/admin/import/geoserver/jobs/{jobId}"),
        new("POST", "/api/v1/admin/import/geoserver/jobs/{jobId}/cancel"),
        new("GET", "/api/v1/admin/import/geoserver/jobs"),

        // v1 admin import endpoints (OGC API Features) — #1029 slice 2
        new("POST", "/api/v1/admin/import/ogc-api-features/collection"),
        // v1 admin import endpoints (OGC WFS)
        new("POST", "/api/v1/admin/import/ogc-wfs/start"),
        // v1 admin import endpoints (OGC Coverages - GeoTIFF/COG, issue #1030 slice 2)
        new("POST", "/api/v1/admin/import/ogc/coverages/import"),

        // v1 admin import endpoints (legacy OGC WCS, issue #1030 slice 3)
        new("POST", "/api/v1/admin/import/ogc-wcs/import"),

        // v1 admin GeoServer migration run orchestration endpoints (#1015 slice 5)
        new("GET", "/api/v1/admin/migration/runs"),
        new("GET", "/api/v1/admin/migration/runs/{runId}"),
        new("GET", "/api/v1/admin/migration/runs/{runId}/evidence-pack"),
        new("POST", "/api/v1/admin/migration/runs/{runId}/cancel"),

        // v1 admin import endpoints (OGC WMTS tile cache export #1016 slice 4)
        new("POST", "/api/v1/admin/import/ogc-tiles/export"),

        // v1 admin operational monitoring endpoints (#512)
        new("GET", "/api/v1/admin/operations/cache/health"),
        new("GET", "/api/v1/admin/operations/cache/statistics"),
        new("GET", "/api/v1/admin/operations/cache/redis"),
        new("POST", "/api/v1/admin/operations/cache/invalidate"),
        new("GET", "/api/v1/admin/operations/streaming/subscribers"),
        new("GET", "/api/v1/admin/operations/streaming/alerts"),
        new("DELETE", "/api/v1/admin/operations/streaming/subscribers/{subscriberId}"),

        // v1 feature-change streaming endpoints (#501)
        new("GET", "/api/v1/streaming/features"),
        new("GET", "/api/v1/streaming/features/capabilities"),
        new("GET", "/api/v1/admin/streaming/features/sessions"),
        new("DELETE", "/api/v1/admin/streaming/features/sessions/{sessionId}"),

        new("GET", "/api/v1/admin/operations/geocoding/providers"),
        new("GET", "/api/v1/admin/operations/geocoding/configuration"),

        // v1 admin operations progress endpoints
        new("GET", "/api/v1/admin/operations/{operationId}"),
        new("POST", "/api/v1/admin/operations/{operationId}/cancel"),
        new("GET", "/api/v1/admin/operations/active"),
        new("GET", "/api/v1/admin/operations/type/{operationType}"),
        new("GET", "/api/v1/admin/feature-events/replay"),

        // Console durable job observability endpoints (#1170)
        new("GET", "/api/v1/admin/jobs"),
        new("GET", "/api/v1/admin/jobs/{jobId}"),
        new("GET", "/api/v1/admin/jobs/{jobId}/logs"),
        new("GET", "/api/v1/admin/jobs/{jobId}/artifacts"),
        new("GET", "/api/v1/admin/jobs/{jobId}/actions"),
        new("POST", "/api/v1/admin/jobs/{jobId}/cancel"),
        new("POST", "/api/v1/admin/jobs/{jobId}/retry"),

        // Console Share export jobs and traffic endpoints (#1216)
        new("GET", "/api/v1/admin/share/exports"),
        new("POST", "/api/v1/admin/share/exports"),
        new("GET", "/api/v1/admin/share/exports/{exportId}"),
        new("PUT", "/api/v1/admin/share/exports/{exportId}"),
        new("DELETE", "/api/v1/admin/share/exports/{exportId}"),
        new("POST", "/api/v1/admin/share/exports/{exportId}/trigger"),
        new("POST", "/api/v1/admin/share/exports/{exportId}/pause"),
        new("POST", "/api/v1/admin/share/exports/{exportId}/resume"),
        new("GET", "/api/v1/admin/share/exports/{exportId}/runs"),
        new("GET", "/api/v1/admin/share/exports/{exportId}/runs/{runId}"),
        new("GET", "/api/v1/admin/share/traffic"),
        new("GET", "/api/v1/admin/share/traffic/series"),
        new("GET", "/api/v1/admin/services/{serviceName}/layers/{layerId}/share/traffic"),
        new("GET", "/api/v1/admin/services/{serviceName}/layers/{layerId}/share/traffic/series"),

        // Mobile runtime auth and diagnostics endpoints (#924)
        new("POST", "/api/mobile/exceptions"),

        // FieldCollection mobile sync endpoints (#894)
        new("GET", "/api/v1/fieldcollection/generation"),
        new("GET", "/api/v1/fieldcollection/sync-cursor"),
        new("POST", "/api/v1/fieldcollection/sync-cursor"),
        new("GET", "/api/v1/fieldcollection/changes"),
        new("POST", "/api/v1/fieldcollection/changes"),

        // Forms package lifecycle, offline policy, and submissions (#1184)
        new("GET", "/api/v1/admin/forms/packages"),
        new("POST", "/api/v1/admin/forms/packages"),
        new("GET", "/api/v1/admin/forms/packages/{formId}"),
        new("GET", "/api/v1/admin/forms/packages/{formId}/versions"),
        new("GET", "/api/v1/admin/forms/packages/{formId}/versions/{packageVersion}"),
        new("PUT", "/api/v1/admin/forms/packages/{formId}/versions/{packageVersion}"),
        new("POST", "/api/v1/admin/forms/packages/{formId}/versions/{packageVersion}/validate"),
        new("POST", "/api/v1/admin/forms/packages/{formId}/versions/{packageVersion}/publish"),
        new("POST", "/api/v1/admin/forms/packages/{formId}/versions/{packageVersion}/reopen"),
        new("GET", "/api/v1/forms/packages/{formId}"),
        new("GET", "/api/v1/forms/packages/{formId}/versions/{packageVersion}"),
        new("GET", "/api/v1/forms/packages/{formId}/offline-policy"),
        new("POST", "/api/v1/forms/packages/{formId}/submissions"),

        new("POST", "/api/v1/admin/tile-operations/jobs"),
        new("GET", "/api/v1/admin/tile-operations/jobs/{jobId}"),
        new("GET", "/api/v1/admin/tile-operations/jobs"),
        new("POST", "/api/v1/admin/tile-operations/jobs/{jobId}/cancel"),
        new("POST", "/api/v1/admin/tile-operations/jobs/{jobId}/retry"),

        new("GET", "/api/v1/admin/observability/errors"),
        new("GET", "/api/v1/admin/observability/telemetry"),
        new("GET", "/api/v1/admin/observability/migrations"),
        // Console Operate event viewer (#1168) — alerts, audit, unified events, logs, investigations.
        new("GET", "/api/v1/admin/observability/alerts"),
        new("GET", "/api/v1/admin/observability/alerts/{eventId}"),
        new("POST", "/api/v1/admin/observability/alerts/{eventId}/acknowledge"),
        new("POST", "/api/v1/admin/observability/alerts/{eventId}/suppress"),
        new("POST", "/api/v1/admin/observability/alerts/{eventId}/resolve"),
        new("GET", "/api/v1/admin/observability/audit"),
        new("GET", "/api/v1/admin/observability/events"),
        new("GET", "/api/v1/admin/observability/logs"),
        new("GET", "/api/v1/admin/investigations"),
        new("POST", "/api/v1/admin/investigations"),
        new("GET", "/api/v1/admin/investigations/{investigationId}"),
        new("PATCH", "/api/v1/admin/investigations/{investigationId}"),
        new("POST", "/api/v1/admin/investigations/{investigationId}/pins"),
        new("DELETE", "/api/v1/admin/investigations/{investigationId}/pins/{pinId}"),
        new("POST", "/api/v1/admin/investigations/{investigationId}/links"),
        new("DELETE", "/api/v1/admin/investigations/{investigationId}/links/{linkId}"),
        new("POST", "/api/v1/admin/dev/fixtures/operate-observability/{profile}"),

        new("GET", "/api/v1/admin/performance/database/query-cache/statistics"),
        new("GET", "/api/v1/admin/performance/enhanced/database/query-performance"),
        new("GET", "/api/v1/admin/performance/enhanced/database/slow-queries"),
        new("GET", "/api/v1/admin/performance/enhanced/resources/tracking"),
        new("GET", "/api/v1/admin/performance/enhanced/resources/potential-leaks"),
        new("POST", "/api/v1/admin/performance/enhanced/resources/scan-leaks"),
        new("GET", "/api/v1/admin/performance/enhanced/exceptions/statistics"),
        new("GET", "/api/v1/admin/performance/enhanced/exceptions/recent"),
        new("GET", "/api/v1/admin/performance/enhanced/cache/statistics"),
        new("GET", "/api/v1/admin/performance/enhanced/cache/effectiveness"),
        new("DELETE", "/api/v1/admin/performance/enhanced/cache/invalidate"),
        new("GET", "/api/v1/admin/performance/enhanced/summary"),

        new("GET", "/api/v1/metrics/health"),
        new("GET", "/api/v1/metrics/performance"),
        new("GET", "/api/v1/metrics/database"),
        new("GET", "/api/v1/metrics/cache"),
        new("GET", "/api/v1/metrics/memory"),
        new("GET", "/api/v1/metrics/streaming"),

        new("POST", "/csp-violation-report"),

        new("GET", "/rest/services"),
        new("GET", "/rest/info"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer/findAddressCandidates"),
        new("POST", "/rest/services/{locatorName}/GeocodeServer/findAddressCandidates"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer/reverseGeocode"),
        new("POST", "/rest/services/{locatorName}/GeocodeServer/reverseGeocode"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer/suggest"),
        new("POST", "/rest/services/{locatorName}/GeocodeServer/suggest"),
        new("GET", "/rest/services/{locatorName}/GeocodeServer/geocodeAddresses"),
        new("POST", "/rest/services/{locatorName}/GeocodeServer/geocodeAddresses"),
        new("GET", "/rest/services/GeocodeServer"),
        new("GET", "/rest/services/GeocodeServer/findAddressCandidates"),
        new("GET", "/rest/services/GeocodeServer/reverseGeocode"),
        new("GET", "/rest/services/GeocodeServer/suggest"),
        new("GET", "/rest/services/GeocodeServer/geocodeAddresses"),

        new("GET", "/rest/services/{serviceId}/FeatureServer"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/query"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/query"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/query"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/applyEdits"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/applyEdits"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/addFeatures"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/updateFeatures"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/deleteFeatures"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryRelatedRecords"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryRelatedRecords"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/generateRenderer"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/createReplica"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/extractChanges"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/synchronizeReplica"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/unRegisterReplica"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/append"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/append"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/calculate"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/calculate"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/queryDomains"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/relationships"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/validateSQL"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/getEstimates"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/getEstimates"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryTopFeatures"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryTopFeatures"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryDateBins"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryDateBins"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/temporalExtent"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryBins"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryBins"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryH3"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryH3"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryClusters"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/spatialJoin"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryBufferAggregate"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryDensity"),
        new("POST", "/api/v1/cloud-demo/reset"),
        new("GET", "/api/v1/realtime/incidents/sse"),
        new("GET", "/tiles/{layerId}/{z}/{x}/{y}.mvt"),
        new("GET", "/tiles/{layerId}/h3/{z}/{x}/{y}.mvt"),
        new("GET", "/tiles/{layerId}/tile.json"),
        new("GET", "/terrain/{datasetId}/tile.json"),
        new("GET", "/terrain/{datasetId}/{z}/{x}/{y}.png"),

        // Saved-map collaboration session seam.
        new("POST", "/api/v1/saved-maps/{mapId}/collaboration/sessions/join"),
        new("POST", "/api/v1/saved-maps/{mapId}/collaboration/feature-locks/claim"),
        new("POST", "/api/v1/saved-maps/{mapId}/collaboration/feature-locks/renew"),
        new("POST", "/api/v1/saved-maps/{mapId}/collaboration/feature-locks/release"),

        // Public SDK-compatible scene discovery (#923).
        new("GET", "/api/scenes"),
        new("GET", "/api/scenes/{sceneId}"),
        new("GET", "/api/scenes/{sceneId}/resolve"),

        // Hosted 3D Tiles scene serving (#837).
        new("POST", "/scenes/{sceneId}/access-envelope"),
        new("GET", "/scenes/{sceneId}/exports/openusd/stage.usda"),
        new("GET", "/scenes/{sceneId}/tileset.json"),
        new("HEAD", "/scenes/{sceneId}/tileset.json"),
        new("GET", "/scenes/{sceneId}/{*assetPath}"),
        new("HEAD", "/scenes/{sceneId}/{*assetPath}"),

        // Scene dataset registry admin endpoints (#844).
        new("GET", "/api/v1/admin/scenes"),
        new("POST", "/api/v1/admin/scenes"),
        new("GET", "/api/v1/admin/scenes/{id}"),
        new("PUT", "/api/v1/admin/scenes/{id}"),
        new("DELETE", "/api/v1/admin/scenes/{id}"),
        new("GET", "/api/v1/admin/scenes/{id}/resolve"),

        // 3D Tiles generation admin endpoint (#842).
        new("POST", "/api/v1/admin/scenes/generate"),

        new("GET", "/elevation/{datasetId}/value"),
        new("GET", "/elevation/{datasetId}/profile"),

        // Scene analysis on the elevation surface (#1204).
        new("POST", "/elevation/{datasetId}/sun-shadow"),
        new("POST", "/elevation/{datasetId}/slice"),
        // 3D visibility analysis on the elevation surface (#1203).
        new("POST", "/elevation/{datasetId}/line-of-sight"),
        new("POST", "/elevation/{datasetId}/viewshed"),

        new("GET", "/api/styles/{layerId}.json"),

        // Durable PMTiles publish range proxy (#845).
        new("GET", "/api/v1/tiles/pmtiles/{*artifactId}"),
        new("HEAD", "/api/v1/tiles/pmtiles/{*artifactId}"),

        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryAttachments"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/queryAttachments"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/attachments"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/addAttachment"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/updateAttachment"),
        new("POST", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/deleteAttachments"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/{layerId}/{featureId}/attachments/{attachmentId}"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/replicas"),
        new("GET", "/rest/services/{serviceId}/FeatureServer/replicas/{replicaId}"),

        new("GET", "/rest/services/{serviceId}/MapServer"),
        new("GET", "/rest/services/{serviceId}/MapServer/{layerId}"),
        new("GET", "/rest/services/{serviceId}/MapServer/export"),
        new("POST", "/rest/services/{serviceId}/MapServer/export"),
        new("GET", "/rest/services/{serviceId}/MapServer/generateKml"),
        new("POST", "/rest/services/{serviceId}/MapServer/generateKml"),
        new("GET", "/rest/services/{serviceId}/MapServer/identify"),
        new("POST", "/rest/services/{serviceId}/MapServer/identify"),
        new("GET", "/rest/services/{serviceId}/MapServer/legend"),
        new("GET", "/rest/services/{serviceId}/MapServer/find"),
        new("POST", "/rest/services/{serviceId}/MapServer/find"),
        new("GET", "/rest/services/{serviceId}/MapServer/{layerId}/query"),
        new("POST", "/rest/services/{serviceId}/MapServer/{layerId}/query"),
        new("GET", "/rest/services/{serviceId}/MapServer/query"),
        new("POST", "/rest/services/{serviceId}/MapServer/query"),
        new("GET", "/rest/services/{serviceId}/MapServer/tile/{z}/{y}/{x}"),
        new("GET", "/rest/services/{serviceId}/MapServer/WMTS"),
        new("GET", "/rest/services/{serviceId}/MapServer/WMTS/{**restPath}"),
        new("GET", "/rest/services/{serviceId}/MapServer/WMS"),
        new("GET", "/ogc/services/{serviceId}/wmts"),
        new("GET", "/ogc/services/{serviceId}/wms"),
        new("GET", "/ogc/services/{serviceId}/wcs"),

        new("GET", "/rest/services/{id}/ImageServer"),
        new("GET", "/rest/services/{id}/ImageServer/WCS"),
        new("GET", "/rest/services/{id}/ImageServer/exportImage"),
        new("POST", "/rest/services/{id}/ImageServer/exportImage"),
        new("GET", "/rest/services/{id}/ImageServer/identify"),
        new("POST", "/rest/services/{id}/ImageServer/identify"),
        new("GET", "/rest/services/{id}/ImageServer/tile/{level}/{row}/{col}"),
        new("GET", "/rest/services/{id}/ImageServer/query"),
        new("POST", "/rest/services/{id}/ImageServer/query"),
        new("GET", "/rest/services/{id}/ImageServer/computeStatisticsHistograms"),
        new("POST", "/rest/services/{id}/ImageServer/computeStatisticsHistograms"),
        new("GET", "/rest/services/{id}/ImageServer/legend"),
        new("GET", "/rest/services/{id}/ImageServer/computeClassStatistics"),
        new("POST", "/rest/services/{id}/ImageServer/computeClassStatistics"),

        new("GET", "/rest/services/{serviceId}/ImageServer"),
        new("GET", "/rest/services/{serviceId}/ImageServer/exportImage"),
        new("POST", "/rest/services/{serviceId}/ImageServer/exportImage"),
        new("GET", "/rest/services/{serviceId}/ImageServer/identify"),
        new("POST", "/rest/services/{serviceId}/ImageServer/identify"),
        new("GET", "/rest/services/{serviceId}/ImageServer/tile/{level}/{row}/{col}"),
        new("GET", "/rest/services/{serviceId}/ImageServer/query"),
        new("POST", "/rest/services/{serviceId}/ImageServer/query"),
        new("GET", "/rest/services/{serviceId}/ImageServer/computeStatisticsHistograms"),
        new("POST", "/rest/services/{serviceId}/ImageServer/computeStatisticsHistograms"),
        new("GET", "/rest/services/{serviceId}/ImageServer/legend"),
        new("GET", "/rest/services/{serviceId}/ImageServer/computeClassStatistics"),
        new("POST", "/rest/services/{serviceId}/ImageServer/computeClassStatistics"),

        new("GET", "/odata"),
        new("GET", "/odata/$metadata"),
        new("GET", "/odata/Layers"),
        new("GET", "/odata/Layers({layerId})"),
        new("GET", "/odata/Layers/$count"),
        new("GET", "/odata/Layers({layerId})/Features"),
        new("GET", "/odata/Layers({layerId})/Features/$count"),
        new("POST", "/odata/Layers({layerId})/Features"),
        new("GET", "/odata/Layers({layerId})/Features({objectId})"),
        new("PATCH", "/odata/Layers({layerId})/Features({objectId})"),
        new("PUT", "/odata/Layers({layerId})/Features({objectId})"),
        new("DELETE", "/odata/Layers({layerId})/Features({objectId})"),
        new("GET", "/odata/Features"),
        new("GET", "/odata/Features/$count"),
        new("POST", "/odata/Features"),
        new("GET", "/odata/Features(LayerId={layerId},ObjectId={objectId})"),
        new("GET", "/odata/Features(LayerId={layerId},ObjectId={objectId})/$ref"),
        new("GET", "/odata/Features(LayerId={layerId},ObjectId={objectId})/$value"),
        new("PATCH", "/odata/Features(LayerId={layerId},ObjectId={objectId})"),
        new("PUT", "/odata/Features(LayerId={layerId},ObjectId={objectId})"),
        new("DELETE", "/odata/Features(LayerId={layerId},ObjectId={objectId})"),
        new("GET", "/odata/Features({layerId})"),
        new("GET", "/odata/Features({layerId})/$count"),
        new("GET", "/odata/Features({layerId},{objectId})"),
        new("PATCH", "/odata/Features({layerId},{objectId})"),
        new("PUT", "/odata/Features({layerId},{objectId})"),
        new("DELETE", "/odata/Features({layerId},{objectId})"),
        new("POST", "/odata/$batch"),
        new("GET", "/odata/Features({layerId})/$apply"),
        new("GET", "/odata/Features({layerId})/$search"),

        new("GET", "/ogc/features"),
        new("GET", "/ogc/features/conformance"),
        new("GET", "/openapi.json"),
        new("GET", "/ogc/features/collections"),
        new("GET", "/ogc/features/collections/{collectionId}"),
        new("GET", "/ogc/features/collections/{collectionId}/queryables"),
        new("GET", "/ogc/features/collections/{collectionId}/items"),
        new("GET", "/ogc/features/api"),
        new("GET", "/ogc/features/schemas/honua-ogcapi-features.xsd"),
        new("GET", "/ogc/features/collections/{collectionId}/items/{featureId}"),
        new("POST", "/ogc/features/collections/{collectionId}/items"),
        new("POST", "/ogc/features/collections/{collectionId}/items/batch"),
        new("PUT", "/ogc/features/collections/{collectionId}/items/{featureId}"),
        new("PATCH", "/ogc/features/collections/{collectionId}/items/{featureId}"),
        new("DELETE", "/ogc/features/collections/{collectionId}/items/{featureId}"),
        new("GET", "/ogc/features/collections/{collectionId}/h3"),
        new("POST", "/ogc/features/collections/{collectionId}/clusters"),
        new("POST", "/ogc/features/collections/{collectionId}/spatial-join"),
        new("POST", "/ogc/features/collections/{collectionId}/buffer-aggregate"),
        new("POST", "/ogc/features/collections/{collectionId}/density"),

        // OGC API Records
        new("GET", "/ogc/records"),
        new("GET", "/ogc/records/conformance"),
        new("GET", "/ogc/records/collections"),
        new("GET", "/ogc/records/collections/{collectionId}"),
        new("GET", "/ogc/records/collections/{collectionId}/items"),
        new("GET", "/ogc/records/collections/{collectionId}/items/{recordId}"),

        // OGC API Coverages
        new("GET", "/ogc/coverages"),
        new("GET", "/ogc/coverages/conformance"),
        new("GET", "/ogc/coverages/api"),
        new("GET", "/ogc/coverages/openapi.json"),
        new("GET", "/ogc/coverages/collections"),
        new("GET", "/ogc/coverages/collections/{collectionId}"),
        new("GET", "/ogc/coverages/collections/{collectionId}/schema"),
        new("GET", "/ogc/coverages/collections/{collectionId}/coverage"),

        // OGC API Processes
        new("GET", "/ogc/processes"),
        new("GET", "/ogc/processes/conformance"),
        new("GET", "/ogc/processes/openapi.json"),
        new("GET", "/ogc/processes/processes"),
        new("GET", "/ogc/processes/processes/{processId}"),
        new("POST", "/ogc/processes/processes/{processId}/execution"),
        new("GET", "/ogc/processes/jobs"),
        new("GET", "/ogc/processes/jobs/{jobId}"),
        new("GET", "/ogc/processes/jobs/{jobId}/results"),
        new("DELETE", "/ogc/processes/jobs/{jobId}"),

        new("GET", "/ogc/tiles"),
        new("GET", "/ogc/tiles/conformance"),
        new("GET", "/ogc/tiles/openapi.json"),
        new("GET", "/ogc/tiles/collections"),
        new("GET", "/ogc/tiles/collections/{collectionId}"),
        new("GET", "/ogc/tiles/collections/{collectionId}/tiles"),
        new("GET", "/ogc/tiles/collections/{collectionId}/tiles/{tileMatrixSetId}"),
        new("GET", "/ogc/tiles/collections/{collectionId}/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}"),
        new("GET", "/ogc/tiles/tiles"),
        new("GET", "/ogc/tiles/tiles/{tileMatrixSetId}"),
        new("GET", "/ogc/tiles/tiles/{tileMatrixSetId}/{tileMatrix}/{tileRow}/{tileCol}"),
        new("GET", "/ogc/tiles/tileMatrixSets"),
        new("GET", "/ogc/tiles/tileMatrixSets/{tileMatrixSetId}"),

        new("GET", "/rest/services/Utilities/Geometry/GeometryServer"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/buffer"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/buffer"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/simplify"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/simplify"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/project"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/project"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/intersect"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/intersect"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/union"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/union"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/clip"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/clip"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/difference"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/difference"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/areasAndLengths"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/areasAndLengths"),
        new("GET", "/rest/services/Utilities/Geometry/GeometryServer/lengths"),
        new("POST", "/rest/services/Utilities/Geometry/GeometryServer/lengths"),

        // NAServer minimal mobile routing compatibility (#366)
        new("POST", "/rest/services/{serviceId}/NAServer/Route/solve"),
        new("POST", "/rest/services/{serviceId}/NAServer/ServiceArea/solveServiceArea"),
        new("POST", "/rest/services/{serviceId}/NAServer/ClosestFacility/solveClosestFacility"),

        new("GET", "/ogc/maps"),
        new("GET", "/ogc/maps/conformance"),
        new("GET", "/ogc/maps/openapi.json"),
        new("GET", "/ogc/maps/collections/{collectionId}/map"),
        new("GET", "/ogc/maps/collections/{collectionId}/styles/{styleId}/map"),
        new("GET", "/ogc/maps/collections/{collectionId}/map/tiles"),
        new("GET", "/ogc/maps/collections/{collectionId}/map/tiles/{tileMatrixSetId}"),
        new("GET", "/ogc/maps/map"),

        // Static Map
        new("GET", "/static/{serviceId}/{center}/{dimensions}.{format}"),
        new("GET", "/static/{serviceId}/bbox/{bbox}/{dimensions}.{format}"),

        // GPServer generic adapter (#723)
        new("GET", "/rest/services/{serviceId}/GPServer"),
        new("POST", "/rest/services/{serviceId}/GPServer"),
        new("GET", "/rest/services/{serviceId}/GPServer/{taskName}"),
        new("POST", "/rest/services/{serviceId}/GPServer/{taskName}"),
        // Synchronous execute (POST + GET per Esri GP contract) shipped with the
        // GP/ETL GPServer adapter (#1228) but was missing from the registry on trunk.
        new("POST", "/rest/services/{serviceId}/GPServer/{taskName}/execute"),
        new("GET", "/rest/services/{serviceId}/GPServer/{taskName}/execute"),
        new("POST", "/rest/services/{serviceId}/GPServer/{taskName}/submitJob"),
        new("GET", "/rest/services/{serviceId}/GPServer/{taskName}/submitJob"),
        new("GET", "/rest/services/{serviceId}/GPServer/{taskName}/jobs/{jobId}"),
        new("GET", "/rest/services/{serviceId}/GPServer/{taskName}/jobs/{jobId}/results/{paramName}"),
        new("GET", "/rest/services/{serviceId}/GPServer/{taskName}/jobs/{jobId}/cancel"),
        new("POST", "/rest/services/{serviceId}/GPServer/{taskName}/jobs/{jobId}/cancel"),

        // PrintingTools (Export Web Map Task)
        // Note: task metadata (service info) is served via GET /execute?f=json
        // matching ArcGIS Server behavior. A standalone base URL endpoint cannot be
        // registered due to ASP.NET Core treating decoded %20 as segment separators.
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task"),
        new("POST", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/execute"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/execute"),
        new("POST", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/submitJob"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/submitJob"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/jobs/{jobId}"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Export Web Map Task/jobs/{jobId}/results/Output_File"),
        new("GET", "/rest/services/Utilities/PrintingTools/GPServer/Get Layout Templates Info Task/execute"),

        // WFS 2.0
        new("GET", "/wfs"),
        new("POST", "/wfs"),

        // Data export
        new("GET", "/api/v1/admin/services/{serviceName}/layers/{layerId}/export"),

        // COG admin endpoints (#519)
        new("POST", "/api/v1/admin/cloud-rasters"),
        new("GET", "/api/v1/admin/cloud-rasters"),
        new("GET", "/api/v1/admin/cloud-rasters/{id}"),
        new("DELETE", "/api/v1/admin/cloud-rasters/{id}"),
        new("POST", "/api/v1/admin/cloud-rasters/{id}/refresh"),

        // Zarr admin endpoints (#1009)
        new("POST", "/api/v1/admin/zarr-stores"),
        new("GET", "/api/v1/admin/zarr-stores"),
        new("GET", "/api/v1/admin/zarr-stores/{id}"),
        new("DELETE", "/api/v1/admin/zarr-stores/{id}"),
        new("POST", "/api/v1/admin/zarr-stores/{id}/refresh"),

        // STAC (SpatioTemporal Asset Catalog)
        new("GET", "/stac"),
        new("GET", "/stac/conformance"),
        new("GET", "/stac/openapi.json"),
        new("GET", "/stac/collections"),
        new("GET", "/stac/collections/{collectionId}"),
        new("GET", "/stac/collections/{collectionId}/items"),
        new("GET", "/stac/collections/{collectionId}/items/{itemId}"),
        new("GET", "/stac/search"),
        new("POST", "/stac/search"),

        // Hosted samples
        new("GET", "/samples/stac-ops"),

        // MCP operator surface (#728) — JSON-RPC dispatch over a single route.
        new("POST", "/v1/grounding/spec/mutate"),
        new("POST", "/v1/grounding/spec/summarize"),
        new("POST", "/mcp"),

        // Spec plan / apply engine (#789).
        new("POST", "/v1/spec/validate"),
        new("POST", "/v1/spec/plan"),
        new("POST", "/v1/spec/apply"),
        new("POST", "/v1/spec/cancel"),
        new("GET", "/v1/spec/artifact/{hash}"),

        // Analysis content HTTP surface (#1182).
        new("POST", "/api/v1/analysis/content/items"),
        new("GET", "/api/v1/analysis/content/items/{itemId}"),
        new("GET", "/api/v1/analysis/content/items/{itemId}/versions/latest"),
        new("GET", "/api/v1/analysis/content/items/{itemId}/versions/{contentVersion}"),
        new("POST", "/api/v1/analysis/content/items/{itemId}/versions"),
        new("POST", "/api/v1/analysis/content/items/{itemId}/versions/{contentVersion}/preview"),
        new("POST", "/api/v1/analysis/content/items/{itemId}/versions/{contentVersion}/runs"),
        new("POST", "/api/v1/analysis/content/items/{itemId}/versions/{contentVersion}/reruns"),
        new("GET", "/api/v1/analysis/artifacts/{artifactId}"),
        new("GET", "/api/v1/analysis/jobs/{jobId}/logs"),
        new("GET", "/api/v1/analysis/jobs/{jobId}/failure"),

        // Analysis report HTTP surface (#801).
        new("GET", "/api/v1/analysis/reports/{jobId}"),
        new("GET", "/api/v1/analysis/reports/{jobId}/render"),

        // Cloud-optimized HDF5 / NetCDF4 multidimensional coverage admin endpoints (#1010).
        new("POST", "/api/v1/admin/multidim-coverages"),
        new("GET", "/api/v1/admin/multidim-coverages"),
        new("GET", "/api/v1/admin/multidim-coverages/{id}"),
        new("DELETE", "/api/v1/admin/multidim-coverages/{id}"),
        new("POST", "/api/v1/admin/multidim-coverages/{id}/refresh"),
    ];
}

/// <summary>
/// Describes an HTTP endpoint by method and route pattern.
/// </summary>
/// <param name="Method">HTTP method (GET, POST, etc.).</param>
/// <param name="Path">Route pattern starting with '/'.</param>
public sealed record EndpointDefinition(string Method, string Path);
