// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

namespace Honua.Core.Features.Geoprocessing.Domain;

/// <summary>
/// Audit trail recording the lineage of a geoprocessing result, including source data,
/// processes applied, assumptions made, and clarifications resolved.
/// </summary>
public sealed record ProvenanceRecord
{
    /// <summary>
    /// Source datasets consumed by the workflow.
    /// </summary>
    public required IReadOnlyList<ProvenanceSource> Sources { get; init; }

    /// <summary>
    /// Identifiers of geoprocessing operations applied during execution.
    /// </summary>
    public required IReadOnlyList<string> ProcessDefinitions { get; init; }

    /// <summary>
    /// Assumptions made during workflow compilation.
    /// </summary>
    public IReadOnlyList<string> Assumptions { get; init; } = [];

    /// <summary>
    /// Question identifiers for clarifications that were asked.
    /// </summary>
    public IReadOnlyList<string> ClarificationsAsked { get; init; } = [];

    /// <summary>
    /// Question identifiers for clarifications that were answered.
    /// </summary>
    public IReadOnlyList<string> ClarificationsAnswered { get; init; } = [];

    /// <summary>
    /// When the workflow execution completed.
    /// </summary>
    public DateTimeOffset? ExecutedAt { get; init; }

    /// <summary>
    /// Identifiers of artifacts generated by the workflow.
    /// </summary>
    public IReadOnlyList<string> GeneratedArtifactIds { get; init; } = [];
}

/// <summary>
/// A source dataset or resource consumed during geoprocessing.
/// </summary>
public sealed record ProvenanceSource
{
    /// <summary>
    /// Identifier of the source dataset or resource.
    /// </summary>
    public required string SourceId { get; init; }

    /// <summary>
    /// Version of the source at the time of access.
    /// </summary>
    public string? Version { get; init; }

    /// <summary>
    /// Human-readable description of the source.
    /// </summary>
    public string? Description { get; init; }
}
