#!/usr/bin/env bash
# capture-bench-environment.sh
#
# Captures runtime, OS, hardware, and database versions for benchmark
# environment disclosure. Outputs a markdown block suitable for pasting
# into a benchmark results disclosure section.
#
# Usage:
#   ./scripts/capture-bench-environment.sh
#
# Optional environment variables:
#   HONUA_BENCH_DB_URL  - PostgreSQL connection string for PostGIS version query
#   PGHOST / PGPORT / PGUSER / PGDATABASE - standard libpq variables

set -euo pipefail

echo "## Benchmark Environment Disclosure"
echo ""
echo "| Detail | Value |"
echo "| --- | --- |"

# Git commit SHA
if command -v git &>/dev/null && git rev-parse --is-inside-work-tree &>/dev/null 2>&1; then
  sha=$(git rev-parse --short HEAD 2>/dev/null || echo "unknown")
  echo "| Git SHA | \`${sha}\` |"
fi

# .NET runtime
if command -v dotnet &>/dev/null; then
  dotnet_version=$(dotnet --version 2>/dev/null || echo "unknown")
  rid=$(dotnet --info 2>/dev/null | grep 'RID:' | awk '{print $2}' || echo "unknown")
  echo "| .NET SDK | ${dotnet_version} |"
  echo "| RID | ${rid} |"
else
  echo "| .NET SDK | not found |"
fi

# OS version
if [[ -f /etc/os-release ]]; then
  os_name=$(. /etc/os-release && echo "${PRETTY_NAME:-$NAME $VERSION}")
  echo "| OS | ${os_name} |"
elif command -v uname &>/dev/null; then
  echo "| OS | $(uname -srm) |"
fi

# CPU
if command -v lscpu &>/dev/null; then
  cpu_model=$(lscpu | grep 'Model name' | sed 's/Model name:[[:space:]]*//')
  cpu_cores=$(lscpu | grep 'Core(s) per socket' | awk '{print $NF}')
  cpu_threads=$(lscpu | grep '^CPU(s):' | awk '{print $2}')
  echo "| CPU | ${cpu_model} (${cpu_cores}C/${cpu_threads}T) |"
elif [[ -f /proc/cpuinfo ]]; then
  cpu_model=$(grep 'model name' /proc/cpuinfo | head -1 | sed 's/.*: //')
  cpu_count=$(grep -c '^processor' /proc/cpuinfo)
  echo "| CPU | ${cpu_model} (${cpu_count} logical) |"
fi

# Memory
if command -v free &>/dev/null; then
  mem_total=$(free -h | awk '/^Mem:/ {print $2}')
  echo "| Memory | ${mem_total} |"
fi

# PostgreSQL version
pg_version="not found"
if [[ -n "${HONUA_BENCH_DB_URL:-}" ]]; then
  pg_version=$(psql "${HONUA_BENCH_DB_URL}" -t -c "SELECT version();" 2>/dev/null | xargs || echo "not found")
elif command -v psql &>/dev/null; then
  pg_version=$(psql -t -c "SELECT version();" 2>/dev/null | xargs || echo "not found (set HONUA_BENCH_DB_URL)")
fi
echo "| PostgreSQL | ${pg_version} |"

# PostGIS version
postgis_version="not found"
if [[ -n "${HONUA_BENCH_DB_URL:-}" ]]; then
  postgis_version=$(psql "${HONUA_BENCH_DB_URL}" -t -c "SELECT PostGIS_Full_Version();" 2>/dev/null | xargs || echo "not found")
elif command -v psql &>/dev/null; then
  postgis_version=$(psql -t -c "SELECT PostGIS_Full_Version();" 2>/dev/null | xargs || echo "not found (set HONUA_BENCH_DB_URL)")
fi
echo "| PostGIS | ${postgis_version} |"

# Docker container image tags (if docker is available)
if command -v docker &>/dev/null; then
  postgres_image=$(docker ps --format '{{.Image}}' 2>/dev/null | grep -i 'postgis\|postgres' | head -1 || echo "")
  redis_image=$(docker ps --format '{{.Image}}' 2>/dev/null | grep -i 'redis' | head -1 || echo "")
  if [[ -n "${postgres_image}" ]]; then
    echo "| PostgreSQL image | \`${postgres_image}\` |"
  fi
  if [[ -n "${redis_image}" ]]; then
    echo "| Redis image | \`${redis_image}\` |"
  fi
fi

# Timestamp
echo "| Captured at | $(date -u '+%Y-%m-%d %H:%M:%S UTC') |"
echo ""
echo "_Generated by \`scripts/capture-bench-environment.sh\`_"
