#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: run-client-compat-smoke.sh [options]

Options:
  --base-url <url>       Base URL for the running Honua server.
  --service-id <id>      Service id to exercise. Default: test_service
  --layer-id <id>        Layer id to exercise. Default: 0
  --timestamp <value>    UTC timestamp segment for artifact layout.
  --output-root <path>   Override the artifact output root.
  --seed-source <path>   Seed snapshot used for this run.
  --profile <name>       Test profile: smoke (MVP 11-check) or full (CERT-* matrix). Default: full.
  --help                 Show this help message.
EOF
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_URL="http://localhost:5000"
SERVICE_ID="test_service"
LAYER_ID="0"
TIMESTAMP="$(date -u +'%Y%m%dT%H%M%SZ')"
SEED_SOURCE="tests/seed/client-compat-v1.sql"
OUTPUT_ROOT=""
PROFILE="full"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url)
      BASE_URL="${2:?missing value for --base-url}"
      shift 2
      ;;
    --service-id)
      SERVICE_ID="${2:?missing value for --service-id}"
      shift 2
      ;;
    --layer-id)
      LAYER_ID="${2:?missing value for --layer-id}"
      shift 2
      ;;
    --timestamp)
      TIMESTAMP="${2:?missing value for --timestamp}"
      shift 2
      ;;
    --output-root)
      OUTPUT_ROOT="${2:?missing value for --output-root}"
      shift 2
      ;;
    --seed-source)
      SEED_SOURCE="${2:?missing value for --seed-source}"
      shift 2
      ;;
    --profile)
      PROFILE="${2:?missing value for --profile}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if [[ "$PROFILE" != "smoke" && "$PROFILE" != "full" ]]; then
  echo "Invalid profile: $PROFILE (must be 'smoke' or 'full')" >&2
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required." >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required." >&2
  exit 1
fi

BASE_URL="${BASE_URL%/}"

if [[ -z "$OUTPUT_ROOT" ]]; then
  OUTPUT_ROOT="$ROOT_DIR/artifacts/client-compat/${SERVICE_ID}-${TIMESTAMP}"
fi

ARTIFACT_ROOT="$OUTPUT_ROOT"
PACK_DIR="$ARTIFACT_ROOT/pack"
METADATA_DIR="$ARTIFACT_ROOT/metadata"
SERVER_DIR="$ARTIFACT_ROOT/server"
LANES_DIR="$ARTIFACT_ROOT/lanes"
SERVER_VERSION="${GITHUB_SHA:-$(git -C "$ROOT_DIR" rev-parse HEAD 2>/dev/null || echo unknown)}"
GENERATED_AT="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

CERT_DIR="$ARTIFACT_ROOT/certification"
LAST_DURATION_MS="0"
LAST_BODY_PATH=""
LAST_HEADERS_PATH=""
LAST_STATUS=""

mkdir -p "$PACK_DIR" "$METADATA_DIR" "$SERVER_DIR" "$LANES_DIR"
if [[ "$PROFILE" == "full" ]]; then
  mkdir -p "$CERT_DIR"
fi

copy_required() {
  local source_rel="$1"
  local dest_path="$2"
  local source_path="$ROOT_DIR/$source_rel"

  if [[ ! -f "$source_path" ]]; then
    echo "Missing required pack source: $source_rel" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$dest_path")"
  cp "$source_path" "$dest_path"
}

prepare_pack() {
  mkdir -p \
    "$PACK_DIR/templates/desktop/arcgis-pro" \
    "$PACK_DIR/templates/desktop/qgis" \
    "$PACK_DIR/templates/bi/power-bi" \
    "$PACK_DIR/templates/bi/excel" \
    "$PACK_DIR/runbook"

  copy_required "docs/gis/client-templates/.env.example" "$PACK_DIR/templates/.env.example"
  copy_required "docs/gis/client-templates/arcgis-pro/Honua-Desktop-Smoke.aprx.template.md" "$PACK_DIR/templates/desktop/arcgis-pro/Honua-Desktop-Smoke.aprx.template.md"
  copy_required "docs/user/client-templates/qgis/Honua-Desktop-Smoke.qgs.template" "$PACK_DIR/templates/desktop/qgis/Honua-Desktop-Smoke.qgs.template"
  copy_required "docs/gis/client-templates/power-bi/Honua-OData-Smoke.pq.template" "$PACK_DIR/templates/bi/power-bi/Honua-OData-Smoke.pq.template"
  copy_required "docs/gis/client-templates/power-bi/Honua-OData-Smoke.pbix.template.md" "$PACK_DIR/templates/bi/power-bi/Honua-OData-Smoke.pbix.template.md"
  copy_required "docs/gis/client-templates/excel/Honua-OData-Smoke.pq.template" "$PACK_DIR/templates/bi/excel/Honua-OData-Smoke.pq.template"
  copy_required "docs/gis/client-templates/excel/Honua-OData-Smoke.xlsx.template.md" "$PACK_DIR/templates/bi/excel/Honua-OData-Smoke.xlsx.template.md"

  copy_required "docs/gis/CLIENT_TEMPLATE_RUNBOOK.md" "$PACK_DIR/runbook/CLIENT_TEMPLATE_RUNBOOK.md"
  copy_required "docs/gis/CROSS_CLIENT_CERTIFICATION_EVIDENCE.md" "$PACK_DIR/runbook/CROSS_CLIENT_CERTIFICATION_EVIDENCE.md"
  copy_required "docs/gis/CROSS_CLIENT_CERTIFICATION_MATRIX.md" "$PACK_DIR/runbook/CROSS_CLIENT_CERTIFICATION_MATRIX.md"
  copy_required "docs/gis/CLIENT_TEMPLATE_VERSION_MATRIX.md" "$PACK_DIR/runbook/CLIENT_TEMPLATE_VERSION_MATRIX.md"

  cat > "$PACK_DIR/README.md" <<EOF
# Client Compatibility Pack

This pack is generated by the Windows client compatibility certification workflow.

- Seed snapshot: \`$(basename "$SEED_SOURCE")\`
- Service id: \`$SERVICE_ID\`
- Layer id: \`$LAYER_ID\`
- Generated at: \`$GENERATED_AT\`

## Contents

- \`templates/\`: reusable ArcGIS Pro, QGIS, Power BI, and Excel template sources.
- \`runbook/\`: smoke-run procedure, evidence schema, certification matrix, and version ledger.

## Source Notes

The current repository stores client-template sources across both \`docs/gis\` and \`docs/user\`.
This workflow assembles them into one canonical pack so manual follow-through uses a single layout.
EOF
}

write_artifact_readme() {
  cat > "$ARTIFACT_ROOT/README.md" <<EOF
# Client Compatibility Evidence

- Service id: \`$SERVICE_ID\`
- Layer id: \`$LAYER_ID\`
- Base URL: \`$BASE_URL\`
- Seed snapshot: \`$SEED_SOURCE\`
- Server version: \`$SERVER_VERSION\`
- Generated at: \`$GENERATED_AT\`

## Layout

- \`overall-summary.json\` and \`overall-summary.md\`: aggregate lane verdicts.
- \`lanes/<lane>/\`: per-lane summaries and request/response transcripts.
- \`certification/\`: per-protocol \`.cert.json\` envelopes (\`full\` profile only).
- \`server/\`: captured Honua server logs.
- \`pack/\`: reusable client compatibility pack for manual Windows follow-through.
- \`metadata/\`: workflow provenance and the exact seed snapshot used for the run.
EOF
}

write_metadata() {
  jq -n \
    --arg generated_at "$GENERATED_AT" \
    --arg timestamp "$TIMESTAMP" \
    --arg base_url "$BASE_URL" \
    --arg service_id "$SERVICE_ID" \
    --arg layer_id "$LAYER_ID" \
    --arg seed_source "$SEED_SOURCE" \
    --arg server_version "$SERVER_VERSION" \
    --arg github_run_id "${GITHUB_RUN_ID:-}" \
    --arg github_workflow "${GITHUB_WORKFLOW:-}" \
    '{
      generated_at: $generated_at,
      timestamp: $timestamp,
      base_url: $base_url,
      service_id: $service_id,
      layer_id: $layer_id,
      seed_source: $seed_source,
      server_version: $server_version,
      github_run_id: (if $github_run_id == "" then null else $github_run_id end),
      github_workflow: (if $github_workflow == "" then null else $github_workflow end)
    }' > "$METADATA_DIR/workflow-context.json"

  copy_required "$SEED_SOURCE" "$METADATA_DIR/$(basename "$SEED_SOURCE")"
}

CURRENT_LANE=""
CURRENT_RESULTS_FILE=""

lane_dir() {
  printf '%s\n' "$LANES_DIR/$1"
}

init_lane() {
  CURRENT_LANE="$1"
  local lane_path
  lane_path="$(lane_dir "$CURRENT_LANE")"
  mkdir -p "$lane_path/transcripts"
  CURRENT_RESULTS_FILE="$lane_path/checks.tsv"
  : > "$CURRENT_RESULTS_FILE"
}

append_result() {
  local check_id="$1"
  local status="$2"
  local http_status="$3"
  local transcript_rel="$4"
  local note="$5"

  note="${note//$'\n'/ }"
  printf '%s\t%s\t%s\t%s\t%s\n' "$check_id" "$status" "$http_status" "$transcript_rel" "$note" >> "$CURRENT_RESULTS_FILE"
}

write_transcript() {
  local transcript_file="$1"
  local method="$2"
  local url="$3"
  local accept="$4"
  local http_status="$5"
  local note="$6"
  local headers_file="$7"
  local body_file="$8"

  {
    echo "# Request"
    echo "${method} ${url}"
    echo "Accept: ${accept}"
    echo
    echo "# Response"
    echo "HTTP ${http_status}"
    if [[ -n "$note" ]]; then
      echo "Note: ${note}"
    fi
    echo
    echo "## Headers"
    cat "$headers_file"
    echo
    echo "## Body"
    cat "$body_file"
  } > "$transcript_file"
}

request_json() {
  local check_id="$1"
  local url="$2"
  local expected_status="$3"
  local jq_expr="$4"
  local accept="${5:-application/json}"

  local lane_path headers_file body_file transcript_file transcript_rel http_status curl_exit status note
  lane_path="$(lane_dir "$CURRENT_LANE")"
  headers_file="$(mktemp)"
  body_file="$(mktemp)"
  transcript_file="$lane_path/transcripts/${check_id}.txt"
  transcript_rel="${transcript_file#$ARTIFACT_ROOT/}"
  http_status="0"
  curl_exit=0
  status="pass"
  note=""
  LAST_DURATION_MS="0"

  local curl_output time_total
  curl_output="$(curl -sS -o "$body_file" -D "$headers_file" -H "Accept: ${accept}" -w '%{http_code}\t%{time_total}' "$url")" || curl_exit=$?
  http_status="${curl_output%%$'\t'*}"
  time_total="${curl_output#*$'\t'}"
  LAST_DURATION_MS="$(awk "BEGIN {printf \"%.0f\", ${time_total:-0} * 1000}")"

  if [[ $curl_exit -ne 0 ]]; then
    status="fail"
    note="curl exited with code ${curl_exit}"
  elif [[ "$http_status" != "$expected_status" ]]; then
    status="fail"
    note="expected HTTP ${expected_status}, got ${http_status}"
  elif ! jq -e "$jq_expr" "$body_file" >/dev/null 2>&1; then
    status="fail"
    note="response failed jq assertion: ${jq_expr}"
  fi

  write_transcript "$transcript_file" "GET" "$url" "$accept" "$http_status" "$note" "$headers_file" "$body_file"
  append_result "$check_id" "$status" "$http_status" "$transcript_rel" "$note"

  rm -f "$LAST_BODY_PATH" 2>/dev/null || true
  LAST_BODY_PATH="$body_file"
  rm -f "$LAST_HEADERS_PATH" 2>/dev/null || true
  LAST_HEADERS_PATH="$headers_file"
  LAST_STATUS="$status"

  [[ "$status" == "pass" ]]
}

request_text() {
  local check_id="$1"
  local url="$2"
  local expected_status="$3"
  local required_text="$4"
  local accept="${5:-text/plain}"

  local lane_path headers_file body_file transcript_file transcript_rel http_status curl_exit status note
  lane_path="$(lane_dir "$CURRENT_LANE")"
  headers_file="$(mktemp)"
  body_file="$(mktemp)"
  transcript_file="$lane_path/transcripts/${check_id}.txt"
  transcript_rel="${transcript_file#$ARTIFACT_ROOT/}"
  http_status="0"
  curl_exit=0
  status="pass"
  note=""
  LAST_DURATION_MS="0"

  local curl_output time_total
  curl_output="$(curl -sS -o "$body_file" -D "$headers_file" -H "Accept: ${accept}" -w '%{http_code}\t%{time_total}' "$url")" || curl_exit=$?
  http_status="${curl_output%%$'\t'*}"
  time_total="${curl_output#*$'\t'}"
  LAST_DURATION_MS="$(awk "BEGIN {printf \"%.0f\", ${time_total:-0} * 1000}")"

  if [[ $curl_exit -ne 0 ]]; then
    status="fail"
    note="curl exited with code ${curl_exit}"
  elif [[ "$http_status" != "$expected_status" ]]; then
    status="fail"
    note="expected HTTP ${expected_status}, got ${http_status}"
  elif ! grep -Fq "$required_text" "$body_file"; then
    status="fail"
    note="response missing expected text: ${required_text}"
  fi

  write_transcript "$transcript_file" "GET" "$url" "$accept" "$http_status" "$note" "$headers_file" "$body_file"
  append_result "$check_id" "$status" "$http_status" "$transcript_rel" "$note"

  rm -f "$LAST_BODY_PATH" 2>/dev/null || true
  LAST_BODY_PATH="$body_file"
  rm -f "$headers_file"
  LAST_STATUS="$status"

  [[ "$status" == "pass" ]]
}

request_json_4xx() {
  local check_id="$1"
  local url="$2"
  local jq_expr="$3"
  local accept="${4:-application/json}"

  local lane_path headers_file body_file transcript_file transcript_rel http_status curl_exit status note
  lane_path="$(lane_dir "$CURRENT_LANE")"
  headers_file="$(mktemp)"
  body_file="$(mktemp)"
  transcript_file="$lane_path/transcripts/${check_id}.txt"
  transcript_rel="${transcript_file#$ARTIFACT_ROOT/}"
  http_status="0"
  curl_exit=0
  status="pass"
  note=""
  LAST_DURATION_MS="0"

  local curl_output time_total
  curl_output="$(curl -sS -o "$body_file" -D "$headers_file" -H "Accept: ${accept}" -w '%{http_code}\t%{time_total}' "$url")" || curl_exit=$?
  http_status="${curl_output%%$'\t'*}"
  time_total="${curl_output#*$'\t'}"
  LAST_DURATION_MS="$(awk "BEGIN {printf \"%.0f\", ${time_total:-0} * 1000}")"

  if [[ $curl_exit -ne 0 ]]; then
    status="fail"
    note="curl exited with code ${curl_exit}"
  elif [[ "${http_status:0:1}" != "4" ]]; then
    status="fail"
    note="expected HTTP 4xx, got ${http_status}"
  elif ! jq -e "$jq_expr" "$body_file" >/dev/null 2>&1; then
    status="fail"
    note="response failed jq assertion: ${jq_expr}"
  fi

  write_transcript "$transcript_file" "GET" "$url" "$accept" "$http_status" "$note" "$headers_file" "$body_file"
  append_result "$check_id" "$status" "$http_status" "$transcript_rel" "$note"

  rm -f "$LAST_BODY_PATH" 2>/dev/null || true
  LAST_BODY_PATH="$body_file"
  rm -f "$LAST_HEADERS_PATH" 2>/dev/null || true
  LAST_HEADERS_PATH="$headers_file"
  LAST_STATUS="$status"

  [[ "$status" == "pass" ]]
}

append_cert_result() {
  local protocol="$1" cert_id="$2" status="$3" duration_ms="$4" measured_count="$5" measured_delta="$6" notes="${7:-}" evidence_ref="${8:-}"
  printf '%s\t%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$cert_id" "$status" "$duration_ms" "$measured_count" "$measured_delta" "$notes" "$evidence_ref" \
    >> "$CERT_DIR/cert-results-${protocol}.tsv"
}

record_skip() {
  local protocol="$1" cert_id="$2" reason="$3"
  append_cert_result "$protocol" "$cert_id" "skip" "" "" "" "$reason" ""
}

record_na() {
  local protocol="$1" cert_id="$2" reason="$3"
  append_cert_result "$protocol" "$cert_id" "not-applicable" "" "" "" "$reason" ""
}

record_skip_with_lane() {
  local check_id="$1" protocol="$2" cert_id="$3" reason="$4"
  append_result "$check_id" "skip" "0" "" "$reason"
  record_skip "$protocol" "$cert_id" "$reason"
}

record_na_with_lane() {
  local check_id="$1" protocol="$2" cert_id="$3" reason="$4"
  append_result "$check_id" "not-applicable" "0" "" "$reason"
  record_na "$protocol" "$cert_id" "$reason"
}


finalize_lane() {
  local lane="$1"
  local title="$2"
  local lane_path summary_json summary_md
  lane_path="$(lane_dir "$lane")"
  summary_json="$lane_path/lane-summary.json"
  summary_md="$lane_path/lane-summary.md"

  jq -Rn \
    --arg lane "$lane" \
    --arg title "$title" \
    '
      [inputs | select(length > 0) | split("\t")] as $rows
      | {
          lane: $lane,
          title: $title,
          status: (if any($rows[]; .[1] == "fail") then "fail" else "pass" end),
          summary: {
            total: ($rows | length),
            passed: ($rows | map(select(.[1] == "pass")) | length),
            failed: ($rows | map(select(.[1] == "fail")) | length),
            skipped: ($rows | map(select(.[1] == "skip")) | length),
            not_applicable: ($rows | map(select(.[1] == "not-applicable")) | length)
          },
          checks: [
            $rows[]
            | {
                id: .[0],
                status: .[1],
                http_status: (.[2] | tonumber),
                transcript: .[3],
                note: (if (.[4] // "") == "" then null else .[4] end)
              }
          ]
        }
    ' < "$lane_path/checks.tsv" > "$summary_json"

  {
    echo "## ${title} Lane"
    echo
    echo "| Check | Status | HTTP | Transcript | Note |"
    echo "|---|---|---:|---|---|"
    while IFS=$'\t' read -r check_id status http_status transcript_rel note; do
      local uppercase_status
      uppercase_status="$(printf '%s' "$status" | tr '[:lower:]' '[:upper:]')"
      printf '| `%s` | %s | %s | `%s` | %s |\n' \
        "$check_id" \
        "$uppercase_status" \
        "$http_status" \
        "$transcript_rel" \
        "${note:-}"
    done < "$lane_path/checks.tsv"
  } > "$summary_md"
}

run_desktop_lane() {
  local lane_failed=0
  init_lane "desktop"

  request_json \
    "featureserver-service-metadata" \
    "${BASE_URL}/rest/services/${SERVICE_ID}/FeatureServer?f=json" \
    "200" \
    '(.layers | length) > 0 and (.layers[0].id == 0)' || lane_failed=1

  request_json \
    "featureserver-layer-metadata" \
    "${BASE_URL}/rest/services/${SERVICE_ID}/FeatureServer/${LAYER_ID}?f=json" \
    "200" \
    '.id == 0 and (.fields | length) > 0 and .geometryType == "esriGeometryPoint"' || lane_failed=1

  request_json \
    "featureserver-query-active-subset" \
    "${BASE_URL}/rest/services/${SERVICE_ID}/FeatureServer/${LAYER_ID}/query?where=status%20%3D%20%27active%27&resultRecordCount=3&returnGeometry=true&f=json" \
    "200" \
    '(.features | length) == 3' || lane_failed=1

  request_json \
    "mapserver-service-metadata" \
    "${BASE_URL}/rest/services/${SERVICE_ID}/MapServer?f=json" \
    "200" \
    '(.layers | length) > 0' || lane_failed=1

  request_json \
    "ogc-collections" \
    "${BASE_URL}/ogc/features/collections" \
    "200" \
    '(.collections | length) > 0' || lane_failed=1

  request_json \
    "ogc-items-first-page" \
    "${BASE_URL}/ogc/features/collections/${LAYER_ID}/items?limit=3" \
    "200" \
    '(.features | length) == 3' || lane_failed=1

  finalize_lane "desktop" "Desktop"
  return "$lane_failed"
}

run_bi_lane() {
  local lane_failed=0
  init_lane "bi"

  request_json \
    "odata-service-document" \
    "${BASE_URL}/odata" \
    "200" \
    '(.value | map(.name) | index("Layers")) != null and (.value | map(.name) | index("Features")) != null' || lane_failed=1

  request_text \
    "odata-metadata" \
    "${BASE_URL}/odata/\$metadata" \
    "200" \
    'EntityType Name="Feature"' \
    'application/xml' || lane_failed=1

  request_json \
    "odata-layer-filter" \
    "${BASE_URL}/odata/Layers?\$filter=Name%20eq%20%27Test%20Layer%27" \
    "200" \
    '(.value | length) == 1' || lane_failed=1

  request_json \
    "odata-features-first-page" \
    "${BASE_URL}/odata/Features(${LAYER_ID})?\$top=3" \
    "200" \
    '(.value | length) == 3 and (."@odata.nextLink" != null)' || lane_failed=1

  request_json \
    "odata-features-second-page" \
    "${BASE_URL}/odata/Features(${LAYER_ID})?\$top=3&\$skip=3" \
    "200" \
    '(.value | length) == 3 and (.value[0].ObjectId > 3)' || lane_failed=1

  finalize_lane "bi" "BI"
  return "$lane_failed"
}

# ---------------------------------------------------------------------------
# Full profile: per-protocol check functions
# ---------------------------------------------------------------------------

run_full_featureserver() {
  local failed=0
  local proto="featureserver"
  local fs_base="${BASE_URL}/rest/services/${SERVICE_ID}/FeatureServer"

  # CERT-CONN-01: HTTP connection (GET; server routes do not support HEAD)
  request_json "fs-conn-check" "${fs_base}?f=json" "200" "true" || failed=1
  append_cert_result "$proto" "CERT-CONN-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-CONN-02, AUTH-01, AUTH-02 (skip)
  record_skip_with_lane "fs-conn-tls" "$proto" "CERT-CONN-02" "HTTP-only CI environment; TLS not available"
  record_skip_with_lane "fs-auth-unauth" "$proto" "CERT-AUTH-01" "No auth configured in CI seed"
  record_skip_with_lane "fs-auth-valid" "$proto" "CERT-AUTH-02" "No auth configured in CI seed"

  # CERT-DISC-01: List services
  request_json \
    "featureserver-service-metadata" \
    "${fs_base}?f=json" "200" \
    "(.layers | length) > 0 and (.layers[0].id == ${LAYER_ID})" || failed=1
  local disc01_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    disc01_count=$(jq -r '.layers | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-DISC-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$disc01_count" "" ""

  # CERT-DISC-02: Layer metadata
  request_json \
    "featureserver-layer-metadata" \
    "${fs_base}/${LAYER_ID}?f=json" "200" \
    ".id == ${LAYER_ID} and (.fields | length) > 0 and .geometryType == \"esriGeometryPoint\"" || failed=1
  append_cert_result "$proto" "CERT-DISC-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-SCHM-01: Typed fields array
  request_json \
    "fs-schema-fields" \
    "${fs_base}/${LAYER_ID}?f=json" "200" \
    '(.fields | length) > 0 and .fields[0].type != null' || failed=1
  append_cert_result "$proto" "CERT-SCHM-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-SCHM-02: Geometry type
  request_json \
    "fs-geometry-type" \
    "${fs_base}/${LAYER_ID}?f=json" "200" \
    '.geometryType == "esriGeometryPoint"' || failed=1
  append_cert_result "$proto" "CERT-SCHM-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-QFLT-01: Attribute filter (verify returned features have matching status)
  request_json \
    "featureserver-query-active-subset" \
    "${fs_base}/${LAYER_ID}/query?where=status%20%3D%20%27active%27&resultRecordCount=3&returnGeometry=true&f=json" \
    "200" \
    '(.features | length) == 3 and ([.features[].attributes.status] | all(. == "active"))' || failed=1
  local qflt01_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    qflt01_count=$(jq -r '.features | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-QFLT-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$qflt01_count" "" ""

  # CERT-QFLT-02: Spatial bbox filter (bbox contains exactly alpha/beta/gamma)
  request_json \
    "fs-bbox-query" \
    "${fs_base}/${LAYER_ID}/query?geometry=-122.50%2C37.70%2C-122.45%2C37.74&geometryType=esriGeometryEnvelope&inSR=4326&spatialRel=esriSpatialRelIntersects&returnGeometry=true&f=json" \
    "200" \
    '(.features | length) == 3 and ([.features[].geometry | (.x >= -122.50 and .x <= -122.45 and .y >= 37.70 and .y <= 37.74)] | all)' || failed=1
  local qflt02_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    qflt02_count=$(jq -r '.features | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-QFLT-02" "$LAST_STATUS" "$LAST_DURATION_MS" "$qflt02_count" "" ""

  # CERT-PAGE-01: First page
  request_json \
    "fs-page-first" \
    "${fs_base}/${LAYER_ID}/query?where=1%3D1&resultRecordCount=3&resultOffset=0&returnGeometry=true&f=json" \
    "200" \
    '(.features | length) == 3' || failed=1
  local page01_count=""
  local page01_oids=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    page01_count=$(jq -r '.features | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
    page01_oids=$(jq -c '[.features[].attributes.OBJECTID]' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-PAGE-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$page01_count" "" ""

  # CERT-PAGE-02: Second page (non-overlapping features)
  local fs_page02_jq='(.features | length) == 3'
  if [[ -n "$page01_oids" && "$page01_oids" != "null" ]]; then
    fs_page02_jq="((.features | length) == 3) and (([.features[].attributes.OBJECTID] - ${page01_oids}) | length) == (.features | length)"
  fi
  request_json \
    "fs-page-second" \
    "${fs_base}/${LAYER_ID}/query?where=1%3D1&resultRecordCount=3&resultOffset=3&returnGeometry=true&f=json" \
    "200" \
    "$fs_page02_jq" || failed=1
  append_cert_result "$proto" "CERT-PAGE-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-GEOM-01: Coordinate fidelity (alpha at -122.4900, 37.7100)
  request_json \
    "fs-geom-coords" \
    "${fs_base}/${LAYER_ID}/query?where=name%20%3D%20%27alpha%27&returnGeometry=true&outFields=*&f=json" \
    "200" \
    '.features[0].geometry | ((.x - (-122.49)) | fabs) < 0.000001 and ((.y - 37.71) | fabs) < 0.000001' || failed=1
  local geom01_delta=""
  if [[ "$LAST_STATUS" == "pass" && -f "$LAST_BODY_PATH" ]]; then
    geom01_delta=$(jq -r '.features[0].geometry | [((.x - (-122.49)) | fabs), ((.y - 37.71) | fabs)] | max' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-GEOM-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "$geom01_delta" ""

  # CERT-GEOM-02: Output CRS
  request_json \
    "fs-geom-crs" \
    "${fs_base}/${LAYER_ID}/query?where=name%20%3D%20%27alpha%27&returnGeometry=true&outSR=4326&f=json" \
    "200" \
    '.spatialReference.wkid == 4326' || failed=1
  append_cert_result "$proto" "CERT-GEOM-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-ERRH-01: Invalid endpoint returns structured error
  request_json_4xx \
    "fs-error-invalid" \
    "${fs_base}/99999?f=json" \
    '.error != null' || failed=1
  append_cert_result "$proto" "CERT-ERRH-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-ERRH-02: Malformed where returns structured error
  request_json_4xx \
    "fs-error-malformed" \
    "${fs_base}/${LAYER_ID}/query?where=INVALID%21%21%21&f=json" \
    '.error != null' || failed=1
  append_cert_result "$proto" "CERT-ERRH-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-RNDR-01, RNDR-02 (skip — visual/manual)
  record_skip_with_lane "fs-rndr-render" "$proto" "CERT-RNDR-01" "Visual rendering requires manual client"
  record_skip_with_lane "fs-rndr-refresh" "$proto" "CERT-RNDR-02" "Data refresh requires manual client"

  return "$failed"
}

run_full_ogc_features() {
  local failed=0
  local proto="ogc-features"
  local ogc_base="${BASE_URL}/ogc/features"

  # CERT-CONN-01 (GET; server routes do not support HEAD)
  request_json "ogc-conn-check" "$ogc_base" "200" "true" || failed=1
  append_cert_result "$proto" "CERT-CONN-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # Common skips
  record_skip_with_lane "ogc-conn-tls" "$proto" "CERT-CONN-02" "HTTP-only CI environment; TLS not available"
  record_skip_with_lane "ogc-auth-unauth" "$proto" "CERT-AUTH-01" "No auth configured in CI seed"
  record_skip_with_lane "ogc-auth-valid" "$proto" "CERT-AUTH-02" "No auth configured in CI seed"

  # CERT-DISC-01: List collections
  request_json \
    "ogc-collections" \
    "${ogc_base}/collections" "200" \
    '(.collections | length) > 0' || failed=1
  local disc01_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    disc01_count=$(jq -r '.collections | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-DISC-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$disc01_count" "" ""

  # CERT-DISC-02: Collection detail (id, itemType, and links required per OGC API Features)
  request_json \
    "ogc-collection-detail" \
    "${ogc_base}/collections/${LAYER_ID}" "200" \
    ".id == \"${LAYER_ID}\" and .itemType == \"feature\" and (.links | length) > 0" || failed=1
  append_cert_result "$proto" "CERT-DISC-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-SCHM-01: Properties have keys
  request_json \
    "ogc-schema-properties" \
    "${ogc_base}/collections/${LAYER_ID}/items?limit=1" "200" \
    '(.features[0].properties | keys | length) > 0' || failed=1
  append_cert_result "$proto" "CERT-SCHM-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-SCHM-02: Geometry type is Point
  request_json \
    "ogc-geometry-type" \
    "${ogc_base}/collections/${LAYER_ID}/items?limit=1" "200" \
    '.features[0].geometry.type == "Point"' || failed=1
  append_cert_result "$proto" "CERT-SCHM-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-QFLT-01: Attribute filter via CQL2 (verify returned features have matching status)
  request_json \
    "ogc-attribute-filter" \
    "${ogc_base}/collections/${LAYER_ID}/items?filter=status%20%3D%20%27active%27&limit=3" "200" \
    '(.features | length) > 0 and (.features | length) <= 3 and ([.features[].properties.status] | all(. == "active"))' || failed=1
  local qflt01_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    qflt01_count=$(jq -r '.features | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-QFLT-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$qflt01_count" "" ""

  # CERT-QFLT-02: Spatial bbox filter (bbox contains exactly alpha/beta/gamma)
  request_json \
    "ogc-bbox-query" \
    "${ogc_base}/collections/${LAYER_ID}/items?bbox=-122.50%2C37.70%2C-122.45%2C37.74&limit=10" "200" \
    '(.features | length) == 3 and ([.features[].geometry.coordinates | (.[0] >= -122.50 and .[0] <= -122.45 and .[1] >= 37.70 and .[1] <= 37.74)] | all)' || failed=1
  local qflt02_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    qflt02_count=$(jq -r '.features | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-QFLT-02" "$LAST_STATUS" "$LAST_DURATION_MS" "$qflt02_count" "" ""

  # CERT-PAGE-01: First page
  request_json \
    "ogc-items-first-page" \
    "${ogc_base}/collections/${LAYER_ID}/items?limit=3" "200" \
    '(.features | length) == 3' || failed=1
  local page01_count=""
  local page01_fids=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    page01_count=$(jq -r '.features | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
    page01_fids=$(jq -c '[.features[].id]' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-PAGE-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$page01_count" "" ""

  # CERT-PAGE-02: Second page offset (non-overlapping features)
  local ogc_page02_jq='(.features | length) == 3'
  if [[ -n "$page01_fids" && "$page01_fids" != "null" ]]; then
    ogc_page02_jq="((.features | length) == 3) and (([.features[].id] - ${page01_fids}) | length) == (.features | length)"
  fi
  request_json \
    "ogc-page-second" \
    "${ogc_base}/collections/${LAYER_ID}/items?limit=3&offset=3" "200" \
    "$ogc_page02_jq" || failed=1
  append_cert_result "$proto" "CERT-PAGE-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-GEOM-01: Coordinate fidelity (GeoJSON: coordinates[0]=x, coordinates[1]=y)
  request_json \
    "ogc-geom-coords" \
    "${ogc_base}/collections/${LAYER_ID}/items?filter=name%20%3D%20%27alpha%27&limit=1" "200" \
    '.features[0].geometry.coordinates | (((.[0]) - (-122.49)) | fabs) < 0.000001 and (((.[1]) - 37.71) | fabs) < 0.000001' || failed=1
  local geom01_delta=""
  if [[ "$LAST_STATUS" == "pass" && -f "$LAST_BODY_PATH" ]]; then
    geom01_delta=$(jq -r '.features[0].geometry.coordinates | [((.[0] - (-122.49)) | fabs), ((.[1] - 37.71) | fabs)] | max' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-GEOM-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "$geom01_delta" ""

  # CERT-GEOM-02: Output CRS matches requested CRS (explicit EPSG:4326, north/east axis order)
  # EPSG:4326 swaps axes to lat/lon: alpha at (-122.49, 37.71) becomes [37.71, -122.49]
  request_json \
    "ogc-geom-crs" \
    "${ogc_base}/collections/${LAYER_ID}/items?filter=name%20%3D%20%27alpha%27&limit=1&crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FEPSG%2F0%2F4326" "200" \
    '.features[0].geometry.coordinates | (((.[0]) - 37.71) | fabs) < 0.000001 and (((.[1]) - (-122.49)) | fabs) < 0.000001' || failed=1
  local geom02_status="$LAST_STATUS"
  if [[ "$geom02_status" == "pass" && -f "$LAST_HEADERS_PATH" ]]; then
    if ! grep -qi 'content-crs:.*EPSG/0/4326' "$LAST_HEADERS_PATH"; then
      geom02_status="fail"
      # Propagate header failure to lane check result so lane/overall summaries stay consistent
      awk -F'\t' -v OFS='\t' '$1 == "ogc-geom-crs" { $2 = "fail"; $5 = "Content-Crs header missing or does not match EPSG:4326" }1' \
        "$CURRENT_RESULTS_FILE" > "${CURRENT_RESULTS_FILE}.tmp" && mv "${CURRENT_RESULTS_FILE}.tmp" "$CURRENT_RESULTS_FILE"
      failed=1
    fi
  fi
  append_cert_result "$proto" "CERT-GEOM-02" "$geom02_status" "$LAST_DURATION_MS" "" "" ""

  # CERT-ERRH-01: Invalid collection
  request_json_4xx \
    "ogc-error-invalid" \
    "${ogc_base}/collections/nonexistent_99999" \
    'type == "object" and length > 0' || failed=1
  append_cert_result "$proto" "CERT-ERRH-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-ERRH-02: Malformed filter
  request_json_4xx \
    "ogc-error-malformed" \
    "${ogc_base}/collections/${LAYER_ID}/items?filter=INVALID%21%21%21" \
    'type == "object" and length > 0' || failed=1
  append_cert_result "$proto" "CERT-ERRH-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-RNDR-01, RNDR-02 (skip)
  record_skip_with_lane "ogc-rndr-render" "$proto" "CERT-RNDR-01" "Visual rendering requires manual client"
  record_skip_with_lane "ogc-rndr-refresh" "$proto" "CERT-RNDR-02" "Data refresh requires manual client"

  return "$failed"
}

run_full_mapserver() {
  local failed=0
  local proto="mapserver"
  local ms_base="${BASE_URL}/rest/services/${SERVICE_ID}/MapServer"

  # CERT-CONN-01 (GET; server routes do not support HEAD)
  request_json "ms-conn-check" "${ms_base}?f=json" "200" "true" || failed=1
  append_cert_result "$proto" "CERT-CONN-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # Common skips
  record_skip_with_lane "ms-conn-tls" "$proto" "CERT-CONN-02" "HTTP-only CI environment; TLS not available"
  record_skip_with_lane "ms-auth-unauth" "$proto" "CERT-AUTH-01" "No auth configured in CI seed"
  record_skip_with_lane "ms-auth-valid" "$proto" "CERT-AUTH-02" "No auth configured in CI seed"

  # CERT-DISC-01: MapServer service listing
  request_json \
    "mapserver-service-metadata" \
    "${ms_base}?f=json" "200" \
    '(.layers | length) > 0' || failed=1
  local disc01_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    disc01_count=$(jq -r '.layers | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-DISC-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$disc01_count" "" ""

  # CERT-DISC-02: Layer metadata
  request_json \
    "ms-layer-metadata" \
    "${ms_base}/${LAYER_ID}?f=json" "200" \
    '.id != null and (.fields | length) > 0' || failed=1
  append_cert_result "$proto" "CERT-DISC-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-SCHM-01: Typed fields
  request_json \
    "ms-schema-fields" \
    "${ms_base}/${LAYER_ID}?f=json" "200" \
    '(.fields | length) > 0 and .fields[0].type != null' || failed=1
  append_cert_result "$proto" "CERT-SCHM-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-SCHM-02: Geometry type
  request_json \
    "ms-geometry-type" \
    "${ms_base}/${LAYER_ID}?f=json" "200" \
    '.geometryType == "esriGeometryPoint"' || failed=1
  append_cert_result "$proto" "CERT-SCHM-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-QFLT-01, QFLT-02, PAGE-01, PAGE-02, GEOM-01, GEOM-02: not-applicable (rendering-only lane)
  record_na_with_lane "ms-qflt-01" "$proto" "CERT-QFLT-01" "Rendering-only lane; query not exercised"
  record_na_with_lane "ms-qflt-02" "$proto" "CERT-QFLT-02" "Rendering-only lane; query not exercised"
  record_na_with_lane "ms-page-01" "$proto" "CERT-PAGE-01" "Rendering-only lane; query not exercised"
  record_na_with_lane "ms-page-02" "$proto" "CERT-PAGE-02" "Rendering-only lane; query not exercised"
  record_na_with_lane "ms-geom-01" "$proto" "CERT-GEOM-01" "Rendering-only lane; query not exercised"
  record_na_with_lane "ms-geom-02" "$proto" "CERT-GEOM-02" "Rendering-only lane; query not exercised"

  # CERT-ERRH-01: Invalid layer
  request_json_4xx \
    "ms-error-invalid" \
    "${ms_base}/99999?f=json" \
    '.error != null' || failed=1
  append_cert_result "$proto" "CERT-ERRH-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-ERRH-02: not-applicable (rendering-only, query endpoint not exercised)
  record_na_with_lane "ms-errh-02" "$proto" "CERT-ERRH-02" "Rendering-only lane; malformed query not applicable"

  # CERT-RNDR-01, RNDR-02 (skip)
  record_skip_with_lane "ms-rndr-render" "$proto" "CERT-RNDR-01" "Visual rendering requires manual client"
  record_skip_with_lane "ms-rndr-refresh" "$proto" "CERT-RNDR-02" "Data refresh requires manual client"

  return "$failed"
}

run_full_odata() {
  local failed=0
  local proto="odata"

  # CERT-CONN-01 (GET; server routes do not support HEAD)
  request_json "odata-conn-check" "${BASE_URL}/odata" "200" "true" || failed=1
  append_cert_result "$proto" "CERT-CONN-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # Common skips
  record_skip_with_lane "odata-conn-tls" "$proto" "CERT-CONN-02" "HTTP-only CI environment; TLS not available"
  record_skip_with_lane "odata-auth-unauth" "$proto" "CERT-AUTH-01" "No auth configured in CI seed"
  record_skip_with_lane "odata-auth-valid" "$proto" "CERT-AUTH-02" "No auth configured in CI seed"

  # CERT-DISC-01: Service document
  request_json \
    "odata-service-document" \
    "${BASE_URL}/odata" "200" \
    '(.value | map(.name) | index("Layers")) != null and (.value | map(.name) | index("Features")) != null' || failed=1
  local disc01_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    disc01_count=$(jq -r '.value | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-DISC-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$disc01_count" "" ""

  # CERT-DISC-02: Metadata document
  request_text \
    "odata-metadata" \
    "${BASE_URL}/odata/\$metadata" "200" \
    'EntityType Name="Feature"' \
    'application/xml' || failed=1
  append_cert_result "$proto" "CERT-DISC-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-SCHM-01: Schema properties in metadata
  request_text \
    "odata-schema-properties" \
    "${BASE_URL}/odata/\$metadata" "200" \
    'Property Name=' \
    'application/xml' || failed=1
  append_cert_result "$proto" "CERT-SCHM-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-SCHM-02: not-applicable (OData does not report geometry type)
  record_na_with_lane "odata-schm-02" "$proto" "CERT-SCHM-02" "OData does not report geometry type per BI lane matrix"

  # CERT-QFLT-01: Attribute filter on features (seed has 5 active out of 10)
  request_json \
    "odata-attribute-filter" \
    "${BASE_URL}/odata/Features(${LAYER_ID})?\$filter=status%20eq%20%27active%27" "200" \
    '(.value | length) == 5' || failed=1
  local qflt01_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    qflt01_count=$(jq -r '.value | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-QFLT-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$qflt01_count" "" ""

  # CERT-QFLT-02: not-applicable (spatial bbox not available via OData)
  record_na_with_lane "odata-qflt-02" "$proto" "CERT-QFLT-02" "Spatial bbox not applicable to OData"

  # CERT-PAGE-01: First page
  request_json \
    "odata-features-first-page" \
    "${BASE_URL}/odata/Features(${LAYER_ID})?\$top=3" "200" \
    '(.value | length) == 3 and (."@odata.nextLink" != null)' || failed=1
  local page01_count=""
  if [[ -f "$LAST_BODY_PATH" ]]; then
    page01_count=$(jq -r '.value | length' "$LAST_BODY_PATH" 2>/dev/null || echo "")
  fi
  append_cert_result "$proto" "CERT-PAGE-01" "$LAST_STATUS" "$LAST_DURATION_MS" "$page01_count" "" ""

  # CERT-PAGE-02: Second page offset
  request_json \
    "odata-features-second-page" \
    "${BASE_URL}/odata/Features(${LAYER_ID})?\$top=3&\$skip=3" "200" \
    '(.value | length) == 3 and (.value[0].ObjectId > 3)' || failed=1
  append_cert_result "$proto" "CERT-PAGE-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-GEOM-01, GEOM-02: not-applicable (OData BI lane per matrix)
  record_na_with_lane "odata-geom-01" "$proto" "CERT-GEOM-01" "Geometry fidelity not applicable to OData BI lane"
  record_na_with_lane "odata-geom-02" "$proto" "CERT-GEOM-02" "CRS not applicable to OData BI lane"

  # CERT-ERRH-01: Non-existent layer returns structured OData error
  request_json_4xx \
    "odata-error-invalid" \
    "${BASE_URL}/odata/Features(99999)" \
    '.error != null' || failed=1
  append_cert_result "$proto" "CERT-ERRH-01" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-ERRH-02: Malformed filter
  request_json_4xx \
    "odata-error-malformed" \
    "${BASE_URL}/odata/Layers?\$filter=INVALID%21%21%21" \
    '.error != null' || failed=1
  append_cert_result "$proto" "CERT-ERRH-02" "$LAST_STATUS" "$LAST_DURATION_MS" "" "" ""

  # CERT-RNDR-01, RNDR-02 (skip)
  record_skip_with_lane "odata-rndr-render" "$proto" "CERT-RNDR-01" "Visual rendering requires manual client"
  record_skip_with_lane "odata-rndr-refresh" "$proto" "CERT-RNDR-02" "Data refresh requires manual client"

  return "$failed"
}

# ---------------------------------------------------------------------------
# Full profile: lane runners
# ---------------------------------------------------------------------------

run_desktop_lane_full() {
  local lane_failed=0
  init_lane "desktop"

  run_full_featureserver || lane_failed=1
  run_full_ogc_features || lane_failed=1
  run_full_mapserver || lane_failed=1

  finalize_lane "desktop" "Desktop"
  return "$lane_failed"
}

run_bi_lane_full() {
  local lane_failed=0
  init_lane "bi"

  run_full_odata || lane_failed=1

  finalize_lane "bi" "BI"
  return "$lane_failed"
}

# ---------------------------------------------------------------------------
# Cert evidence envelope generation
# ---------------------------------------------------------------------------

generate_cert_envelope() {
  local client_lane="$1" protocol="$2"
  local cert_results_file="$CERT_DIR/cert-results-${protocol}.tsv"
  local cert_json="$CERT_DIR/${TIMESTAMP}-${client_lane}-${protocol}.cert.json"
  local client_version
  client_version="curl/$(curl --version 2>/dev/null | head -1 | awk '{print $2}')"

  if [[ ! -f "$cert_results_file" ]]; then
    echo "Warning: no cert results for ${protocol}, skipping envelope" >&2
    return 0
  fi

  jq -Rn \
    --arg schema_version "1.0" \
    --arg run_id "$TIMESTAMP" \
    --arg run_date "$GENERATED_AT" \
    --arg server_version "$SERVER_VERSION" \
    --arg client_lane "$client_lane" \
    --arg client_version "$client_version" \
    --arg protocol "$protocol" \
    --arg environment "ci" \
    '
      [inputs | select(length > 0) | split("\t")] as $rows
      | {
          schema_version: $schema_version,
          run_id: $run_id,
          run_date: $run_date,
          server_version: $server_version,
          client_lane: $client_lane,
          client_version: $client_version,
          protocol: $protocol,
          environment: $environment,
          results: [
            $rows[]
            | {
                test_case_id: .[0],
                status: .[1],
                duration_ms: (if (.[2] // "") == "" then null else (.[2] | tonumber) end),
                measured_count: (if (.[3] // "") == "" then null else (.[3] | tonumber) end),
                measured_delta: (if (.[4] // "") == "" then null else (.[4] | tonumber) end),
                notes: (if (.[5] // "") == "" then "" else .[5] end),
                evidence_ref: (if (.[6] // "") == "" then "" else .[6] end)
              }
          ],
          summary: {
            total: ($rows | length),
            passed: ($rows | map(select(.[1] == "pass")) | length),
            failed: ($rows | map(select(.[1] == "fail")) | length),
            skipped: ($rows | map(select(.[1] == "skip")) | length),
            not_applicable: ($rows | map(select(.[1] == "not-applicable")) | length)
          },
          cite_results: null,
          extensions: []
        }
    ' < "$cert_results_file" > "$cert_json"

  echo "Generated: ${cert_json#$ROOT_DIR/}"
}

generate_all_cert_envelopes() {
  generate_cert_envelope "ci-desktop" "featureserver"
  generate_cert_envelope "ci-desktop" "ogc-features"
  generate_cert_envelope "ci-desktop" "mapserver"
  generate_cert_envelope "ci-bi" "odata"
}

write_overall_summary() {
  local overall_json="$ARTIFACT_ROOT/overall-summary.json"
  local overall_md="$ARTIFACT_ROOT/overall-summary.md"

  jq -s \
    --arg artifact_root "${ARTIFACT_ROOT#$ROOT_DIR/}" \
    --arg generated_at "$GENERATED_AT" \
    --arg service_id "$SERVICE_ID" \
    --arg layer_id "$LAYER_ID" \
    --arg seed_source "$SEED_SOURCE" \
    --arg server_version "$SERVER_VERSION" \
    '
      {
        generated_at: $generated_at,
        artifact_root: $artifact_root,
        service_id: $service_id,
        layer_id: $layer_id,
        seed_source: $seed_source,
        server_version: $server_version,
        status: (if any(.[]; .status == "fail") then "fail" else "pass" end),
        lanes: map({
          lane,
          title,
          status,
          summary,
          summary_path: ("lanes/" + .lane + "/lane-summary.json")
        })
      }
    ' \
    "$LANES_DIR/desktop/lane-summary.json" \
    "$LANES_DIR/bi/lane-summary.json" > "$overall_json"

  {
    echo "## Windows Client Compatibility Summary"
    echo
    echo "| Lane | Status | Passed | Failed | Summary |"
    echo "|---|---|---:|---:|---|"
    jq -r '
      .lanes[]
      | "| \(.title) | \(.status | ascii_upcase) | \(.summary.passed) | \(.summary.failed) | `\(.summary_path)` |"
    ' "$overall_json"
    echo
    echo "- Artifact root: \`${ARTIFACT_ROOT#$ROOT_DIR/}\`"
    echo "- Seed snapshot: \`$SEED_SOURCE\`"
    echo "- Server version: \`$SERVER_VERSION\`"
  } > "$overall_md"
}

prepare_pack
write_artifact_readme
write_metadata

desktop_exit=0
bi_exit=0

if [[ "$PROFILE" == "smoke" ]]; then
  run_desktop_lane || desktop_exit=$?
  run_bi_lane || bi_exit=$?
else
  run_desktop_lane_full || desktop_exit=$?
  run_bi_lane_full || bi_exit=$?
  generate_all_cert_envelopes
fi

write_overall_summary

rm -f "$LAST_BODY_PATH" 2>/dev/null || true

if [[ $desktop_exit -ne 0 || $bi_exit -ne 0 ]]; then
  exit 1
fi
