#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage: run-client-compat-smoke.sh [options]

Options:
  --base-url <url>       Base URL for the running Honua server.
  --service-id <id>      Service id to exercise. Default: test_service
  --layer-id <id>        Layer id to exercise. Default: 0
  --timestamp <value>    UTC timestamp segment for artifact layout.
  --output-root <path>   Override the artifact output root.
  --seed-source <path>   Seed snapshot used for this run.
  --help                 Show this help message.
EOF
}

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
BASE_URL="http://localhost:5000"
SERVICE_ID="test_service"
LAYER_ID="0"
TIMESTAMP="$(date -u +'%Y%m%dT%H%M%SZ')"
SEED_SOURCE="tests/seed/client-compat-v1.sql"
OUTPUT_ROOT=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --base-url)
      BASE_URL="${2:?missing value for --base-url}"
      shift 2
      ;;
    --service-id)
      SERVICE_ID="${2:?missing value for --service-id}"
      shift 2
      ;;
    --layer-id)
      LAYER_ID="${2:?missing value for --layer-id}"
      shift 2
      ;;
    --timestamp)
      TIMESTAMP="${2:?missing value for --timestamp}"
      shift 2
      ;;
    --output-root)
      OUTPUT_ROOT="${2:?missing value for --output-root}"
      shift 2
      ;;
    --seed-source)
      SEED_SOURCE="${2:?missing value for --seed-source}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required." >&2
  exit 1
fi

if ! command -v jq >/dev/null 2>&1; then
  echo "jq is required." >&2
  exit 1
fi

BASE_URL="${BASE_URL%/}"

if [[ -z "$OUTPUT_ROOT" ]]; then
  OUTPUT_ROOT="$ROOT_DIR/artifacts/client-compat/${SERVICE_ID}-${TIMESTAMP}"
fi

ARTIFACT_ROOT="$OUTPUT_ROOT"
PACK_DIR="$ARTIFACT_ROOT/pack"
METADATA_DIR="$ARTIFACT_ROOT/metadata"
SERVER_DIR="$ARTIFACT_ROOT/server"
LANES_DIR="$ARTIFACT_ROOT/lanes"
SERVER_VERSION="${GITHUB_SHA:-$(git -C "$ROOT_DIR" rev-parse HEAD 2>/dev/null || echo unknown)}"
GENERATED_AT="$(date -u +'%Y-%m-%dT%H:%M:%SZ')"

mkdir -p "$PACK_DIR" "$METADATA_DIR" "$SERVER_DIR" "$LANES_DIR"

copy_required() {
  local source_rel="$1"
  local dest_path="$2"
  local source_path="$ROOT_DIR/$source_rel"

  if [[ ! -f "$source_path" ]]; then
    echo "Missing required pack source: $source_rel" >&2
    exit 1
  fi

  mkdir -p "$(dirname "$dest_path")"
  cp "$source_path" "$dest_path"
}

prepare_pack() {
  mkdir -p \
    "$PACK_DIR/templates/desktop/arcgis-pro" \
    "$PACK_DIR/templates/desktop/qgis" \
    "$PACK_DIR/templates/bi/power-bi" \
    "$PACK_DIR/templates/bi/excel" \
    "$PACK_DIR/runbook"

  copy_required "docs/gis/client-templates/.env.example" "$PACK_DIR/templates/.env.example"
  copy_required "docs/gis/client-templates/arcgis-pro/Honua-Desktop-Smoke.aprx.template.md" "$PACK_DIR/templates/desktop/arcgis-pro/Honua-Desktop-Smoke.aprx.template.md"
  copy_required "docs/user/client-templates/qgis/Honua-Desktop-Smoke.qgs.template" "$PACK_DIR/templates/desktop/qgis/Honua-Desktop-Smoke.qgs.template"
  copy_required "docs/gis/client-templates/power-bi/Honua-OData-Smoke.pq.template" "$PACK_DIR/templates/bi/power-bi/Honua-OData-Smoke.pq.template"
  copy_required "docs/gis/client-templates/power-bi/Honua-OData-Smoke.pbix.template.md" "$PACK_DIR/templates/bi/power-bi/Honua-OData-Smoke.pbix.template.md"
  copy_required "docs/gis/client-templates/excel/Honua-OData-Smoke.pq.template" "$PACK_DIR/templates/bi/excel/Honua-OData-Smoke.pq.template"
  copy_required "docs/gis/client-templates/excel/Honua-OData-Smoke.xlsx.template.md" "$PACK_DIR/templates/bi/excel/Honua-OData-Smoke.xlsx.template.md"

  copy_required "docs/gis/CLIENT_TEMPLATE_RUNBOOK.md" "$PACK_DIR/runbook/CLIENT_TEMPLATE_RUNBOOK.md"
  copy_required "docs/gis/CROSS_CLIENT_CERTIFICATION_EVIDENCE.md" "$PACK_DIR/runbook/CROSS_CLIENT_CERTIFICATION_EVIDENCE.md"
  copy_required "docs/gis/CROSS_CLIENT_CERTIFICATION_MATRIX.md" "$PACK_DIR/runbook/CROSS_CLIENT_CERTIFICATION_MATRIX.md"
  copy_required "docs/gis/CLIENT_TEMPLATE_VERSION_MATRIX.md" "$PACK_DIR/runbook/CLIENT_TEMPLATE_VERSION_MATRIX.md"

  cat > "$PACK_DIR/README.md" <<EOF
# Client Compatibility Pack

This pack is generated by the Windows client compatibility certification workflow.

- Seed snapshot: \`$(basename "$SEED_SOURCE")\`
- Service id: \`$SERVICE_ID\`
- Layer id: \`$LAYER_ID\`
- Generated at: \`$GENERATED_AT\`

## Contents

- \`templates/\`: reusable ArcGIS Pro, QGIS, Power BI, and Excel template sources.
- \`runbook/\`: smoke-run procedure, evidence schema, certification matrix, and version ledger.

## Source Notes

The current repository stores client-template sources across both \`docs/gis\` and \`docs/user\`.
This workflow assembles them into one canonical pack so manual follow-through uses a single layout.
EOF
}

write_artifact_readme() {
  cat > "$ARTIFACT_ROOT/README.md" <<EOF
# Client Compatibility Evidence

- Service id: \`$SERVICE_ID\`
- Layer id: \`$LAYER_ID\`
- Base URL: \`$BASE_URL\`
- Seed snapshot: \`$SEED_SOURCE\`
- Server version: \`$SERVER_VERSION\`
- Generated at: \`$GENERATED_AT\`

## Layout

- \`overall-summary.json\` and \`overall-summary.md\`: aggregate lane verdicts.
- \`lanes/<lane>/\`: per-lane summaries and request/response transcripts.
- \`server/\`: captured Honua server logs.
- \`pack/\`: reusable client compatibility pack for manual Windows follow-through.
- \`metadata/\`: workflow provenance and the exact seed snapshot used for the run.
EOF
}

write_metadata() {
  jq -n \
    --arg generated_at "$GENERATED_AT" \
    --arg timestamp "$TIMESTAMP" \
    --arg base_url "$BASE_URL" \
    --arg service_id "$SERVICE_ID" \
    --arg layer_id "$LAYER_ID" \
    --arg seed_source "$SEED_SOURCE" \
    --arg server_version "$SERVER_VERSION" \
    --arg github_run_id "${GITHUB_RUN_ID:-}" \
    --arg github_workflow "${GITHUB_WORKFLOW:-}" \
    '{
      generated_at: $generated_at,
      timestamp: $timestamp,
      base_url: $base_url,
      service_id: $service_id,
      layer_id: $layer_id,
      seed_source: $seed_source,
      server_version: $server_version,
      github_run_id: (if $github_run_id == "" then null else $github_run_id end),
      github_workflow: (if $github_workflow == "" then null else $github_workflow end)
    }' > "$METADATA_DIR/workflow-context.json"

  copy_required "$SEED_SOURCE" "$METADATA_DIR/$(basename "$SEED_SOURCE")"
}

CURRENT_LANE=""
CURRENT_RESULTS_FILE=""

lane_dir() {
  printf '%s\n' "$LANES_DIR/$1"
}

init_lane() {
  CURRENT_LANE="$1"
  local lane_path
  lane_path="$(lane_dir "$CURRENT_LANE")"
  mkdir -p "$lane_path/transcripts"
  CURRENT_RESULTS_FILE="$lane_path/checks.tsv"
  : > "$CURRENT_RESULTS_FILE"
}

append_result() {
  local check_id="$1"
  local status="$2"
  local http_status="$3"
  local transcript_rel="$4"
  local note="$5"

  note="${note//$'\n'/ }"
  printf '%s\t%s\t%s\t%s\t%s\n' "$check_id" "$status" "$http_status" "$transcript_rel" "$note" >> "$CURRENT_RESULTS_FILE"
}

write_transcript() {
  local transcript_file="$1"
  local method="$2"
  local url="$3"
  local accept="$4"
  local http_status="$5"
  local note="$6"
  local headers_file="$7"
  local body_file="$8"

  {
    echo "# Request"
    echo "${method} ${url}"
    echo "Accept: ${accept}"
    echo
    echo "# Response"
    echo "HTTP ${http_status}"
    if [[ -n "$note" ]]; then
      echo "Note: ${note}"
    fi
    echo
    echo "## Headers"
    cat "$headers_file"
    echo
    echo "## Body"
    cat "$body_file"
  } > "$transcript_file"
}

request_json() {
  local check_id="$1"
  local url="$2"
  local expected_status="$3"
  local jq_expr="$4"
  local accept="${5:-application/json}"

  local lane_path headers_file body_file transcript_file transcript_rel http_status curl_exit status note
  lane_path="$(lane_dir "$CURRENT_LANE")"
  headers_file="$(mktemp)"
  body_file="$(mktemp)"
  transcript_file="$lane_path/transcripts/${check_id}.txt"
  transcript_rel="${transcript_file#$ARTIFACT_ROOT/}"
  http_status="0"
  curl_exit=0
  status="pass"
  note=""

  http_status="$(curl -sS -o "$body_file" -D "$headers_file" -H "Accept: ${accept}" -w '%{http_code}' "$url")" || curl_exit=$?

  if [[ $curl_exit -ne 0 ]]; then
    status="fail"
    note="curl exited with code ${curl_exit}"
  elif [[ "$http_status" != "$expected_status" ]]; then
    status="fail"
    note="expected HTTP ${expected_status}, got ${http_status}"
  elif ! jq -e "$jq_expr" "$body_file" >/dev/null 2>&1; then
    status="fail"
    note="response failed jq assertion: ${jq_expr}"
  fi

  write_transcript "$transcript_file" "GET" "$url" "$accept" "$http_status" "$note" "$headers_file" "$body_file"
  append_result "$check_id" "$status" "$http_status" "$transcript_rel" "$note"

  rm -f "$headers_file" "$body_file"

  [[ "$status" == "pass" ]]
}

request_text() {
  local check_id="$1"
  local url="$2"
  local expected_status="$3"
  local required_text="$4"
  local accept="${5:-text/plain}"

  local lane_path headers_file body_file transcript_file transcript_rel http_status curl_exit status note
  lane_path="$(lane_dir "$CURRENT_LANE")"
  headers_file="$(mktemp)"
  body_file="$(mktemp)"
  transcript_file="$lane_path/transcripts/${check_id}.txt"
  transcript_rel="${transcript_file#$ARTIFACT_ROOT/}"
  http_status="0"
  curl_exit=0
  status="pass"
  note=""

  http_status="$(curl -sS -o "$body_file" -D "$headers_file" -H "Accept: ${accept}" -w '%{http_code}' "$url")" || curl_exit=$?

  if [[ $curl_exit -ne 0 ]]; then
    status="fail"
    note="curl exited with code ${curl_exit}"
  elif [[ "$http_status" != "$expected_status" ]]; then
    status="fail"
    note="expected HTTP ${expected_status}, got ${http_status}"
  elif ! grep -Fq "$required_text" "$body_file"; then
    status="fail"
    note="response missing expected text: ${required_text}"
  fi

  write_transcript "$transcript_file" "GET" "$url" "$accept" "$http_status" "$note" "$headers_file" "$body_file"
  append_result "$check_id" "$status" "$http_status" "$transcript_rel" "$note"

  rm -f "$headers_file" "$body_file"

  [[ "$status" == "pass" ]]
}

finalize_lane() {
  local lane="$1"
  local title="$2"
  local lane_path summary_json summary_md
  lane_path="$(lane_dir "$lane")"
  summary_json="$lane_path/lane-summary.json"
  summary_md="$lane_path/lane-summary.md"

  jq -Rn \
    --arg lane "$lane" \
    --arg title "$title" \
    '
      [inputs | select(length > 0) | split("\t")] as $rows
      | {
          lane: $lane,
          title: $title,
          status: (if any($rows[]; .[1] == "fail") then "fail" else "pass" end),
          summary: {
            total: ($rows | length),
            passed: ($rows | map(select(.[1] == "pass")) | length),
            failed: ($rows | map(select(.[1] == "fail")) | length)
          },
          checks: [
            $rows[]
            | {
                id: .[0],
                status: .[1],
                http_status: (.[2] | tonumber),
                transcript: .[3],
                note: (if (.[4] // "") == "" then null else .[4] end)
              }
          ]
        }
    ' < "$lane_path/checks.tsv" > "$summary_json"

  {
    echo "## ${title} Lane"
    echo
    echo "| Check | Status | HTTP | Transcript | Note |"
    echo "|---|---|---:|---|---|"
    while IFS=$'\t' read -r check_id status http_status transcript_rel note; do
      local uppercase_status
      uppercase_status="$(printf '%s' "$status" | tr '[:lower:]' '[:upper:]')"
      printf '| `%s` | %s | %s | `%s` | %s |\n' \
        "$check_id" \
        "$uppercase_status" \
        "$http_status" \
        "$transcript_rel" \
        "${note:-}"
    done < "$lane_path/checks.tsv"
  } > "$summary_md"
}

run_desktop_lane() {
  local lane_failed=0
  init_lane "desktop"

  request_json \
    "featureserver-service-metadata" \
    "${BASE_URL}/rest/services/${SERVICE_ID}/FeatureServer?f=json" \
    "200" \
    '(.layers | length) > 0 and (.layers[0].id == 0)' || lane_failed=1

  request_json \
    "featureserver-layer-metadata" \
    "${BASE_URL}/rest/services/${SERVICE_ID}/FeatureServer/${LAYER_ID}?f=json" \
    "200" \
    '.id == 0 and (.fields | length) > 0 and .geometryType == "esriGeometryPoint"' || lane_failed=1

  request_json \
    "featureserver-query-active-subset" \
    "${BASE_URL}/rest/services/${SERVICE_ID}/FeatureServer/${LAYER_ID}/query?where=status%20%3D%20%27active%27&resultRecordCount=3&returnGeometry=true&f=json" \
    "200" \
    '(.features | length) == 3' || lane_failed=1

  request_json \
    "mapserver-service-metadata" \
    "${BASE_URL}/rest/services/${SERVICE_ID}/MapServer?f=json" \
    "200" \
    '(.layers | length) > 0' || lane_failed=1

  request_json \
    "ogc-collections" \
    "${BASE_URL}/ogc/features/collections" \
    "200" \
    '(.collections | length) > 0' || lane_failed=1

  request_json \
    "ogc-items-first-page" \
    "${BASE_URL}/ogc/features/collections/${LAYER_ID}/items?limit=3" \
    "200" \
    '(.features | length) == 3' || lane_failed=1

  finalize_lane "desktop" "Desktop"
  return "$lane_failed"
}

run_bi_lane() {
  local lane_failed=0
  init_lane "bi"

  request_json \
    "odata-service-document" \
    "${BASE_URL}/odata" \
    "200" \
    '(.value | map(.name) | index("Layers")) != null and (.value | map(.name) | index("Features")) != null' || lane_failed=1

  request_text \
    "odata-metadata" \
    "${BASE_URL}/odata/\$metadata" \
    "200" \
    'EntityType Name="Feature"' \
    'application/xml' || lane_failed=1

  request_json \
    "odata-layer-filter" \
    "${BASE_URL}/odata/Layers?\$filter=Name%20eq%20%27Test%20Layer%27" \
    "200" \
    '(.value | length) == 1' || lane_failed=1

  request_json \
    "odata-features-first-page" \
    "${BASE_URL}/odata/Features(${LAYER_ID})?\$top=3" \
    "200" \
    '(.value | length) == 3 and (."@odata.nextLink" != null)' || lane_failed=1

  request_json \
    "odata-features-second-page" \
    "${BASE_URL}/odata/Features(${LAYER_ID})?\$top=3&\$skip=3" \
    "200" \
    '(.value | length) == 3 and (.value[0].ObjectId > 3)' || lane_failed=1

  finalize_lane "bi" "BI"
  return "$lane_failed"
}

write_overall_summary() {
  local overall_json="$ARTIFACT_ROOT/overall-summary.json"
  local overall_md="$ARTIFACT_ROOT/overall-summary.md"

  jq -s \
    --arg artifact_root "${ARTIFACT_ROOT#$ROOT_DIR/}" \
    --arg generated_at "$GENERATED_AT" \
    --arg service_id "$SERVICE_ID" \
    --arg layer_id "$LAYER_ID" \
    --arg seed_source "$SEED_SOURCE" \
    --arg server_version "$SERVER_VERSION" \
    '
      {
        generated_at: $generated_at,
        artifact_root: $artifact_root,
        service_id: $service_id,
        layer_id: $layer_id,
        seed_source: $seed_source,
        server_version: $server_version,
        status: (if any(.[]; .status == "fail") then "fail" else "pass" end),
        lanes: map({
          lane,
          title,
          status,
          summary,
          summary_path: ("lanes/" + .lane + "/lane-summary.json")
        })
      }
    ' \
    "$LANES_DIR/desktop/lane-summary.json" \
    "$LANES_DIR/bi/lane-summary.json" > "$overall_json"

  {
    echo "## Windows Client Compatibility Summary"
    echo
    echo "| Lane | Status | Passed | Failed | Summary |"
    echo "|---|---|---:|---:|---|"
    jq -r '
      .lanes[]
      | "| \(.title) | \(.status | ascii_upcase) | \(.summary.passed) | \(.summary.failed) | `\(.summary_path)` |"
    ' "$overall_json"
    echo
    echo "- Artifact root: \`${ARTIFACT_ROOT#$ROOT_DIR/}\`"
    echo "- Seed snapshot: \`$SEED_SOURCE\`"
    echo "- Server version: \`$SERVER_VERSION\`"
  } > "$overall_md"
}

prepare_pack
write_artifact_readme
write_metadata

desktop_exit=0
bi_exit=0

run_desktop_lane || desktop_exit=$?
run_bi_lane || bi_exit=$?

write_overall_summary

if [[ $desktop_exit -ne 0 || $bi_exit -ne 0 ]]; then
  exit 1
fi
