// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Text.Json.Serialization;
using Honua.Core.Configuration;
using Honua.Server.Features.Admin.Services;
using ConfigurationSection = Honua.Core.Configuration.ConfigurationSection;

namespace Honua.Server.Features.Admin.Models;

/// <summary>
/// JSON source generation context for configuration discovery endpoints.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ConfigurationDiscoveryResult))]
[JsonSerializable(typeof(ConfigurationDocumentation))]
[JsonSerializable(typeof(ConfigurationSection))]
[JsonSerializable(typeof(ConfigurationProperty))]
[JsonSerializable(typeof(EnvironmentVariableInfo))]
[JsonSerializable(typeof(List<ConfigurationMetadata>))]
[JsonSerializable(typeof(List<AutoGeneratedDocumentationSection>))]
[JsonSerializable(typeof(SecretValidationResult))]
[JsonSerializable(typeof(ConfigurationAuditInfo))]
[JsonSerializable(typeof(ConfigurationSummary))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(decimal))]
[JsonSerializable(typeof(TimeSpan))]
[JsonSerializable(typeof(object))]
internal sealed partial class ConfigurationDiscoveryJsonContext : JsonSerializerContext
{
}
