// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Text.Json.Serialization;
using Honua.Server.Features.Admin.Services;

namespace Honua.Server.Features.Admin.Models;

/// <summary>
/// JSON source generation context for configuration discovery endpoints.
/// </summary>
[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(ConfigurationDiscoveryResult))]
[JsonSerializable(typeof(List<ConfigurationMetadata>))]
[JsonSerializable(typeof(List<AutoGeneratedDocumentationSection>))]
[JsonSerializable(typeof(SecretValidationResult))]
[JsonSerializable(typeof(ConfigurationAuditInfo))]
[JsonSerializable(typeof(ConfigurationSummary))]
internal sealed partial class ConfigurationDiscoveryJsonContext : JsonSerializerContext
{
}
