// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Diagnostics.Metrics;
using Honua.ServiceDefaults;

namespace Honua.Server.Features.Admin.TileOperations;

/// <summary>
/// Metrics emitted by tile operation jobs.
/// </summary>
internal static class TileOperationMetrics
{
    // `unit: null` on the instruments below is deliberate, not an oversight. The OpenTelemetry
    // Prometheus exporter derives the exported series name from the instrument name AND its unit:
    // it maps the unit through the UCUM table and appends it, so a declared unit renames the series
    // out from under every dashboard and alert rule without breaking a single build. A PromQL query
    // against the absent name returns an empty vector, so the panel is blank and the alert never
    // fires, silently. Units are documented in the instrument name and description instead. See the
    // SLO-contract comment block in HonuaTelemetry.cs, observability/metric-name-contract.json, and
    // MetricNameContractTests, which scrapes the real /metrics exposition and fails on drift.

    public static readonly UpDownCounter<long> QueueDepth = HonuaTelemetry.Meter.CreateUpDownCounter<long>(
        "honua.tile.jobs.queue_depth",
        unit: null,
        "Number of tile jobs waiting in queue.");

    public static readonly Counter<long> JobCount = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.jobs.total",
        unit: null,
        "Number of tile jobs completed by status.");

    public static readonly Histogram<double> JobDurationMs = HonuaTelemetry.Meter.CreateHistogram<double>(
        "honua.tile.jobs.duration_ms",
        unit: null,
        "Tile job execution duration in milliseconds.");

    public static readonly Counter<long> TileThroughput = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.jobs.tiles_processed",
        unit: null,
        "Number of tiles processed by tile jobs.");

    public static readonly Counter<long> ArchivesGenerated = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.archives.total",
        unit: null,
        "Number of PMTiles archives generated.");

    public static readonly Histogram<double> ArchiveSizeBytes = HonuaTelemetry.Meter.CreateHistogram<double>(
        "honua.tile.archives.size_bytes",
        "bytes",
        "Size of generated PMTiles archives.");

    /// <summary>Number of tiles successfully generated (rendered) by seed/warm/archive jobs.</summary>
    public static readonly Counter<long> TilesGenerated = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.generated",
        unit: null,
        "Number of tiles successfully generated by tile-cache jobs.");

    /// <summary>Number of tiles that failed to generate during seed/warm/archive jobs.</summary>
    public static readonly Counter<long> TilesFailed = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.failed",
        unit: null,
        "Number of tiles that failed to generate during tile-cache jobs.");

    /// <summary>Number of generated cache tiles deleted from cloud storage by bounded delete jobs (#2661).</summary>
    public static readonly Counter<long> TilesDeleted = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.deleted",
        unit: null,
        "Number of generated cache tiles deleted from the cloud tile store by bounded delete jobs.");

    /// <summary>Number of generated cache tiles marked stale by bounded expire jobs (#2661).</summary>
    public static readonly Counter<long> TilesExpired = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.expired",
        unit: null,
        "Number of generated cache tiles marked stale by bounded expire jobs.");

    /// <summary>Bytes released from the tile cache by bounded expire/delete jobs (#2661).</summary>
    public static readonly Counter<long> CacheBytesReleased = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.bytes_released",
        unit: null,
        "Bytes released from the generated tile cache by bounded expire/delete jobs.");

    // Generated tile-cache serve-path hit/miss counters (honua.tile.cache.hits / .misses) are
    // owned by GeoServicesCloudTileCache, the single place every generated-cache read passes
    // through. They are deliberately not redeclared here: a counter declared beside the job
    // metrics but never incremented from the serve path would report a permanent zero.
}

