// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Diagnostics.Metrics;
using Honua.ServiceDefaults;

namespace Honua.Server.Features.Admin.TileOperations;

/// <summary>
/// Metrics emitted by tile operation jobs.
/// </summary>
internal static class TileOperationMetrics
{
    public static readonly UpDownCounter<long> QueueDepth = HonuaTelemetry.Meter.CreateUpDownCounter<long>(
        "honua.tile.jobs.queue_depth",
        "jobs",
        "Number of tile jobs waiting in queue.");

    public static readonly Counter<long> JobCount = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.jobs.total",
        "jobs",
        "Number of tile jobs completed by status.");

    public static readonly Histogram<double> JobDurationMs = HonuaTelemetry.Meter.CreateHistogram<double>(
        "honua.tile.jobs.duration_ms",
        "ms",
        "Tile job execution duration in milliseconds.");

    public static readonly Counter<long> TileThroughput = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.jobs.tiles_processed",
        "tiles",
        "Number of tiles processed by tile jobs.");

    public static readonly Counter<long> ArchivesGenerated = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.archives.total",
        "archives",
        "Number of PMTiles archives generated.");

    public static readonly Histogram<double> ArchiveSizeBytes = HonuaTelemetry.Meter.CreateHistogram<double>(
        "honua.tile.archives.size_bytes",
        "bytes",
        "Size of generated PMTiles archives.");

    /// <summary>Number of tiles successfully generated (rendered) by seed/warm/archive jobs.</summary>
    public static readonly Counter<long> TilesGenerated = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.generated",
        "tiles",
        "Number of tiles successfully generated by tile-cache jobs.");

    /// <summary>Number of tiles that failed to generate during seed/warm/archive jobs.</summary>
    public static readonly Counter<long> TilesFailed = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.failed",
        "tiles",
        "Number of tiles that failed to generate during tile-cache jobs.");

    /// <summary>Number of generated cache tiles deleted from cloud storage by bounded delete jobs (#2661).</summary>
    public static readonly Counter<long> TilesDeleted = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.deleted",
        "tiles",
        "Number of generated cache tiles deleted from the cloud tile store by bounded delete jobs.");

    /// <summary>Number of generated cache tiles marked stale by bounded expire jobs (#2661).</summary>
    public static readonly Counter<long> TilesExpired = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.expired",
        "tiles",
        "Number of generated cache tiles marked stale by bounded expire jobs.");

    /// <summary>Bytes released from the tile cache by bounded expire/delete jobs (#2661).</summary>
    public static readonly Counter<long> CacheBytesReleased = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.bytes_released",
        "bytes",
        "Bytes released from the generated tile cache by bounded expire/delete jobs.");

    /// <summary>Generated tile-cache serve-path hits (reserved for the serve adapters, #2661).</summary>
    public static readonly Counter<long> CacheHits = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.hits",
        "tiles",
        "Number of generated tile-cache serve-path hits.");

    /// <summary>Generated tile-cache serve-path misses (reserved for the serve adapters, #2661).</summary>
    public static readonly Counter<long> CacheMisses = HonuaTelemetry.Meter.CreateCounter<long>(
        "honua.tile.cache.misses",
        "tiles",
        "Number of generated tile-cache serve-path misses.");
}

