# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from honua_sdk.grpc._generated.honua.v1 import feature_service_pb2 as honua_dot_v1_dot_feature__service__pb2

GRPC_GENERATED_VERSION = '1.70.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in honua/v1/feature_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FeatureServiceStub(object):
    """FeatureService provides typed RPC access to geospatial feature queries.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.QueryFeatures = channel.unary_unary(
                '/honua.v1.FeatureService/QueryFeatures',
                request_serializer=honua_dot_v1_dot_feature__service__pb2.QueryFeaturesRequest.SerializeToString,
                response_deserializer=honua_dot_v1_dot_feature__service__pb2.QueryFeaturesResponse.FromString,
                _registered_method=True)
        self.QueryFeaturesStream = channel.unary_stream(
                '/honua.v1.FeatureService/QueryFeaturesStream',
                request_serializer=honua_dot_v1_dot_feature__service__pb2.QueryFeaturesRequest.SerializeToString,
                response_deserializer=honua_dot_v1_dot_feature__service__pb2.FeaturePage.FromString,
                _registered_method=True)


class FeatureServiceServicer(object):
    """FeatureService provides typed RPC access to geospatial feature queries.
    """

    def QueryFeatures(self, request, context):
        """QueryFeatures executes a feature query and returns all results in a single response.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def QueryFeaturesStream(self, request, context):
        """QueryFeaturesStream executes a feature query and streams results as pages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FeatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'QueryFeatures': grpc.unary_unary_rpc_method_handler(
                    servicer.QueryFeatures,
                    request_deserializer=honua_dot_v1_dot_feature__service__pb2.QueryFeaturesRequest.FromString,
                    response_serializer=honua_dot_v1_dot_feature__service__pb2.QueryFeaturesResponse.SerializeToString,
            ),
            'QueryFeaturesStream': grpc.unary_stream_rpc_method_handler(
                    servicer.QueryFeaturesStream,
                    request_deserializer=honua_dot_v1_dot_feature__service__pb2.QueryFeaturesRequest.FromString,
                    response_serializer=honua_dot_v1_dot_feature__service__pb2.FeaturePage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'honua.v1.FeatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('honua.v1.FeatureService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FeatureService(object):
    """FeatureService provides typed RPC access to geospatial feature queries.
    """

    @staticmethod
    def QueryFeatures(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/honua.v1.FeatureService/QueryFeatures',
            honua_dot_v1_dot_feature__service__pb2.QueryFeaturesRequest.SerializeToString,
            honua_dot_v1_dot_feature__service__pb2.QueryFeaturesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def QueryFeaturesStream(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/honua.v1.FeatureService/QueryFeaturesStream',
            honua_dot_v1_dot_feature__service__pb2.QueryFeaturesRequest.SerializeToString,
            honua_dot_v1_dot_feature__service__pb2.FeaturePage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
