// Copyright (c) Honua. All rights reserved.
// Licensed under the Elastic License 2.0. See LICENSE in the project root.

using System.Text.Json.Serialization;
using Honua.Core.Features.Import.Abstractions;
using Honua.Core.Features.Import.Domain;
using Honua.Core.Features.Infrastructure.Domain;
using Honua.Server.Features.Infrastructure.Models;

namespace Honua.Server.Features.Import;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(FileFormatsResponse))]
[JsonSerializable(typeof(MigrationInventoryScanRequest))]
[JsonSerializable(typeof(MigrationScanArtifactSet))]
[JsonSerializable(typeof(OgcApiFeaturesImportApiRequest))]
[JsonSerializable(typeof(OgcApiFeaturesImportRequest))]
[JsonSerializable(typeof(OgcApiFeaturesImportResult))]
[JsonSerializable(typeof(OgcApiFeaturesSchemaMappingDiagnostic))]
[JsonSerializable(typeof(OgcApiFeaturesSchemaMappingDiagnostic[]))]
[JsonSerializable(typeof(IReadOnlyList<OgcApiFeaturesSchemaMappingDiagnostic>))]
[JsonSerializable(typeof(OgcApiFeaturesSchemaMappingClassification))]
[JsonSerializable(typeof(OgcApiFeaturesFeatureCountParity))]
[JsonSerializable(typeof(GeoservicesCredentialDescriptor))]
[JsonSerializable(typeof(MigrationSourceInventoryArtifact))]
[JsonSerializable(typeof(MigrationManifestArtifact))]
[JsonSerializable(typeof(MigrationManifestTargetResource))]
[JsonSerializable(typeof(MigrationManifestTargetResource[]))]
[JsonSerializable(typeof(MigrationManifestStyleAction))]
[JsonSerializable(typeof(MigrationManifestStyleAction[]))]
[JsonSerializable(typeof(MigrationManifestServicePlan))]
[JsonSerializable(typeof(MigrationManifestServicePlan[]))]
[JsonSerializable(typeof(MigrationManifestReviewItem))]
[JsonSerializable(typeof(MigrationManifestReviewItem[]))]
[JsonSerializable(typeof(MigrationManifestPlanEntry))]
[JsonSerializable(typeof(MigrationManifestPlanEntry[]))]
[JsonSerializable(typeof(MigrationManifestPlanDiagnostic))]
[JsonSerializable(typeof(MigrationManifestPlanDiagnostic[]))]
[JsonSerializable(typeof(MigrationManifestIdentityRemap))]
[JsonSerializable(typeof(MigrationManifestIdentityRemap[]))]
[JsonSerializable(typeof(MigrationManifestResourceIdentity))]
[JsonSerializable(typeof(MigrationManifestServiceIdentity))]
[JsonSerializable(typeof(MigrationManifestAttachmentRecord))]
[JsonSerializable(typeof(MigrationManifestAttachmentRecord[]))]
[JsonSerializable(typeof(MigrationManifestRelationshipRecord))]
[JsonSerializable(typeof(MigrationManifestRelationshipRecord[]))]
[JsonSerializable(typeof(MigrationManifestRendererDiagnostic))]
[JsonSerializable(typeof(MigrationManifestRendererDiagnostic[]))]
[JsonSerializable(typeof(MigrationManifestLabelClassDiagnostic))]
[JsonSerializable(typeof(MigrationManifestLabelClassDiagnostic[]))]
[JsonSerializable(typeof(MigrationFidelityMatrix))]
[JsonSerializable(typeof(MigrationFidelityMatrixSummary))]
[JsonSerializable(typeof(MigrationFidelityMatrixCell))]
[JsonSerializable(typeof(MigrationFidelityMatrixCell[]))]
[JsonSerializable(typeof(MigrationRunMetricsArtifact))]
[JsonSerializable(typeof(MigrationRunMetricsPhase))]
[JsonSerializable(typeof(MigrationRunMetricsPhase[]))]
[JsonSerializable(typeof(MigrationRunMetricsResourceSample))]
[JsonSerializable(typeof(MigrationRunMetricsResourceSample[]))]
[JsonSerializable(typeof(MigrationRunMetricsValues))]
[JsonSerializable(typeof(MigrationRunMetricsSourceSummary))]
[JsonSerializable(typeof(MigrationRunMetricsPrivacySummary))]
[JsonSerializable(typeof(MigrationRunMetricsBaselineArtifact))]
[JsonSerializable(typeof(MigrationMetricBaseline))]
[JsonSerializable(typeof(MigrationMetricBaselineBand))]
[JsonSerializable(typeof(MigrationMetricBaselineBand[]))]
[JsonSerializable(typeof(MigrationMetricBaselineSignal))]
[JsonSerializable(typeof(MigrationMetricBaselineSignal[]))]
[JsonSerializable(typeof(MigrationFixtureSizeProfile))]
[JsonSerializable(typeof(MigrationPerformanceEvidenceArtifact))]
[JsonSerializable(typeof(MigrationPerformanceEvidenceRedactionPosture))]
[JsonSerializable(typeof(MigrationPerformanceEvidenceRecord))]
[JsonSerializable(typeof(MigrationPerformanceEvidenceRecord[]))]
[JsonSerializable(typeof(IReadOnlyList<MigrationPerformanceEvidenceRecord>))]
[JsonSerializable(typeof(MigrationPerformanceEvidenceHistoryResponse))]
[JsonSerializable(typeof(MigrationParityEvidenceArtifact))]
[JsonSerializable(typeof(MigrationParityEvidenceSection))]
[JsonSerializable(typeof(MigrationParityEvidenceSection[]))]
[JsonSerializable(typeof(MigrationParityEvidenceItem))]
[JsonSerializable(typeof(MigrationParityEvidenceItem[]))]
[JsonSerializable(typeof(ArcGisMigrationParityArtifact))]
[JsonSerializable(typeof(ArcGisMigrationParityResourceProbe))]
[JsonSerializable(typeof(ArcGisMigrationParityResourceProbe[]))]
[JsonSerializable(typeof(ArcGisMigrationParityFeatureCountProbe))]
[JsonSerializable(typeof(ArcGisMigrationParitySchemaProbe))]
[JsonSerializable(typeof(ArcGisMigrationParityCoverageProbe))]
[JsonSerializable(typeof(ArcGisMigrationRunListResult))]
[JsonSerializable(typeof(ArcGisMigrationRunSummary))]
[JsonSerializable(typeof(ArcGisMigrationRunSummary[]))]
[JsonSerializable(typeof(MigrationCutoverReadinessSummary))]
[JsonSerializable(typeof(MigrationCutoverReadinessItem))]
[JsonSerializable(typeof(MigrationCutoverReadinessItem[]))]
[JsonSerializable(typeof(MigrationReadinessStageReport))]
[JsonSerializable(typeof(MigrationReadinessStageEntry))]
[JsonSerializable(typeof(MigrationReadinessStageEntry[]))]
[JsonSerializable(typeof(MigrationReadinessStageSummary))]
[JsonSerializable(typeof(MigrationReadinessAttestationArtifact))]
[JsonSerializable(typeof(MigrationReadinessAttestationArtifact[]))]
[JsonSerializable(typeof(MigrationReadinessReason))]
[JsonSerializable(typeof(MigrationReadinessReason[]))]
[JsonSerializable(typeof(MigrationReadinessEvidenceCitation))]
[JsonSerializable(typeof(MigrationReadinessEvidenceCitation[]))]
[JsonSerializable(typeof(MigrationInventoryField))]
[JsonSerializable(typeof(MigrationInventoryField[]))]
[JsonSerializable(typeof(MigrationRunDto))]
[JsonSerializable(typeof(MigrationRunDto[]))]
[JsonSerializable(typeof(MigrationRunListResponse))]
[JsonSerializable(typeof(MigrationRunCancelRequest))]
[JsonSerializable(typeof(MigrationInventoryCodedValue))]
[JsonSerializable(typeof(MigrationInventoryCodedValue[]))]
[JsonSerializable(typeof(FilePreview))]
[JsonSerializable(typeof(ImportResult))]
[JsonSerializable(typeof(ImportValidationIssue))]
[JsonSerializable(typeof(IReadOnlyList<ImportValidationIssue>))]
[JsonSerializable(typeof(ImportProgress))]
[JsonSerializable(typeof(ImportLimits))]
[JsonSerializable(typeof(ImportStatus))]
[JsonSerializable(typeof(BackgroundImportResponse))]
[JsonSerializable(typeof(PreviewUrlImportRequest))]
[JsonSerializable(typeof(ImportUrlImportRequest))]
[JsonSerializable(typeof(ImportProgress[]))]
[JsonSerializable(typeof(CancelUploadResponse))]
[JsonSerializable(typeof(CancelImportJobResponse))]
[JsonSerializable(typeof(ActiveUploadsResponse))]
[JsonSerializable(typeof(ActiveImportJobsResponse))]
[JsonSerializable(typeof(UploadProgress[]))]
// New unified progress types
[JsonSerializable(typeof(IOperationProgress))]
[JsonSerializable(typeof(UploadProgress))]
[JsonSerializable(typeof(IngestProgress))]
[JsonSerializable(typeof(OperationType))]
[JsonSerializable(typeof(OperationStatus))]
[JsonSerializable(typeof(ApiErrorResponse))]
[JsonSerializable(typeof(GeoServicesError))]
[JsonSerializable(typeof(Dictionary<string, string>))]
[JsonSerializable(typeof(Dictionary<string, object?>))]
[JsonSerializable(typeof(IReadOnlyList<string>))]
[JsonSerializable(typeof(object))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(sbyte))]
[JsonSerializable(typeof(short))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(long))]
[JsonSerializable(typeof(byte))]
[JsonSerializable(typeof(ushort))]
[JsonSerializable(typeof(uint))]
[JsonSerializable(typeof(ulong))]
[JsonSerializable(typeof(double))]
[JsonSerializable(typeof(float))]
[JsonSerializable(typeof(decimal))]
[JsonSerializable(typeof(bool))]
[JsonSerializable(typeof(DateTimeOffset))]
[JsonSerializable(typeof(DateTime))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(double[]))]
[JsonSerializable(typeof(TimeSpan))]
[JsonSerializable(typeof(byte[]))]
[JsonSerializable(typeof(TimeOnly))]
[JsonSerializable(typeof(DateOnly))]
internal sealed partial class ImportJsonContext : JsonSerializerContext
{
}
