export { HonuaClient } from "./core/client.js";
export { HonuaHttpError } from "./core/errors.js";
export {
  createHonuaOgcFeatures,
  createHonuaService,
  HonuaFeatureLayer,
  HonuaMapService,
  HonuaOgcFeatureCollection,
  HonuaOgcFeatures,
  HonuaService,
} from "./core/surfaces.js";
export type {
  ApplyEditsRequest,
  ExportMapRequest,
  HonuaClientOptions,
  HonuaRawRequest,
  HonuaErrorContext,
  HonuaRequestContext,
  HonuaRequestInterceptor,
  HonuaRequestMutation,
  HonuaResponseContext,
  MapIdentifyRequest,
  MapLegendRequest,
  OgcCollectionRequest,
  OgcCreateItemRequest,
  OgcDeleteItemRequest,
  OgcItemRequest,
  OgcItemsRequest,
  OgcMetadataRequest,
  OgcPatchItemRequest,
  OgcReplaceItemRequest,
  OgcResponseFormat,
  QueryFeaturesRequest,
  QueryMethod,
  QueryRelatedRecordsRequest,
} from "./core/types.js";
export type {
  HonuaFeatureLayerAddAttachmentRequest,
  HonuaFeatureLayerAttachmentData,
  HonuaFeatureLayerApplyEditsRequest,
  HonuaFeatureLayerDeleteAttachmentsRequest,
  HonuaFeatureLayerListAttachmentsRequest,
  HonuaFeatureLayerOptions,
  HonuaFeatureLayerQueryAllRequest,
  HonuaFeatureLayerQueryAttachmentsRequest,
  HonuaFeatureLayerQueryCountRequest,
  HonuaFeatureLayerQueryExtentRequest,
  HonuaFeatureLayerQueryExtentResponse,
  HonuaFeatureLayerQueryObjectIdsRequest,
  HonuaFeatureLayerQueryRelatedRecordsRequest,
  HonuaFeatureLayerQueryRequest,
  HonuaFeatureLayerRequest,
  HonuaFeatureLayerUpdateAttachmentRequest,
  HonuaMapServiceExportMapRequest,
  HonuaMapServiceFindRequest,
  HonuaMapServiceIdentifyRequest,
  HonuaMapServiceLegendRequest,
  HonuaMapServiceOptions,
  HonuaOgcCollectionCreateItemRequest,
  HonuaOgcCollectionDeleteItemRequest,
  HonuaOgcCollectionItemRequest,
  HonuaOgcCollectionItemsRequest,
  HonuaOgcCollectionPatchItemRequest,
  HonuaOgcCollectionReplaceItemRequest,
  HonuaOgcCollectionRequest,
  HonuaOgcCreateItemRequest,
  HonuaOgcDeleteItemRequest,
  HonuaOgcFeatureCollectionOptions,
  HonuaOgcFeaturesOptions,
  HonuaOgcItemRequest,
  HonuaOgcItemsRequest,
  HonuaOgcMetadataRequest,
  HonuaOgcPatchItemRequest,
  HonuaOgcReplaceItemRequest,
  HonuaServiceOptions,
} from "./core/surfaces.js";
