export { HonuaClient } from "./core/client.js";
export { expr, Expr } from "./expr/index.js";
export {
  isHonuaSource,
  isFeatureServiceSource,
  isMapServiceSource,
  isOgcFeaturesSource,
  parseOgcFeaturesUrl,
  validateHonuaStyle,
  createSources,
} from "./style/index.js";
export type {
  HonuaSourceBase,
  HonuaFeatureServiceSourceSpecification,
  HonuaMapServiceSourceSpecification,
  HonuaOgcFeaturesSourceSpecification,
  HonuaSourceSpecification,
  HonuaLayerSpecification,
  HonuaStyleSpecification,
  ParsedOgcFeaturesUrl,
  StyleValidationError,
  ResolvedSource,
} from "./style/index.js";
export type {
  ExprColor,
  ExprFormatted,
  ExprImage,
  ExprValue,
  NumberInput,
  StringInput,
  BooleanInput,
  ColorInput,
  Resolvable,
} from "./expr/index.js";
export {
  setFeatureState,
  getFeatureState,
  removeFeatureState,
  createHoverHandler,
  createSelectionHandler,
} from "./interactions/index.js";
export type {
  FeatureStateMap,
  MapEventTarget,
  InteractiveMap,
  FeatureTarget,
  HoverHandlerOptions,
  HoverHandle,
  SelectionHandlerOptions,
  SelectionHandle,
} from "./interactions/index.js";
export { HonuaMap } from "./map/index.js";
export type {
  HonuaMapOptions,
  HonuaMapEvent,
  HonuaMapEventListener,
  LayerSnapshot,
  ResolvedMapSource,
} from "./map/index.js";
export { HonuaHttpError } from "./core/errors.js";
export {
  createHonuaOgcFeatures,
  createHonuaService,
  HonuaFeatureLayer,
  HonuaMapLayer,
  HonuaMapService,
  HonuaOgcFeatureCollection,
  HonuaOgcFeatures,
  HonuaService,
} from "./core/surfaces.js";
export type {
  ApplyEditsRequest,
  ExportMapRequest,
  HonuaClientOptions,
  HonuaRawRequest,
  HonuaErrorContext,
  HonuaRequestContext,
  HonuaRequestInterceptor,
  HonuaRequestMutation,
  HonuaRetryOptions,
  HonuaResponseContext,
  MapFindRequest,
  MapIdentifyRequest,
  MapLayerQueryRequest,
  MapLegendRequest,
  MapRelatedRecordsRequest,
  OgcCollectionRequest,
  OgcCreateItemRequest,
  OgcDeleteItemRequest,
  OgcItemRequest,
  OgcItemsRequest,
  OgcMetadataRequest,
  OgcPatchItemRequest,
  OgcReplaceItemRequest,
  OgcResponseFormat,
  QueryFeaturesRequest,
  QueryMethod,
  QueryRelatedRecordsRequest,
} from "./core/types.js";
export type {
  HonuaFeatureLayerAddAttachmentRequest,
  HonuaFeatureLayerAttachmentData,
  HonuaFeatureLayerApplyEditsRequest,
  HonuaFeatureLayerDeleteAttachmentsRequest,
  HonuaFeatureLayerListAttachmentsRequest,
  HonuaFeatureLayerOptions,
  HonuaFeatureLayerQueryAllRequest,
  HonuaFeatureLayerQueryAttachmentsRequest,
  HonuaFeatureLayerQueryCountRequest,
  HonuaFeatureLayerQueryExtentRequest,
  HonuaFeatureLayerQueryExtentResponse,
  HonuaFeatureLayerQueryObjectIdsRequest,
  HonuaFeatureLayerQueryRelatedRecordsRequest,
  HonuaFeatureLayerQueryRequest,
  HonuaFeatureLayerRequest,
  HonuaFeatureLayerUpdateAttachmentRequest,
  HonuaMapServiceExportMapRequest,
  HonuaMapServiceFindRequest,
  HonuaMapServiceIdentifyRequest,
  HonuaMapServiceLegendRequest,
  HonuaMapServiceRequest,
  HonuaMapLayerOptions,
  HonuaMapLayerQueryAllRequest,
  HonuaMapLayerQueryCountRequest,
  HonuaMapLayerQueryExtentRequest,
  HonuaMapLayerQueryExtentResponse,
  HonuaMapLayerQueryObjectIdsRequest,
  HonuaMapLayerQueryRelatedRecordsRequest,
  HonuaMapLayerQueryRequest,
  HonuaMapLayerRequest,
  HonuaMapServiceQueryLayerAllRequest,
  HonuaMapServiceQueryLayerCountRequest,
  HonuaMapServiceQueryLayerExtentRequest,
  HonuaMapServiceQueryLayerExtentResponse,
  HonuaMapServiceQueryLayerObjectIdsRequest,
  HonuaMapServiceQueryLayerRelatedRecordsRequest,
  HonuaMapServiceQueryLayerRequest,
  HonuaMapServiceOptions,
  HonuaOgcCollectionCreateItemRequest,
  HonuaOgcCollectionDeleteItemRequest,
  HonuaOgcCollectionItemRequest,
  HonuaOgcCollectionItemsAllRequest,
  HonuaOgcCollectionItemsRequest,
  HonuaOgcCollectionPatchItemRequest,
  HonuaOgcCollectionReplaceItemRequest,
  HonuaOgcCollectionRequest,
  HonuaOgcCreateItemRequest,
  HonuaOgcDeleteItemRequest,
  HonuaOgcFeatureCollectionOptions,
  HonuaOgcFeaturesOptions,
  HonuaOgcItemRequest,
  HonuaOgcItemsAllRequest,
  HonuaOgcItemsRequest,
  HonuaOgcMetadataRequest,
  HonuaOgcPatchItemRequest,
  HonuaOgcReplaceItemRequest,
  HonuaServiceOptions,
} from "./core/surfaces.js";
